// GENERATED by scripts/brand-icons.mjs - do not edit. Run `npm run brand`.
//
// What brand files exist, so the header, footer and schema can reference
// the real logo when it is there and fall back to the monogram when it is
// not, without ever requesting a file that 404s.

export const BRAND_ASSETS = {
  /** The full logo (wordmark + shield), or null while none has been supplied. */
  logo: {"path":"/brand/logo.png","width":535,"height":529} as { path: string; width: number; height: number } | null,
  /** The shield alone, for the header and small placements; null falls back to the logo. */
  mark: {"path":"/brand/logo-mark.png","width":398,"height":320} as { path: string; width: number; height: number } | null,
  /** Square mark, always present (generated from the logo, or the monogram). */
  mark512: '/brand/logo-mark-512.png',
  mark192: '/brand/logo-mark-192.png',
  generatedAt: '2026-09-11',
};
