// src/config/product-details.ts - The long-form half of every product.
//
// PRODUCTS (site.ts) is imported by client components on every page, so
// everything in it ships in the shared JS chunk. The fields here - the full
// description, the assigned keywords and the tags - only render on one
// product page and in the JSON-LD, so they live in this server-only module
// and reach the client as props. Never import this file from a
// 'use client' component.
//
// FAQs are built from each product's own data (see product-faqs.ts) rather
// than stored here; an entry may still carry hand-written `faqs` to override.
//
// Keywords and tags come from the cleaned keyword bank
// (docs/keyword-research/phase0/keyword-bank-clean.csv); the per-product
// table is docs/keyword-research/phase2/product-tags.csv.

import { PRODUCTS, ProductItem } from './site';
import { buildFaqs } from './product-faqs';

export interface ProductDetails {
  fullDescription: string;
  /** The single term this page is meant to win, from the cleaned keyword bank.
   *  Absent where the bank holds no clean (non-parts) term for the product. */
  primaryKeyword?: string;
  /** Up to six secondary terms. Each keyword is assigned to exactly one page
   *  so pages never compete with each other for the same query. */
  supportingKeywords?: string[];
  /** 10 to 14 descriptive tags: brand, model, type, powertrain, spec and
   *  audience terms true of this product. Rendered on the page and in JSON-LD. */
  tags: string[];
  /** Optional hand-written FAQs. When absent they are built by buildFaqs(). */
  faqs?: { q: string; a: string }[];
}

export type ProductFull = ProductItem & ProductDetails;

export const PRODUCT_DETAILS: Record<string, ProductDetails> = {
  "atlas-4-passenger-lifted-lithium-buggy": {
    fullDescription: "Engineered for Australian acreage estates and elite gated communities such as Sanctuary Cove and Hope Island, the Atlas 4-Passenger pairs whisper-quiet 48V lithium power with genuine rough-terrain capability. The three-inch factory lift and 14-inch alloy wheels raise the floor clear of rutted driveways, garden edging and unsealed estate tracks that bottom out a standard-height golf buggy, while custom leather seating and a touchscreen display keep the cabin closer to a car than a course buggy. Four adults travel in comfort without fumes, engine noise or the weekly water-topping that lead-acid buggies demand. Every Atlas is inspected, charge-cycled and road tested at our Yatala QLD depot before enclosed freight, and at this price it qualifies for a complimentary on-farm trial demonstration before you commit.",
    primaryKeyword: "atlas golf carts for sale",
    supportingKeywords: ["atlas golf carts reviews"],
    tags: [
      "atlas 4-passenger lifted lithium buggy",
      "atlas golf buggy",
      "4 seater golf buggy",
      "luxury golf buggy",
      "lithium golf buggy",
      "electric golf buggy",
      "lifted golf buggy",
      "48v lithium",
      "3-inch factory lift",
      "custom leather seats",
      "touchscreen display",
      "gated estates",
      "luxury property owners",
      "resort operators",
    ],
  },
  "evolution-d5-ranger-4-plus-2": {
    fullDescription: "The Evolution D5 Ranger 4+2 carries six passengers across expansive private properties and championship fairways without a second trip. Forward-facing seating in both rows means conversation stays natural and nobody rides backwards over rough ground, which matters on long estate driveways and resort transfers. A 110Ah lithium pack supplies the range for a full day of running, and the nine-inch touchscreen, Bluetooth soundbar and foldable windshield make it as suited to a summer afternoon around the property as to eighteen holes. Families choosing a buggy as a genuine second vehicle tend to land here: it is the largest-capacity model in our luxury range while still driving with the quiet, low-effort manners of a lithium buggy. Tested at Yatala QLD and delivered Australia-wide by enclosed transporter.",
    primaryKeyword: "evolution d5 golf cart for sale",
    supportingKeywords: ["evolution d5 golf cart price", "buy evolution d5 golf cart", "evolution d5 golf cart cost", "evolution d5 golf cart reviews", "evolution 6 seater golf cart", "evolution d5 golf carts"],
    tags: [
      "evolution d5 ranger 4+2 plus",
      "evolution golf buggy",
      "6 seater golf buggy",
      "luxury golf buggy",
      "lithium golf buggy",
      "electric golf buggy",
      "110ah lithium",
      "soundbar with bluetooth",
      "9-inch touchscreen",
      "foldable windshield",
      "high net-worth families",
      "lifestyle acreage owners",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "club-car-onward-4-passenger-lithium": {
    fullDescription: "Club Car's aircraft-grade aluminium frame is the reason the Onward holds its value so well in Australian conditions: aluminium does not rust, so coastal salt air and irrigated fairways cannot eat the chassis out from under the bodywork the way they do with steel-framed imports. The AC drive motor delivers smooth, progressive power up village inclines rather than the surging feel of older DC systems, and the premium canopy top, ergonomic seating and custom metallic paint make this the model buyers choose when the buggy will be parked in front of the house. Zero-maintenance lithium removes acid spills and water topping entirely. Supported from our Yatala QLD depot with genuine Club Car parts held in Australia, backed by an Australian factory warranty and nationwide enclosed freight.",
    primaryKeyword: "club car onward for sale",
    supportingKeywords: ["club car onward 4 passenger for sale", "club car onward 4 passenger price", "club car onward 4 seater", "club car onward price", "club car onward 4 passenger", "onward golf cart for sale"],
    tags: [
      "club car onward 4-passenger lithium",
      "club car golf buggy",
      "4 seater golf buggy",
      "luxury golf buggy",
      "lithium golf buggy",
      "electric golf buggy",
      "ac drive motor",
      "custom metallic paint",
      "ergonomic seating",
      "aircraft-grade aluminum frame",
      "club car brand loyalists",
      "premium golf village residents",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "tara-roadster-2-plus-2-lifted": {
    fullDescription: "The Tara Roadster 2+2 is the value entry into lifted four-seat buggies, and it earns that position with hardware rather than trim. Hydraulic disc brakes on a lifted chassis give you genuine stopping control on sloped semi-rural driveways, where drum brakes fade and feel vague under load. The rear flip seat converts from passenger bench to flat cargo deck in seconds, so the same buggy carries the family down to the gate in the morning and mulch, feed or tools in the afternoon. A full LED light package keeps it usable at dusk on unlit property tracks. For lifestyle blocks and semi-rural acreage that need ground clearance and dual-purpose flexibility without a luxury price tag, this is the most sensible buy in the range.",
    primaryKeyword: "tara golf carts price",
    supportingKeywords: ["tara roadster 2 golf cart reviews", "tara roadster 2 golf cart"],
    tags: [
      "tara roadster 2+2 lifted",
      "tara golf buggy",
      "4 seater golf buggy",
      "luxury golf buggy",
      "lithium golf buggy",
      "electric golf buggy",
      "lifted golf buggy",
      "lithium battery",
      "lifted chassis",
      "hydraulic disc brakes",
      "led light package",
      "budget-luxury buyers",
      "semi-rural properties",
      "golf buggy australia",
    ],
  },
  "ezgo-express-l6-lithium": {
    fullDescription: "The E-Z-GO Express L6 seats six on a single chassis, which makes it the natural choice for resort hospitality, holiday parks and large family estates that move groups rather than pairs. High ground clearance and heavy-duty suspension let it cross gravel service roads and grassed overflow areas without shaking guests loose, and E-Z-GO's ELiTE lithium technology means no fumes, no engine noise and no daily battery maintenance for the staff running it. For commercial venues that is the whole argument: a petrol shuttle needs fuel handling, servicing and somewhere to idle away from guests, while a lithium shuttle simply plugs in overnight. Supplied with Australian warranty support and dispatched by enclosed transporter from our Yatala QLD depot to any state or territory.",
    primaryKeyword: "ezgo express l6 for sale",
    supportingKeywords: ["ezgo express l6 price", "ezgo 6 seater golf cart"],
    tags: [
      "e-z-go express l6 lithium",
      "e-z-go golf buggy",
      "6 seater golf buggy",
      "luxury golf buggy",
      "lithium golf buggy",
      "electric golf buggy",
      "elite lithium technology",
      "6-passenger seating",
      "high ground clearance",
      "heavy duty suspension",
      "resort transport",
      "large family estates",
      "commercial venues",
      "golf buggy australia",
    ],
  },
  "lvtong-4-seater-resort-cruiser": {
    fullDescription: "A proven workhorse across Australian caravan parks and holiday resorts, the LVTONG 4-Seater Resort Cruiser is specified for operators who count running cost per year rather than features per brochure. The 4kW AC motor pulls four adults and luggage up park inclines without straining, the maintenance-free lithium pack removes the labour of watering and equalising a lead-acid bank, and the on-board charger means any standard outlet becomes a charging point without extra infrastructure. A heavy-duty bumper takes the knocks that shared-use vehicles inevitably collect from bollards, kerbs and gateposts. For hotels, holiday parks and community centres running a small fleet, it delivers dependable all-day duty with low maintenance overheads. Freight is quoted per delivery postcode and every unit is tested at Yatala QLD before dispatch.",
    primaryKeyword: "resort buggy for sale",
    supportingKeywords: ["4 seater electric golf cart", "4 seat electric golf cart", "lv tong electric golf carts", "lvtong maintenance free battery"],
    tags: [
      "lvtong 4-seater resort cruiser",
      "lvtong golf buggy",
      "4 seater golf buggy",
      "luxury golf buggy",
      "lithium golf buggy",
      "electric golf buggy",
      "4kw ac motor",
      "maintenance-free lithium",
      "on-board charger",
      "heavy duty bumper",
      "hotels holiday parks community centers",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "4 seater electric golf cart",
    ],
  },
  "club-car-tempo-lithium-2025": {
    fullDescription: "The 2025 Club Car Tempo is built for the golfer who plays the same course every week and wants the buggy to disappear underneath them. The Monaco drive system delivers smooth hill-climbing acceleration without the lurch that makes a full bag shift on steep fairway transitions, and the automotive-style dashboard puts digital battery metrics in front of you so range stops being guesswork on the back nine. A rust-proof aluminium frame is the long-term argument: Australian courses combine irrigation, humidity and coastal air, and an aluminium chassis simply does not corrode the way steel does. Golf bag caddy security keeps clubs stable through turns. Private course members and avid golfers choose the Tempo when they intend to keep a buggy for many seasons rather than trade it quickly.",
    primaryKeyword: "club car tempo for sale",
    supportingKeywords: ["club car tempo price", "club car tempo electric", "tempo golf cart for sale"],
    tags: [
      "club car tempo lithium 2025 model",
      "club car golf buggy",
      "2 seater golf buggy",
      "electric golf buggy",
      "lithium golf buggy",
      "golf buggy for sale australia",
      "monaco drive system",
      "rust-proof aluminum frame",
      "automotive-style dashboard",
      "avid golfers",
      "private course members",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "club car tempo price",
    ],
  },
  "ezgo-rxv-elite-lithium": {
    fullDescription: "The defining feature of the RXV ELiTE is what happens when you lift your foot: the automatic electromagnetic brake holds the buggy the moment you step off the throttle, so it will not creep or run away on a steep fairway slope or a sloped village driveway. For retirement village residents and anyone parking on an incline, that single behaviour is worth more than any spec on the sheet. Samsung SDI lithium batteries supply consistent power delivery through the full charge rather than fading toward the end like lead-acid, and the high-efficiency AC drive keeps consumption low across a full round. Fleet buyers value the reduced servicing burden across many units. Supported with Australian parts and warranty from our Yatala QLD depot, delivered nationwide by enclosed transporter.",
    primaryKeyword: "ezgo rxv elite for sale",
    supportingKeywords: ["ezgo elite golf cart for sale", "ezgo elite golf cart price", "ezgo rxv golf cart for sale", "ezgo rxv golf cart price", "ezgo rxv electric golf cart", "ezgo rxv"],
    tags: [
      "e-z-go rxv elite lithium",
      "e-z-go golf buggy",
      "2 seater golf buggy",
      "electric golf buggy",
      "lithium golf buggy",
      "golf buggy for sale australia",
      "samsung sdi lithium batteries",
      "automatic electromagnetic brake",
      "high-efficiency ac drive",
      "golfers fleet buyers retirement village residents",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "ezgo elite golf cart for sale",
      "ezgo elite golf cart price",
    ],
  },
  "yamaha-drive2-ac-lithium": {
    fullDescription: "Independent front and rear suspension is rare at this level and it is the reason the Drive2 rides the way it does. Most buggies transmit every rut and root straight into the seat frame; independent suspension lets each wheel move on its own, so rough turf, unsealed tracks and cart-path joins arrive as a muted movement rather than a jolt. Combined with ultra-comfort seats, that makes the Drive2 the model to choose if you or a passenger have a back that objects to rough ground, or if the daily run crosses unmade surfaces rather than manicured fairway. Wide dash storage takes phones, scorecards, keys and a drink without anything sliding off through turns. Tested at our Yatala QLD depot and freighted enclosed to any Australian address.",
    primaryKeyword: "yamaha drive2 golf cart for sale",
    supportingKeywords: ["yamaha drive 2 golf cart for sale", "yamaha drive 2 golf cart price", "yamaha drive 2 electric golf cart", "yamaha electric carts", "electric golf cart yamaha"],
    tags: [
      "yamaha drive2 ac lithium",
      "yamaha golf buggy",
      "2 seater golf buggy",
      "electric golf buggy",
      "lithium golf buggy",
      "golf buggy for sale australia",
      "ultra-comfort seats",
      "wide dash storage",
      "golfers wanting smooth ride comfort",
      "course fleets",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "yamaha drive 2 golf cart for sale",
      "yamaha drive 2 golf cart price",
    ],
  },
  "tara-spirit-pro-2-seater": {
    fullDescription: "The Tara Spirit Pro is aimed squarely at private golfers stepping away from an ageing lead-acid buggy, and it is priced so that the upgrade is realistic rather than aspirational. A lightweight frame means less mass for the motor to move, which translates directly into usable range from the lithium pack, and the rapid charger shortens turnaround between rounds so the buggy is ready when you are rather than the next morning. The digital speedometer gives you a real read on pace instead of a guess, and a sweater basket handles the layers that Australian mornings demand and afternoons make redundant. Cost-conscious buyers get modern lithium reliability, current styling and an end to acid spills and water topping without paying for badge prestige.",
    primaryKeyword: "tara electric golf cart",
    supportingKeywords: ["2 seater electric golf carts", "2 seat electric golf cart"],
    tags: [
      "tara spirit pro 2-seater",
      "tara golf buggy",
      "2 seater golf buggy",
      "electric golf buggy",
      "lithium golf buggy",
      "golf buggy for sale australia",
      "lightweight frame",
      "rapid charger",
      "digital speedometer",
      "sweater basket",
      "cost-conscious private golfers",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "2 seater electric golf carts",
    ],
  },
  "lvtong-2-passenger-golf-buggy": {
    fullDescription: "The LVTONG 2-Passenger is specified so you can roll straight onto your local course without a shopping list of extras. The split foldable windshield, dual sand bottles and caddy bag holder are fitted rather than optional, which is where competing budget buggies quietly recover margin once you start adding the parts you actually need. A 48V system keeps it compact, agile and energy efficient around tight club layouts and shorter suburban courses, and the two-seat footprint parks and stores in a standard garage or club bay without difficulty. For budget-focused private buyers and smaller local clubs building a modest fleet, it delivers dependable electric running with no hidden extra costs. Prices include GST and freight is quoted against your delivery postcode.",
    primaryKeyword: "2 person electric golf cart",
    supportingKeywords: ["2 person golf cart", "two seater electric golf cart", "lv tong australia golf carts"],
    tags: [
      "lvtong 2-passenger golf buggy",
      "lvtong golf buggy",
      "2 seater golf buggy",
      "electric golf buggy",
      "lithium golf buggy",
      "golf buggy for sale australia",
      "48v system",
      "split foldable windshield",
      "dual sand bottles",
      "caddy bag holder",
      "budget private buyers",
      "local golf clubs",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "evolution-classic-2-plus": {
    fullDescription: "The Evolution Classic 2 Plus brings automotive-level instrumentation to a two-seat buggy, which is exactly what buyers moving across from a modern car expect and rarely find. A 6.3-inch LCD screen with reverse camera compatibility, side mirrors with integrated turn signals and two-tone seating make it road-aware in a way that matters on estate roads shared with vehicles, not just on fairway. Turn signals and mirrors are also the features most often required when a buggy is used around traffic on private roads or a gated community's internal network. Lithium-ion power keeps it quiet enough to hold a conversation at speed and removes the maintenance routine lead-acid demands. Dispatched from Yatala QLD with Australian warranty support and enclosed nationwide freight.",
    primaryKeyword: "evolution golf carts for sale",
    supportingKeywords: ["evolution 2 seater golf carts", "evolution golf carts near me"],
    tags: [
      "evolution classic 2 plus",
      "evolution golf buggy",
      "2 seater golf buggy",
      "electric golf buggy",
      "lithium golf buggy",
      "golf buggy for sale australia",
      "6.3-inch lcd screen",
      "lithium-ion battery",
      "two-tone seats",
      "side mirrors with turn signals",
      "modern tech-focused golfers",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "evolution 2 seater golf carts",
    ],
  },
  "atlas-4-seater-heavy-duty-lifted-350a": {
    fullDescription: "The 350-amp controller is the specification that matters on this buggy. Controller amperage governs how much current the motor can draw under load, which is what decides whether a fully laden four-seater walks up a steep farm track or bogs down halfway and overheats. Paired with four-wheel hydraulic disc brakes, it also means you can come back down that same hill under control rather than riding the brakes to the bottom. Rugged all-terrain tyres and a steel brush guard handle the scrub, stumps and gateposts that acreage driving involves. For hilly Australian properties where a standard golf buggy has already disappointed you, this is the model built to answer that specific problem. Tested at Yatala QLD and freighted enclosed anywhere in Australia.",
    primaryKeyword: "atlas golf carts price",
    supportingKeywords: ["atlas golf cart price range", "atlas golf carts for sale near me", "atlas golf cart reviews consumer reports"],
    tags: [
      "atlas 4-seater heavy duty lifted 350a",
      "atlas golf buggy",
      "off road golf buggy",
      "electric golf buggy",
      "lifted golf buggy",
      "lithium golf buggy",
      "350a controller",
      "4-wheel hydraulic brakes",
      "rugged all-terrain tires",
      "brush guard",
      "acreage owners",
      "hilly farm tracks",
      "rural properties",
      "golf buggy australia",
    ],
  },
  "evolution-d-max-gt4-off-road": {
    fullDescription: "The D-Max GT4 is the only buggy in our range built around recovery rather than comfort. A heavy-duty roll cage and long-travel independent off-road suspension let it work genuine trail terrain instead of merely surviving a gravel driveway, and the integrated winch means a bogged vehicle, a fallen limb or a stuck gate is a job you finish yourself rather than a call you make. Hunters and large property managers choose it because the working day happens well away from the shed. The high-power AC drivetrain delivers torque quietly, which matters more than most buyers expect around livestock and wildlife. This is a serious piece of equipment rather than a lifted golf buggy, and it is specified accordingly.",
    primaryKeyword: "evolution electric golf cart",
    supportingKeywords: ["evolution golf cart reviews"],
    tags: [
      "evolution d-max gt4 off-road",
      "evolution golf buggy",
      "off road golf buggy",
      "electric golf buggy",
      "lithium golf buggy",
      "heavy duty roll cage",
      "independent off-road suspension",
      "integrated winch",
      "high-power ac engine",
      "hunters large property managers trail enthusiasts",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "evolution golf cart reviews",
    ],
  },
  "ezgo-express-s4-lifted-high-torque": {
    fullDescription: "The Express S4 solves the problem every rural family runs into: you need seats in the morning and a tray in the afternoon, and you do not want two vehicles. The rear seat flips over into a flatbed utility platform, so the school-run configuration becomes the feed-and-tools configuration in seconds without unbolting anything. A four-inch factory lift on Desert Eagle all-terrain tyres gives it the clearance to cross paddock ruts, washouts and unsealed tracks that would ground a standard-height buggy. Because the lift is factory rather than aftermarket, the geometry, braking and warranty are engineered together rather than bolted on afterwards. For farm transport and rural families it is the most flexible chassis we stock.",
    primaryKeyword: "ezgo express s4 for sale",
    supportingKeywords: ["ezgo express s4 price", "ezgo express s4 reviews", "ezgo golf cart lifted", "ezgo express s4 elite for sale"],
    tags: [
      "e-z-go express s4 lifted high-torque",
      "e-z-go golf buggy",
      "off road golf buggy",
      "electric golf buggy",
      "lifted golf buggy",
      "lithium golf buggy",
      "4-inch lift kit",
      "desert eagle all-terrain tires",
      "convertible rear seat to cargo bed",
      "rural families",
      "farm transport",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "ezgo express s4 price",
    ],
  },
  "lvtong-rough-terrain-lifted-buggy": {
    fullDescription: "Built for farmers, orchard owners and bush properties where the terrain is the job rather than the obstacle. A reinforced steel subframe carries the twisting loads that rough ground puts through a chassis, and the front bash guard takes the low-speed impacts that orchard rows, stumps and undergrowth inevitably deliver. High ground clearance keeps the underbody clear of the ruts and irrigation lines that catch out standard buggies. The front LED light bar is the feature owners end up valuing most: stock work, harvest and property checks do not stop at sunset, and a high-intensity bar turns a dark row into a working one. Straightforward, reinforced and specified for work rather than presentation.",
    primaryKeyword: "all terrain golf cart for sale",
    tags: [
      "lvtong rough-terrain lifted buggy",
      "lvtong golf buggy",
      "off road golf buggy",
      "electric golf buggy",
      "lifted golf buggy",
      "lithium golf buggy",
      "high ground clearance",
      "reinforced steel subframe",
      "front led light bar",
      "farmers orchard owners bush properties",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "club-car-onward-lifted-efi-petrol": {
    fullDescription: "For properties without reliable grid power, or runs too long to plan around a charge cycle, electronic fuel injection changes the maths. The Onward Lifted EFI carries a Kohler 14HP EFI petrol engine, so range is limited by the jerry can rather than the battery pack, and refuelling takes a minute rather than a night. EFI also means it starts cleanly cold, meters fuel accurately at altitude and across temperature swings, and avoids the carburettor tuning that older petrol buggies demanded every season. Lifted suspension and all-terrain tread give it the clearance to work the same ground as our electric lifted models. For remote and long-distance farm use, petrol remains the honest answer and this is the refined version of it.",
    primaryKeyword: "club car onward lifted",
    supportingKeywords: ["club car onward lifted 4 passenger", "club car lifted golf carts"],
    tags: [
      "club car onward lifted efi petrol",
      "club car golf buggy",
      "off road golf buggy",
      "petrol golf buggy",
      "lifted golf buggy",
      "kohler 14hp efi petrol engine",
      "lifted suspension",
      "all-terrain tread",
      "buyers without grid power access",
      "long-distance farm users",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "club car onward lifted 4 passenger",
      "club car lifted golf carts",
    ],
  },
  "tara-roadster-4-off-road": {
    fullDescription: "Gearing, not power, is what gets a loaded buggy up a steep incline, and the Tara Roadster 4 is built around a high-torque gear reduction ratio chosen for exactly that. Lower gearing multiplies motor torque at the wheel, so sustained climbs happen at a steady pace instead of a struggle that heats the motor and drains the pack. Twelve-inch off-road rims put more sidewall and tread between the rim and the rock than a standard golf wheel, which is what prevents pinch damage on rutted acreage trails. An optional rear cargo tray adds working capacity when the buggy is not carrying passengers. For property owners whose main complaint is that their current buggy cannot climb, this is the direct fix.",
    primaryKeyword: "roadster golf cart for sale",
    tags: [
      "tara roadster 4 off-road",
      "tara golf buggy",
      "off road golf buggy",
      "electric golf buggy",
      "lithium golf buggy",
      "high-torque gear ratio",
      "12-inch off-road rims",
      "rear cargo tray option",
      "property owners needing steep incline power",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "club-car-carryall-700-electric-utility": {
    fullDescription: "A 680kg payload puts the Carryall 700 in genuine work-vehicle territory rather than utility-buggy territory. The six-foot aluminium cargo box is the right material for the job: aluminium will not rust out from wet turf, fertiliser, sand or salt air the way a steel tray does, and it keeps unladen weight down so more of the payload rating is available for cargo. An integrated heavy-duty tow hitch extends that further to trailers, spreaders and turf equipment. Councils, maintenance teams and commercial farms specify it because lithium removes fuel handling, engine servicing and exhaust from shared work areas entirely. Delivered Australia-wide by enclosed transporter with freight quoted against your site postcode.",
    primaryKeyword: "club car carryall 700 for sale",
    supportingKeywords: ["club car carryall 700 price", "club car utility golf cart"],
    tags: [
      "club car carryall 700 electric utility",
      "club car golf buggy",
      "utility buggy",
      "commercial buggy",
      "electric utility buggy",
      "farm buggy",
      "cargo buggy",
      "6-foot aluminum cargo box",
      "680kg payload capacity",
      "heavy-duty tow hitch",
      "councils maintenance teams commercial farms",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "club car carryall 700 price",
    ],
  },
  "ezgo-cushman-hauler-pro-lithium": {
    fullDescription: "The Hauler PRO runs a 72V AC drive rather than the 48V systems common elsewhere in the range, and higher system voltage is what lets it move heavy loads at lower current, running cooler and holding performance through a full working shift. A 544kg towing capacity covers turf equipment, trailers and grounds machinery. The optional electric dump bed is the feature that changes the working day: tipping a load of sand, mulch or clippings becomes a button rather than a shovel, which is the difference between one trip and one trip plus twenty minutes. Turf managers, schools and university campuses choose it for exactly that combination of capacity and quiet, fume-free operation around students and public areas.",
    primaryKeyword: "cushman utility cart for sale",
    supportingKeywords: ["cushman electric utility cart", "cushman electric cart", "cushman utility cart", "cushman electric golf cart"],
    tags: [
      "e-z-go cushman hauler pro lithium",
      "e-z-go golf buggy",
      "utility buggy",
      "commercial buggy",
      "electric utility buggy",
      "cargo buggy",
      "72v ac drive",
      "electric cargo bed dump option",
      "544kg towing capacity",
      "turf managers schools university campuses",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "cushman electric utility cart",
      "cushman electric cart",
    ],
  },
  "yamaha-umax-rally-efi-petrol": {
    fullDescription: "The UMAX Rally is Yamaha's commercial workhorse, powered by a 402cc EFI engine sized for sustained duty rather than short bursts. Livestock properties and large regional venues run these hard for long days, and the details reflect it: a side-filling fuel tank means refuelling without climbing over the bed or unloading first, and substantial under-hood dry storage keeps tools, medications, tags and paperwork out of the weather rather than sliding loose in an open tray. Bucket seats hold you in place across paddock ground instead of letting you slide with every camber change. Electronic fuel injection keeps starting reliable through cold mornings and hot afternoons alike, which matters when the vehicle is part of the day's routine.",
    primaryKeyword: "yamaha umax utility cart for sale",
    supportingKeywords: ["yamaha umax utility cart"],
    tags: [
      "yamaha umax rally efi petrol",
      "yamaha golf buggy",
      "efi utility buggy",
      "utility buggy",
      "commercial buggy",
      "petrol utility buggy",
      "farm buggy",
      "402cc yamaha efi engine",
      "side-filling fuel tank",
      "bucket seats",
      "under-hood storage",
      "livestock properties",
      "large regional venues",
      "golf buggy australia",
    ],
  },
  "evolution-700-heavy-commercial-utility": {
    fullDescription: "Specified for facility management and security patrol work, where the vehicle runs continuously across a defined site rather than covering open country. The drop-side flatbed tray is the practical distinction: dropping a side lets you load and unload from any angle, including with a trolley or by sliding long items on, instead of lifting everything up and over a fixed wall. Lithium-ion power keeps patrol runs quiet enough not to disturb residents, guests or wildlife on night rounds, and removes refuelling from a shift pattern entirely. High-output automotive headlights and a fitted tow bar make it useful after dark and behind a trailer. A straightforward industrial platform, supported from our Yatala QLD depot.",
    primaryKeyword: "evolution golf cart price",
    supportingKeywords: ["evolution golf cart dealers"],
    tags: [
      "evolution 700 heavy commercial utility",
      "evolution golf buggy",
      "utility buggy",
      "commercial buggy",
      "electric utility buggy",
      "cargo buggy",
      "drop-side flatbed tray",
      "lithium-ion",
      "high-output headlights",
      "tow bar",
      "facility management",
      "security patrols",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "lvtong-commercial-flatbed-cargo-buggy": {
    fullDescription: "Low loader height is the reason this model exists. Every centimetre of deck height is a lift your staff perform on every item, all day, and a low steel mesh deck turns awkward lifts into slides. The mesh itself drains, so wet nursery stock, hosed-down bins and rain do not pool in the tray. Regenerative braking recovers energy on the descents and, more usefully indoors, gives controlled slowing without riding the brake pedal through a warehouse aisle. Warehouses, nurseries and eco-resort groundskeepers choose it as a load-carrying platform rather than a passenger vehicle with a tray attached. Quiet, low-slung and specified for repetitive handling work across sealed and semi-sealed surfaces.",
    primaryKeyword: "flatbed golf cart for sale",
    supportingKeywords: ["electric flatbed golf cart", "electric cargo golf cart", "cargo golf cart for sale", "cargo buggy for sale", "electric buggy with tray", "golf buggy with tray for sale"],
    tags: [
      "lvtong commercial flatbed / cargo buggy",
      "lvtong golf buggy",
      "utility buggy",
      "commercial buggy",
      "electric utility buggy",
      "resort shuttle buggy",
      "cargo buggy",
      "steel mesh flatbed",
      "low loader height",
      "regenerative braking",
      "warehouses nurseries eco-resort groundskeepers",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "electric flatbed golf cart",
    ],
  },
  "club-car-transporter-6-commercial": {
    fullDescription: "Where the Carryall carries loads, the Transporter 6 carries people, and it is built for shuttle duty at airports, mine sites and large resorts. Six forward-facing seats keep every passenger travelling in the direction of movement, which matters on longer transfers and with luggage. ArmorFlex bodywork resists the dents and scuffs that shared shuttle vehicles collect from trolleys, cases, bollards and inattentive drivers, so the fleet still looks presentable after a season rather than a fortnight. Heavy-duty axles carry a full load of adults and bags without the sag that shortens component life. For any operator whose vehicle is the first impression a guest receives, the durability specification pays for itself.",
    primaryKeyword: "club car transporter golf carts for sale",
    supportingKeywords: ["club car golf buggy for sale", "club car golf buggy"],
    tags: [
      "club car transporter 6 commercial",
      "club car golf buggy",
      "utility buggy",
      "commercial buggy",
      "electric utility buggy",
      "resort shuttle buggy",
      "6 seater golf buggy",
      "6-passenger forward-facing seating",
      "armor-flex body",
      "heavy-duty axles",
      "airports mines large resort guest shuttles",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "club car golf buggy for sale",
    ],
  },
  "yamaha-drive2-quiettech-efi-petrol": {
    fullDescription: "QuietTech exists to solve the one real objection to petrol: the noise. Yamaha's engineering brings the Drive2 close enough to electric in sound that conversation at speed stays comfortable, while keeping the unlimited range and one-minute refuelling that petrol offers. For golfers and property owners who want to cover long distances without planning around a charge cycle, but who have ruled out petrol because of engine drone, this is the model that reopens the option. Fully independent rear suspension keeps rough turf and unsealed tracks from reaching the seat frame, and high fuel efficiency keeps the running cost sensible across long weekly distances. Supported with Australian parts and warranty from our Yatala QLD depot.",
    primaryKeyword: "yamaha petrol golf buggy for sale",
    supportingKeywords: ["yamaha petrol golf cart for sale", "yamaha petrol golf cart price", "yamaha efi golf cart for sale", "yamaha efi golf cart price", "yamaha gas golf cart for sale"],
    tags: [
      "yamaha drive2 quiettech efi petrol",
      "yamaha golf buggy",
      "petrol golf buggy",
      "petrol golf cart",
      "efi golf buggy",
      "fully independent rear suspension",
      "high mpg",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "yamaha petrol golf cart for sale",
      "yamaha petrol golf cart price",
      "yamaha efi golf cart for sale",
      "yamaha efi golf cart price",
      "yamaha gas golf cart for sale",
    ],
  },
  "club-car-tempo-efi-petrol": {
    fullDescription: "The 25.4-litre fuel tank is the headline for remote users, and the reason is simple arithmetic: a larger tank means fewer trips to town, fewer jerry cans and longer stretches between refuelling on properties where the nearest bowser is a genuine drive away. The 14HP overhead-cam single-cylinder engine is a conventional, proven layout that rural mechanics understand and that does not require specialist tooling to service. Traditional rural users and remote property caretakers tend to prefer exactly this: mechanical simplicity, long range and parts availability over touchscreens and app connectivity. Club Car build quality underpins it, and the whole vehicle is supported from our Yatala QLD depot with nationwide enclosed freight quoted per postcode.",
    primaryKeyword: "club car petrol golf buggy",
    supportingKeywords: ["club car petrol golf cart", "club car petrol golf carts for sale", "club car tempo gas"],
    tags: [
      "club car tempo efi petrol",
      "club car golf buggy",
      "petrol golf buggy",
      "petrol golf cart",
      "efi golf buggy",
      "14hp single cylinder engine",
      "overhead cam",
      "tank capacity 25.4l",
      "traditional rural users",
      "remote property caretakers",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "club car petrol golf cart",
      "club car petrol golf carts for sale",
    ],
  },
  "ezgo-freedom-rxv-gas": {
    fullDescription: "The EX1 engine was designed around a maintenance problem rather than a power target. Its closed-loop electronic fuel injection continuously adjusts the fuel mixture based on live exhaust readings, which keeps combustion clean, reduces the fuel dilution and carbon build-up that contaminate oil, and lengthens the interval between oil changes. For farmers and acreage owners that translates into fewer hours spent servicing and more spent using the vehicle. Closed-loop metering also means it adapts automatically to temperature and altitude instead of needing seasonal adjustment. If your previous petrol buggy felt like a maintenance commitment, the Freedom RXV is the direct answer to that experience. Dispatched from Yatala QLD with Australian warranty support.",
    primaryKeyword: "ezgo freedom rxv for sale",
    supportingKeywords: ["ezgo gas golf cart for sale", "ezgo rxv gas golf cart", "ezgo freedom rxv price australia", "ezgo freedom golf cart for sale", "ezgo rxv freedom ex1 gas"],
    tags: [
      "e-z-go freedom rxv gas",
      "e-z-go golf buggy",
      "petrol golf buggy",
      "petrol golf cart",
      "efi golf buggy",
      "ex1 closed-loop efi petrol engine",
      "low maintenance",
      "energy efficient",
      "farmers acreage owners",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "ezgo gas golf cart for sale",
      "ezgo rxv gas golf cart",
      "ezgo freedom rxv price australia",
    ],
  },
  "cushman-hauler-1200-gas-utility": {
    fullDescription: "The 13.5HP Kawasaki engine is the reason this model has the reputation it does. Kawasaki's small industrial engines are a known quantity on Australian properties, which means parts, service knowledge and reliability are all readily available rather than dependent on a single importer. A manual dump bed handles 544kg of sand, gravel, feed or spoil and tips it without hydraulics to fail or maintain, which on heavy agricultural work is a feature rather than a compromise. Fewer systems means fewer things to go wrong a long way from the shed. For properties that need a genuinely rugged load carrier and value mechanical simplicity over convenience features, the Hauler 1200 is the straightforward choice.",
    primaryKeyword: "cushman golf cart for sale",
    supportingKeywords: ["cushman carts for sale", "cushman buggy for sale", "cushman cart models"],
    tags: [
      "cushman hauler 1200 gas utility",
      "cushman golf buggy",
      "petrol golf buggy",
      "petrol golf cart",
      "petrol utility buggy",
      "13.5hp kawasaki engine",
      "manual dump bed",
      "544kg total load capacity",
      "heavy agricultural property work",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "cushman carts for sale",
      "cushman buggy for sale",
      "cushman cart models",
    ],
  },
  "yamaha-umax-one-efi-utility": {
    fullDescription: "The UMAX One is the compact end of the commercial range, sized for small farms, lifestyle blocks and sport venues where a full-size utility vehicle is more machine than the site needs. A one-hand tailgate latch sounds minor until you are carrying something in the other arm, which on a working vehicle is most of the time. The compact utility bed carries a genuine load without the length that makes manoeuvring awkward around sheds, gates and spectator areas. Wide contoured bucket seats keep the driver comfortable across a long day rather than merely seated. Yamaha EFI keeps starting and running reliable across the temperature range Australian sites actually experience.",
    primaryKeyword: "yamaha umax golf cart for sale",
    tags: [
      "yamaha umax one efi utility",
      "yamaha golf buggy",
      "petrol golf buggy",
      "petrol golf cart",
      "efi golf buggy",
      "petrol utility buggy",
      "compact utility bed",
      "one-hand latch system",
      "high comfort bucket seats",
      "small farms",
      "lifestyle blocks",
      "sport venues",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "club-car-carryall-300-petrol": {
    fullDescription: "A tight turning circle is the specification that decides whether a utility vehicle is useful around buildings, and the Carryall 300 is built for exactly that environment. Schools, grounds teams and light commercial sites work between structures, walkways, garden beds and parked cars, where a large turning radius means three-point turns all day. The rustproof aircraft-grade aluminium bed is the durability argument: grounds work means wet clippings, fertiliser and sand, all of which corrode a steel tray from the inside out over a few seasons. Aluminium simply does not. A 14HP engine provides adequate power for the loads this class carries without the running costs of a larger unit. Supported from Yatala QLD.",
    primaryKeyword: "club car carryall for sale",
    supportingKeywords: ["club car carryall price"],
    tags: [
      "club car carryall 300 petrol",
      "club car golf buggy",
      "petrol golf buggy",
      "petrol golf cart",
      "efi golf buggy",
      "petrol utility buggy",
      "14hp engine",
      "compact turning radius",
      "light commercial",
      "school groundskeeping",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "club car carryall price",
    ],
  },
  "mgi-ai-navigator-gps-remote-buggy": {
    fullDescription: "The gyroscope straight tracker is what separates a good remote buggy from a frustrating one. Without it, any motorised buggy drifts off line on a cambered fairway and you spend the walk correcting it; the gyroscope holds the chosen heading across slopes so the buggy tracks where you pointed it. Full directional remote control means you can send it ahead to the next tee or around a bunker while you play, and the integrated touchscreen GPS puts distances in front of you without reaching for a phone or a separate rangefinder. For private golfers who walk the course, this is the flagship of the MGI range and the model to choose if you want the buggy to require no attention at all.",
    primaryKeyword: "mgi ai navigator gps+ remote golf buggy",
    supportingKeywords: ["mgi ai navigator gps+ buggy", "mgi golf buggy remote control", "mgi ai navigator gps+ review", "mgi navigator", "mgi ai navigator gps+"],
    tags: [
      "mgi ai navigator gps remote buggy",
      "mgi golf buggy",
      "motorised golf buggy",
      "electric golf trolley",
      "walk behind golf buggy",
      "lithium golf trolley",
      "remote control golf buggy",
      "gps golf trolley",
      "full directional remote",
      "integrated touchscreen gps",
      "gyroscope straight tracker",
      "private golfers walking the course",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "mgi-zip-navigator-all-terrain": {
    fullDescription: "Twin 230W motors drive the wheels independently, which is what gives the Zip Navigator its footing on wet slopes and cambered lies where a single-motor buggy scrabbles and slides sideways. The rear fold-out fifth wheel is the other half of the story: it sits behind the main axle and stops the buggy tipping backwards when climbing steep contours, a genuine risk on undulating Australian courses when a full bag sits high on the frame. A 24V 380Wh lithium pack supplies the sustained power both motors need. For walk-behind golfers whose home course has real elevation rather than gentle undulation, this is the stability specification worth paying for.",
    primaryKeyword: "mgi zip navigator all terrain motorised golf buggy",
    supportingKeywords: ["mgi navigator all terrain", "mgi navigator all terrain golf buggy reviews", "mgi zip navigator", "mgi zip navigator all terrain"],
    tags: [
      "mgi zip navigator all-terrain",
      "mgi golf buggy",
      "motorised golf buggy",
      "electric golf trolley",
      "walk behind golf buggy",
      "lithium golf trolley",
      "twin 230w motors",
      "24v 380wh lithium battery",
      "rear anti-tip 5th wheel",
      "walk-behind golfers wanting all-terrain stability",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "mgi navigator all terrain",
      "mgi navigator all terrain golf buggy reviews",
    ],
  },
  "mgi-2024-zip-x5-36-hole-lithium": {
    fullDescription: "Built for golfers who play long days, the Zip X5 carries a 36-hole lithium battery so a second round does not become a range calculation. Downhill speed control is the feature that earns its keep on hilly courses: rather than running away from you and forcing a jog, the buggy holds a steady walking pace on descents automatically. An electronic park brake holds it in place on a slope while you play your shot, instead of chocking a wheel or angling it across the hill. Distance control lets you send it forward a set distance and have it stop on its own. Straightforward, well-sorted and specified for volume golf rather than occasional rounds.",
    primaryKeyword: "mgi zip x5 motorised golf buggy",
    supportingKeywords: ["mgi zip x5 review", "mgi zip x5 best price", "mgi zip x5 electric golf cart"],
    tags: [
      "mgi 2024 zip x5 36-hole lithium",
      "mgi golf buggy",
      "motorised golf buggy",
      "electric golf trolley",
      "walk behind golf buggy",
      "lithium golf trolley",
      "downhill speed control",
      "electronic park brake",
      "distance control function",
      "golfers playing long 36-hole days",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "mgi zip x5 review",
      "mgi zip x5 best price",
    ],
  },
  "powakaddy-fx7-gps-lithium": {
    fullDescription: "PowaKaddy's FX7 brings UK engineering and a genuinely usable screen to the walk-behind category. The 3.5-inch OCA full colour touchscreen comes preloaded with over 40,000 courses worldwide, so it works on your home course and on holiday without a subscription hunt or a manual download before every round. OCA bonding is the reason it stays readable in Australian sunlight where cheaper laminated screens wash out. The high-power 30V Plug 'n' Play lithium system fits and removes without tools, which matters when the buggy lives in a car boot between rounds and the battery comes inside to charge. For tech-focused golfers who want the data on the buggy rather than the wrist, this is the pick.",
    primaryKeyword: "powakaddy fx7 gps electric golf trolley",
    supportingKeywords: ["powakaddy fx7 gps", "powakaddy fx7 review", "powakaddy electric golf buggies", "powakaddy golf trolley", "fx7 powakaddy", "powakaddy fx7 ebs"],
    tags: [
      "powakaddy fx7 gps lithium",
      "powakaddy golf buggy",
      "motorised golf buggy",
      "electric golf trolley",
      "walk behind golf buggy",
      "lithium golf trolley",
      "gps golf trolley",
      "high-power 30v plug n play lithium",
      "tech-savvy golfers seeking uk engineering",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "powakaddy fx7 gps",
      "powakaddy fx7 review",
      "powakaddy electric golf buggies",
    ],
  },
  "robera-pro-follow-remote-golf-buggy": {
    fullDescription: "The Robera Pro is the only buggy in our range that requires no input at all once you start walking. A smart tracking tag clips to your belt and the buggy follows your footsteps at a safe distance, so there is no remote to hold, no dial to adjust and nothing to think about between shots. When you do want direct control, dual-mode remote operation is still there. All-terrain dual motors supply the independent drive that follow-mode needs to hold a line across slopes and around obstacles rather than cutting corners. For premium buyers who have decided the point of walking is to walk unencumbered, hands-free follow technology is the feature worth the step up.",
    primaryKeyword: "follow me remote control golf trolley",
    supportingKeywords: ["follow me golf buggy australia", "follow golf buggy", "best follow me golf cart", "electric follow golf cart"],
    tags: [
      "robera pro follow remote golf buggy",
      "robera golf buggy",
      "motorised golf buggy",
      "electric golf trolley",
      "walk behind golf buggy",
      "lithium golf trolley",
      "remote control golf buggy",
      "follow me golf buggy",
      "smart follow tracking tag",
      "remote control dual-mode",
      "all-terrain dual motors",
      "premium walk-behind buyers seeking hands-free tech",
      "golf buggy australia",
      "buggy for sale yatala qld",
    ],
  },
  "mgi-zip-x1-lithium-buggy": {
    fullDescription: "The Zip X1 is where most Australians make the move from pushing to motorised, and it is deliberately uncomplicated. A single variable speed dial is the entire control interface, so there is no menu, no pairing and nothing to learn before your first round. The Click & Go lithium system drops the battery in and out without tools or cables, and the compact fold mechanism collapses the frame quickly for a standard car boot. Measure your boot before ordering and the rest takes care of itself. For first-time motorised buyers, this is the model that answers the real question, which is not what it can do but whether it will be simple enough to use every week.",
    primaryKeyword: "mgi zip x1 motorised golf buggy",
    supportingKeywords: ["mgi zip x1 review", "mgi zip x1 price", "mgi x1 electric golf trolley", "mgi zip x1"],
    tags: [
      "mgi zip x1 lithium buggy",
      "mgi golf buggy",
      "motorised golf buggy",
      "electric golf trolley",
      "walk behind golf buggy",
      "lithium golf trolley",
      "simple speed dial",
      "click & go lithium system",
      "compact fold mechanism",
      "first-time motorised buggy buyers",
      "golf buggy australia",
      "buggy for sale yatala qld",
      "mgi zip x1 review",
      "mgi zip x1 price",
    ],
  },
  "eco-battery-48v-105ah-lithium-conversion-kit": {
    fullDescription: "A complete drop-in conversion that removes roughly 140kg of lead-acid weight from an existing buggy and replaces it with a single lithium pack. That weight reduction is felt immediately in acceleration, hill climbing and range, because the motor is no longer hauling the battery bank around as dead mass. The kit is genuinely complete: CAN-bus charger, digital gauge, mounting bracket and universal harness are all included, so there is no parts-chasing partway through the job. It also ends acid spills, terminal corrosion and the fortnightly water topping that lead-acid maintenance demands. Backed by an 8-year warranty, this is the single upgrade that most transforms an ageing but otherwise sound golf buggy.",
    primaryKeyword: "golf cart electric conversion kit",
    supportingKeywords: ["electric golf cart conversion", "golf push cart electric conversion kit"],
    tags: [
      "eco battery 48v 105ah lithium conversion kit",
      "eco battery golf buggy battery",
      "lithium golf buggy battery",
      "lithium conversion kit",
      "golf buggy battery",
      "digital gauge",
      "mounting bracket",
      "universal harness",
      "golf cart owners upgrading from lead-acid to lithium",
      "golf buggy accessories australia",
      "lithium conversion kit 48v",
      "105ah lithium conversion",
      "electric golf cart conversion",
      "golf push cart electric conversion kit",
    ],
  },
  "roypow-48v-105ah-lithium-battery-pack": {
    fullDescription: "Automotive-grade LiFePO4 cells and a smart Bluetooth BMS make this the straightforward drop-in replacement for a tired 48V lead-acid bank. The Bluetooth battery management system is the part owners appreciate most day to day: state of charge, cell balance and pack health are visible on a phone instead of inferred from how the buggy feels, which turns range anxiety into a number. Integrated thermal protection guards against charging in freezing conditions, a genuine consideration for alpine and inland properties where overnight temperatures drop well below what coastal buyers expect. LiFePO4 chemistry is the safest and longest-cycling of the common lithium types. Supplied with a 5-year warranty and dispatched from our Yatala QLD depot.",
    primaryKeyword: "electric golf buggy lithium battery",
    tags: [
      "roypow 48v 105ah golf cart lithium battery pack",
      "roypow golf buggy battery",
      "lithium golf buggy battery",
      "golf buggy battery",
      "drop-in replacement",
      "built-in bms",
      "5-year warranty",
      "thermal protection",
      "club car precedent / ezgo rxv owners",
      "golf buggy accessories australia",
      "48v lithium battery pack",
      "105ah lithium battery",
      "drop in lithium battery",
    ],
  },
  "roypow-72v-105ah-commercial-lithium-battery": {
    fullDescription: "The 72V version of the RoyPow drop-in pack, specified for commercial duty rather than private golf. Higher system voltage moves the same load at lower current, so the pack and cabling run cooler and hold performance through a full working shift instead of fading toward the end of it. That is why resort fleets, security patrols and grounds teams end up here rather than on a 48V pack. Automotive-grade LiFePO4 cells and a smart BMS report state of charge and pack health rather than leaving you to infer them from how the vehicle feels, and integrated thermal protection guards against charging in freezing conditions. Supplied with a 5-year warranty and dispatched from our Yatala QLD depot.",
    tags: [
      "roypow 72v 105ah commercial lithium battery pack",
      "roypow golf buggy battery",
      "lithium golf buggy battery",
      "golf buggy battery",
      "72v 105ah",
      "drop-in replacement",
      "built-in bms",
      "5-year warranty",
      "resort fleets",
      "security patrols and grounds teams running 72v vehicles",
      "golf buggy accessories australia",
      "72v lithium battery pack",
      "commercial lithium battery",
      "105ah lithium battery",
    ],
  },
  "invicta-48v-50ah-lithium-drop-in-module": {
    fullDescription: "A compact 50Ah module designed to be linked rather than bought oversized. Parallel expansion capability means you can start with the capacity a light vehicle actually needs and add a second module later if the duty changes, instead of paying upfront for range you may never use. That modularity also helps where physical space is tight and one large pack simply will not fit the existing battery tray. Integrated Bluetooth monitoring reports state of charge and pack health to a phone. For walk-behind buggies, light utility vehicles and custom builds where a standard 105Ah pack is more battery than the application warrants, this is the sensible building block.",
    primaryKeyword: "electric buggy 48v",
    tags: [
      "invicta 48v 50ah lithium drop-in module",
      "invicta golf buggy accessory",
      "lithium golf buggy battery",
      "golf buggy battery",
      "parallel expansion capable",
      "integrated bluetooth monitoring",
      "compact or light-duty cart owners",
      "golf buggy accessories australia",
      "48v lithium battery",
      "drop in lithium module",
      "bluetooth battery monitor",
      "50ah lithium battery",
    ],
  },
  "trojan-t-875-8v-deep-cycle-lead-acid-battery": {
    fullDescription: "Genuine Trojan T-875s remain the benchmark for fleet operators who have deliberately stayed with lead-acid, and the reasoning is sound: low upfront cost per vehicle, familiar charging infrastructure and batteries that any technician can test and replace individually rather than as a sealed pack. Trojan's Alpha Plus paste formulation and T2 Technology target the plate degradation that ends most deep-cycle battery lives, delivering more usable cycles from the same footprint. The high-capacity grid design supports the deep discharge and recharge pattern that golf duty imposes daily. Clubs running larger fleets on established charging banks often find the economics still favour these. Held in stock at Yatala QLD.",
    primaryKeyword: "lead acid battery for golf trolley",
    tags: [
      "trojan t-875 8v deep cycle lead acid battery",
      "trojan golf buggy battery",
      "lead acid golf buggy battery",
      "golf buggy battery",
      "8v deep cycle",
      "t2 technology",
      "high capacity grid design",
      "fleet operators",
      "standard golf carts",
      "golf buggy accessories australia",
      "8v deep cycle battery",
      "trojan deep cycle battery",
      "golf buggy deep cycle battery",
    ],
  },
  "delta-q-quiq-48v-smart-on-board-charger": {
    fullDescription: "An IP66 sealed enclosure is the specification that matters for an on-board charger in Australia. On-board means the charger lives on the vehicle, so it endures wash-downs, rain, dust and the vibration of rough ground rather than sitting safe on a shelf, and IP66 rates it against powerful water jets and total dust ingress. The Delta-Q QuiQ also carries multiple pre-loaded charging algorithms, which lets one charger serve lead-acid, AGM and lithium packs correctly as a mixed fleet transitions rather than forcing a matched charger for each chemistry. Selecting the right profile matters: charging a battery on the wrong algorithm is the fastest way to shorten its life.",
    primaryKeyword: "on board golf cart charger",
    supportingKeywords: ["golf cart charger", "golf cart charger for sale"],
    tags: [
      "delta-q quiq 48v smart on-board charger",
      "delta-q golf buggy charger",
      "golf buggy charger",
      "golf buggy battery",
      "multi-profile charging algorithms",
      "weatherproof sealed enclosure",
      "e-z-go rxv / txt owners needing charger replacement",
      "golf buggy accessories australia",
      "on board charger",
      "48v smart charger",
      "weatherproof charger",
      "multi-profile charger",
      "golf cart charger",
      "golf cart charger for sale",
    ],
  },
  "club-car-eric-48v-high-frequency-charger": {
    fullDescription: "The genuine Club Car ERIC charger, built around high-frequency switching rather than the older transformer design. That is why it weighs a fraction of a conventional charger of the same output, which matters if it is carried between vehicles or lifted onto a bench regularly. Automatic voltage compensation adjusts for the supply it is given, so it charges correctly on a long extension lead or a rural supply that sags under load, situations where a fixed-output charger delivers an incomplete charge and slowly ruins the pack. Global AC input compatibility handles varying mains conditions. As OEM equipment it speaks to Club Car onboard systems natively. Stocked at our Yatala QLD depot.",
    primaryKeyword: "club car golf cart battery charger",
    supportingKeywords: ["club car golf buggy charger"],
    tags: [
      "club car eric 48v high-frequency charger",
      "club car golf buggy charger",
      "golf buggy charger",
      "golf buggy battery",
      "automatic voltage compensation",
      "global ac input compatibility",
      "club car precedent & tempo owners",
      "golf buggy accessories australia",
      "48v charger",
      "high frequency charger",
      "club car charger",
      "global ac input charger",
    ],
  },
  "mgi-24v-lithium-battery-36-hole": {
    fullDescription: "The genuine MGI 36-hole replacement battery for Zip Navigator and Ai Series buggies. Walk-behind batteries are consumables: after a few seasons of weekly rounds the pack no longer finishes eighteen holes with margin, and the honest fix is replacement rather than nursing it. This is the factory 24V 380Wh unit with the correct advanced BMS, which matters because the BMS is what protects the cells and communicates correctly with the buggy's electronics. The Click & Go design means fitting is tool-free. Buying the genuine pack rather than an unbranded equivalent preserves both the buggy's warranty position and its charging behaviour. Held in Australian stock at Yatala QLD.",
    primaryKeyword: "mgi golf buggy lithium battery",
    supportingKeywords: ["mgi golf buggy battery", "mgi zip navigator battery", "lithium battery for golf trolley"],
    tags: [
      "mgi 24v lithium battery 24-spindle / 36 hole",
      "mgi golf buggy battery",
      "lithium golf buggy battery",
      "golf buggy battery",
      "24v 380wh capacity",
      "advanced bms",
      "click & go design",
      "owners of mgi zip & ai series buggies",
      "golf buggy accessories australia",
      "24v lithium golf trolley battery",
      "mgi spare battery",
      "36 hole lithium battery",
      "mgi zip navigator battery",
      "lithium battery for golf trolley",
    ],
  },
  "curtis-1268-400a-programmable-motor-controller": {
    fullDescription: "The controller is the component that decides how much current reaches the motor, which makes it the real limit on a lifted or high-torque conversion. Fitting larger tyres and a lift kit increases the load on every hill, and a factory controller current-limits or overheats long before the motor does. The Curtis 1268 raises that ceiling to 400 amps peak and adds programmable acceleration and speed curves, so the buggy can be tuned for torque on steep acreage rather than left with a flat factory map. Regenerative braking control recovers energy on descents and adds engine-braking feel. A well-known industrial unit with parts and programming knowledge widely available in Australia.",
    primaryKeyword: "electric golf cart controller",
    supportingKeywords: ["electric golf cart motor controller", "electric golf cart speed controller", "golf buggy controller", "golf buggy speed controller", "48v golf cart controller"],
    tags: [
      "curtis 1268 400a programmable motor controller",
      "curtis golf buggy accessory",
      "golf buggy accessory",
      "400 amp peak output",
      "regenerative braking control",
      "programmable curves",
      "lifted cart builders",
      "performance tuners",
      "golf buggy accessories australia",
      "golf buggy motor controller",
      "programmable controller",
      "regenerative braking controller",
      "400a controller",
      "electric golf cart motor controller",
    ],
  },
  "navitas-600a-ac-controller-upgrade-kit": {
    fullDescription: "A 600-amp AC controller upgrade for owners who want a decisive change rather than a marginal one, delivering both substantially higher top speed and the hill torque that heavy lifted buggies demand. The feature that sets it apart is Bluetooth on-the-fly control: performance modes can be changed from a dashboard dial or a phone, so the same vehicle can run a restricted profile when guests, children or staff are driving and full output when you are. That lockout is a genuine safety consideration on a family property. AC drive also brings smoother power delivery and better regenerative braking than a DC system. Fitting is best handled by an experienced technician.",
    primaryKeyword: "golf cart controllers for sale",
    supportingKeywords: ["best golf cart controller", "how much is a controller for a golf cart", "golf cart controller replacement"],
    tags: [
      "navitas 600a ac controller upgrade kit",
      "navitas golf buggy accessory",
      "golf buggy accessory",
      "up to 600 amps output",
      "golfers needing speed 40+ km/h & hill climbing torque",
      "golf buggy accessories australia",
      "ac controller upgrade",
      "600 amp controller",
      "golf buggy controller upgrade",
      "bluetooth lockout controller",
      "best golf cart controller",
      "how much is a controller for a golf cart",
    ],
  },
  "universal-48v-to-12v-30a-voltage-reducer": {
    fullDescription: "Every accessory worth adding to a golf buggy runs on 12V, and the pack does not. A voltage reducer is the correct way to bridge that gap: it steps 48V down to a clean, regulated 12V supply at up to 30 amps, which is enough headroom for an LED light kit, a soundbar and USB charging together. Tapping a single battery in the bank instead, which is the shortcut people take, unbalances the pack and shortens the life of every cell in it. Key-switch triggering means it powers down with the buggy rather than draining the pack overnight. Waterproof cast aluminium housing handles under-seat heat and moisture.",
    primaryKeyword: "best golf cart dc converter",
    supportingKeywords: ["12v accessories for golf cart", "golf cart dc converter"],
    tags: [
      "universal 48v/36v to 12v 30a voltage reducer",
      "golf buggy battery",
      "key-switch triggered",
      "waterproof cast aluminum housing",
      "diy cart builders adding lights audio or horns",
      "golf buggy accessories australia",
      "48v to 12v converter",
      "golf buggy voltage reducer",
      "12v accessory power",
      "dc converter",
      "12v accessories for golf cart",
    ],
  },
  "madjax-alpha-lux-street-legal-led-light-kit": {
    fullDescription: "A complete lighting package rather than a pair of headlights, and that distinction matters if the buggy is used on private estate roads shared with vehicles. It includes automotive LED projector headlights, sequential turn signals, hazard lights, a brake switch and a mechanical horn, which together cover the signalling equipment normally expected for legitimate road use. Projector optics put light where it is needed with a defined cut-off rather than scattering glare at oncoming drivers. Note that conditional registration requirements differ by state, so confirm what your state requires before assuming a kit alone makes a buggy road legal. Supplied with mounting hardware and dispatched from Yatala QLD.",
    primaryKeyword: "golf cart lights",
    supportingKeywords: ["golf cart turn signal kit", "universal golf cart headlight kit"],
    tags: [
      "madjax alpha lux street legal led light kit",
      "madjax golf buggy accessory",
      "golf buggy accessory",
      "automotive turn signals",
      "hazard lights",
      "brake switch included",
      "gated estate drivers driving at night",
      "golf buggy accessories australia",
      "golf buggy led lights",
      "led light kit",
      "turn signal kit",
      "hazard light kit",
    ],
  },
  "heavy-duty-4-wheel-hydraulic-disc-brake-kit": {
    fullDescription: "Factory rear drum brakes are the weakest point on most golf buggies, and they become genuinely inadequate once a lift kit, larger tyres, extra seats or a loaded cargo tray increase the mass being stopped. Drums also fade when hot and hold water after wet grass, which is precisely when you need them. This kit replaces all four corners with dual-piston hydraulic calipers on stainless steel lines, giving consistent, repeatable stopping that does not deteriorate down a long descent. Stainless lines resist the corrosion that causes soft pedal feel over time. Direct bolt-on fitment means no fabrication. If you have lifted a buggy, this is the upgrade to pair with it.",
    primaryKeyword: "golf cart brake parts",
    tags: [
      "heavy duty 4-wheel hydraulic disc brake kit",
      "golf buggy accessory",
      "dual-piston calipers",
      "stainless steel lines",
      "direct bolt-on",
      "heavy utility and fast lifted cart owners",
      "golf buggy accessories australia",
      "golf buggy brake kit",
      "hydraulic disc brakes",
      "dual piston calipers",
      "bolt-on brake kit",
    ],
  },
  "all-weather-heavy-duty-pvc-enclosure": {
    fullDescription: "A four-sided enclosure turns a buggy into a usable vehicle through winter mornings, wet season downpours and dusty afternoons, which for most owners is the difference between using it year round and leaving it in the shed. The clear marine-grade vinyl windows roll up individually, so ventilation can be adjusted rather than being an all-or-nothing choice. Marine vinyl is specified because standard clear PVC yellows and cracks under Australian UV within a season or two. Heavy-duty zippers and reinforced brass eyelets are the components that usually fail first on cheap enclosures, which is exactly why they are upgraded here. Universal fit options cover most common two and four-seat models.",
    primaryKeyword: "golf buggy enclosures for sale",
    supportingKeywords: ["golf buggy enclosures"],
    tags: [
      "all-weather heavy-duty pvc enclosure",
      "golf buggy accessory",
      "roll-up clear vinyl windows",
      "heavy duty zippers",
      "universal fit options",
      "golfers playing in rain",
      "winter drivers",
      "golf buggy accessories australia",
      "golf buggy enclosure",
      "all weather enclosure",
      "roll up vinyl enclosure",
      "golf buggy rain cover",
    ],
  },
  "all-terrain-23x10-5-12-wheel-tyre-combo": {
    fullDescription: "A matched wheel and tyre package, supplied mounted with lug nuts included, so there is no separate fitting exercise. The 6-ply construction is the specification that matters on rural property: standard golf tyres are built for turf and puncture readily on stubble, stones and stick, while a 6-ply carcass resists that. Twenty-three-inch diameter adds genuine ground clearance under the axle rather than just filling the arch, and the aggressive tread clears mud instead of packing with it. Diamond-cut 12-inch alloy rims handle the side loads of off-camber driving better than pressed steel. Pair with a lift kit for the intended geometry, and check clearance before fitting to an unlifted chassis.",
    primaryKeyword: "golf cart wheels and tyres",
    supportingKeywords: ["golf cart tyres", "golf cart wheels", "golf cart wheels and rims", "golf buggy tyres wheels", "all terrain golf cart tires", "replacement golf buggy wheels"],
    tags: [
      "all-terrain 23x10.5-12 wheel & tyre combo set of 4",
      "golf buggy accessory",
      "12-inch machined alloy rims",
      "6-ply off-road tread",
      "lifted cart owners",
      "property buyers",
      "golf buggy accessories australia",
      "all terrain wheel tyre combo",
      "golf buggy wheels and tyres",
      "all terrain tyres",
      "12 inch alloy wheels",
      "23x10.5-12 tyres",
      "golf cart tyres",
      "golf cart wheels",
    ],
  },
  "foldable-tinted-acrylic-windshield-system": {
    fullDescription: "A split windshield that folds down, which is the practical arrangement for Australian conditions: up for cold mornings, insects and rain, down for airflow on hot afternoons. Fixed windshields force you to choose once and live with it. High-impact acrylic resists the stone and stick strikes that shatter glass, and the smoke tint blocks UV, which matters as much for the driver as for the dashboard and seats that would otherwise fade and crack. Snug noise-reduction clips are a small detail that prevents the buzz and rattle that makes cheaper folding windshields irritating at speed. A straightforward comfort upgrade that is fitted in minutes.",
    primaryKeyword: "golf cart windshield parts",
    tags: [
      "foldable tinted acrylic windshield system",
      "golf buggy accessory",
      "high-impact acrylic",
      "snug noise-reduction clips",
      "uv protection",
      "club car ezgo and yamaha owners",
      "golf buggy accessories australia",
      "golf buggy windshield",
      "foldable windshield",
      "tinted acrylic windshield",
      "uv protection windshield",
    ],
  },
  "heavy-duty-solenoid-albright-48vdc-200a": {
    fullDescription: "The solenoid is the high-current switch between the battery pack and the motor, and it is a common failure point on buggies that have been upgraded or worked hard. Every start draws a current spike through its contacts, and a lightweight solenoid pits and welds under that duty until it either sticks closed or stops passing current. The Albright unit uses silver alloy contacts with a continuous duty rating, meaning it is built to stay energised for extended periods without overheating, rather than for intermittent switching. If your buggy clicks but will not move, or has started intermittently cutting out, this is the part to suspect. Industrial-grade and stocked at Yatala QLD.",
    primaryKeyword: "48v golf cart solenoid",
    supportingKeywords: ["48 volt golf cart solenoid", "golf cart solenoid replacement"],
    tags: [
      "heavy duty solenoid albright 48vdc 200a",
      "albright golf buggy accessory",
      "golf buggy accessory",
      "continuous duty rating",
      "silver alloy contacts",
      "carts experiencing ignition or starting issues",
      "golf buggy accessories australia",
      "golf buggy solenoid",
      "48v solenoid",
      "200 amp solenoid",
      "albright solenoid",
    ],
  },
  "replacement-mgi-ai-zip-remote-controller": {
    fullDescription: "The official replacement handheld remote for MGI Zip Navigator and Ai Series buggies. Remotes lead a hard life clipped to a bag or a belt through every round, and a cracked case, failed button or dead internal battery does not justify replacing an otherwise healthy buggy. This is the genuine unit with pre-programmed pairing capability, so it links to your buggy without a service visit. USB-C charging means it takes the same cable as everything else rather than a proprietary lead you will lose. Using the official remote rather than a generic substitute preserves correct pairing behaviour and directional response. Held in Australian stock and dispatched from Yatala QLD.",
    primaryKeyword: "mgi remote golf buggy",
    supportingKeywords: ["mgi golf buggy remote control replacement", "mgi zip navigator replacement remote"],
    tags: [
      "replacement mgi ai & zip remote controller unit",
      "mgi golf buggy accessory",
      "golf buggy accessory",
      "pre-programmed pairing capability",
      "usb-c rechargeable",
      "mgi buggy owners who lost or damaged their remote",
      "golf buggy accessories australia",
      "golf trolley remote",
      "mgi remote control",
      "replacement remote controller",
      "usb-c rechargeable remote",
    ],
  },
  "golf-cart-side-mirrors-integrated-led-indicators": {
    fullDescription: "Convex glass gives a genuinely wide field of view, which matters more on a buggy than a car because there is no rear window, no pillar geometry to work around and passengers or cargo frequently block the view directly behind. Integrated amber LED indicators built into the mirror face put the turn signal where following drivers already look, rather than requiring separate indicator pods elsewhere on the body. That combination makes them a sensible pairing with a street-legal light kit if the buggy shares estate roads with vehicles. Straightforward to fit to standard strut positions, and supplied as a pair with mounting hardware.",
    primaryKeyword: "golf cart mirrors near me",
    tags: [
      "golf cart side mirrors with integrated led indicators",
      "golf buggy accessory",
      "convex glass for wide angle view",
      "integrated led amber indicators",
      "road-registered or estate golf buggy users",
      "golf buggy accessories australia",
      "golf buggy side mirrors",
      "led indicator mirrors",
      "convex side mirrors",
      "estate golf buggy mirrors",
    ],
  },
  "heavy-duty-rear-flip-seat-kit-2-to-4": {
    fullDescription: "The most cost-effective way to add capacity to a buggy you already own. Rather than trading a two-seater for a four-seater, this kit converts it: rear-facing seating for two more passengers that folds flat into a cargo tray when you need to carry rather than seat. That dual purpose is why it suits property owners as much as families, since the same vehicle handles the school gate and the feed run. The powder-coated steel frame resists the corrosion that would otherwise start at every weld and bolt hole in coastal or irrigated conditions. Consider pairing it with a seatbelt set and upgraded brakes, since added passengers mean added mass to stop.",
    primaryKeyword: "golf cart rear flip seat",
    supportingKeywords: ["golf cart folding rear seat", "golf cart rear seat kit", "golf cart rear seat", "golf cart rear seat replacement parts"],
    tags: [
      "heavy duty rear flip seat kit converts 2 to 4 seater",
      "golf buggy accessory",
      "folds flat into flatbed cargo tray",
      "powder-coated steel frame",
      "owners wanting to expand 2-seater capacity to 4",
      "golf buggy accessories australia",
      "rear flip seat kit",
      "2 to 4 seater conversion",
      "golf buggy rear seat",
      "flatbed rear seat",
      "golf cart folding rear seat",
      "golf cart rear seat kit",
      "golf cart rear seat",
    ],
  },
  "heavy-duty-tow-hitch-ball-assembly": {
    fullDescription: "A standard 2-inch receiver with a 50mm chrome ball, which are the common Australian sizes, so it accepts the garden trailers, box trailers and sprayers most properties already own rather than requiring anything bespoke. The receiver format also means the ball mount can be swapped for a different height or a pin-style attachment as needs change. Powder-coated steel handles the wet grass, fertiliser and mud that would rust bare steel quickly at the rear of a working vehicle. Mounting hardware is included. Remember that towing adds substantially to stopping distance, so it is worth reviewing brake condition before putting a loaded trailer behind a buggy.",
    tags: [
      "heavy duty tow hitch & ball assembly",
      "golf buggy accessory",
      "2-inch receiver",
      "powder coated steel",
      "mounting hardware included",
      "farm cart owners pulling trailers or mowers",
      "golf buggy accessories australia",
      "golf buggy tow hitch",
      "2 inch receiver hitch",
      "trailer hitch for golf buggy",
      "tow ball assembly",
    ],
  },
  "golf-cart-solar-charging-panel-expansion-kit": {
    fullDescription: "A flexible rooftop panel with an MPPT charge controller that trickle charges the pack whenever the buggy is parked in sun, extending daily range by around 20%. MPPT is the important part of that specification: it continuously finds the panel's maximum power point rather than passing raw output through, which is what allows a modest rooftop panel to contribute usefully instead of marginally. The practical benefit is greatest for vehicles that sit outdoors between short trips, which describes most resort, farm and estate duty. The flexible panel follows the roof contour and adds negligible weight or wind noise. Compatible with 36V and 48V systems.",
    primaryKeyword: "solar charging golf cart",
    supportingKeywords: ["solar golf cart", "solar powered golf buggy", "solar charge golf cart", "golf cart solar power", "solar powered golf carts for sale"],
    tags: [
      "golf cart solar charging panel expansion kit 175w",
      "golf buggy solar charging",
      "golf buggy battery",
      "flexible rooftop panel",
      "mppt charge controller 36v/48v",
      "acreage cart owners parked away from power",
      "golf buggy accessories australia",
      "solar panel for golf buggy",
      "mppt charge controller",
      "solar golf cart",
      "solar powered golf buggy",
      "solar charge golf cart",
      "golf cart solar power",
      "solar powered golf carts for sale",
    ],
  },
  "waterproof-marine-grade-bluetooth-soundbar": {
    fullDescription: "Marine-grade IP67 construction is the right specification for a golf buggy, because the vehicle lives outdoors and gets rained on, hosed down and covered in dust regardless of intent. IP67 means fully protected against dust and capable of surviving temporary immersion, which comfortably covers weather and washing. Bass radiators produce genuine low end from a compact enclosure without the ported bulk that would not survive the vibration of rough ground. Integrated RGB accent lighting is customisable, and the direct clamp mount fits roll cages and roof struts without drilling. Pair it with a voltage reducer rather than tapping a single battery, which unbalances the pack.",
    primaryKeyword: "golf cart speaker mounts",
    supportingKeywords: ["bluetooth golf cart", "golf cart with stereo"],
    tags: [
      "waterproof marine grade bluetooth soundbar 26-inch",
      "golf buggy accessory",
      "ip67 waterproof",
      "integrated rgb lights",
      "direct clamp to roll cage",
      "resort and lifestyle cart drivers",
      "golf buggy accessories australia",
      "golf buggy sound system",
      "bluetooth soundbar",
      "waterproof golf buggy speaker",
      "ip67 soundbar",
    ],
  },
  "retractable-seatbelt-system-set": {
    fullDescription: "E-Mark certification is the meaningful detail here: it means the harness has been tested and approved against a recognised international standard rather than simply resembling a seatbelt. For anyone carrying children, elderly passengers or driving on sloped or uneven ground, that distinction is worth insisting on. The three-point lap and shoulder configuration restrains the torso as well as the hips, which is what prevents the forward pitch that causes most buggy injuries. Automatic retraction keeps the belts out of the door aperture and off the ground when unused, so they stay clean and actually get worn. Heavy-duty steel mounting brackets are included, and the kit should be anchored to structural frame points.",
    primaryKeyword: "golf cart seat belts",
    supportingKeywords: ["golf cart seat belt kit", "golf cart retractable seat belts", "do golf carts have seat belts"],
    tags: [
      "retractable seatbelt system set front & rear",
      "golf buggy accessory",
      "3-point lap & shoulder harness",
      "bracket kit included",
      "e-mark certified",
      "families with kids",
      "estate road compliance",
      "golf buggy accessories australia",
      "golf buggy seat belts",
      "retractable seatbelts",
      "golf cart seat belt kit",
      "golf cart retractable seat belts",
    ],
  },
  "lockable-dash-glove-box-storage-system": {
    fullDescription: "Dual lockable compartments with a carbon-fibre textured finish, custom moulded to fit popular models rather than fixed on as a universal box. The value is straightforward: a golf buggy has no doors and no boot, so a phone, wallet or keys left on the seat are visible and available to anyone walking past while you play a hole or step into the clubhouse. A lockable compartment turns that from a risk into a non-issue. Two keys are supplied, which is worth noting since single-key accessories become a problem the moment the key is lost. It also stops loose items sliding off the dash through turns.",
    tags: [
      "lockable dash glove box storage system",
      "golf buggy accessory",
      "carbon fiber finish",
      "dual keys",
      "golfers leaving valuables at the club or resort",
      "golf buggy accessories australia",
      "golf buggy glove box",
      "lockable dash storage",
      "dual key glove box",
      "dash storage box",
    ],
  },
  "heavy-duty-sand-bottle-assembly-dual-set": {
    fullDescription: "A dual set of divot bottles with curved easy-pour necks and rattle-free bracket mounts. Repairing divots is basic course etiquette and most clubs expect it, but factory bottle mounts are notorious for rattling loose over a round until they are removed and left in the shed. The rattle-free bracket design is the entire point of upgrading: mounts that stay quiet and stay put get used, while ones that buzz constantly do not. The curved neck pours accurately into the divot rather than scattering sand across the surrounding turf, which is what makes the repair actually take. Supplied as a pair with side-frame mounting hardware.",
    primaryKeyword: "golf sand bottle",
    supportingKeywords: ["what is a sand bottle used for in golf"],
    tags: [
      "heavy duty sand bottle assembly dual set",
      "golf buggy accessory",
      "rattle-free bracket mounts",
      "easy-pour curved neck design",
      "private golf cart owners",
      "course operators",
      "golf buggy accessories australia",
      "golf buggy sand bottle",
      "dual sand bottle set",
      "divot sand bottle",
      "sand bottle holder",
    ],
  },
};

export function getProductDetails(slug: string): ProductDetails {
  const d = PRODUCT_DETAILS[slug];
  if (!d) throw new Error(`No product details for slug "${slug}"`);
  if (d.faqs) return d;
  const product = PRODUCTS.find((p) => p.slug === slug);
  if (!product) throw new Error(`No product for slug "${slug}"`);
  return { ...d, faqs: buildFaqs(product) };
}

export function withDetails(product: ProductItem): ProductFull {
  return { ...product, ...getProductDetails(product.slug) };
}

/** The full catalogue for server-side consumers (APIs, MCP, schema). */
export const PRODUCTS_FULL: ProductFull[] = PRODUCTS.map(withDetails);
