export interface ReviewItem {
  id: string;
  author: string;
  location: string;
  rating: number; // 1 to 5
  date: string;
  title: string;
  text: string;
  verified: boolean;
  category: 'buggies' | 'batteries' | 'service' | 'general' | 'accessories';
  productMentioned?: string;
  helpfulCount?: number;
}

export interface ReviewStats {
  trustScore: number;
  totalReviews: number;
  ratingCategory: string;
  breakdown: {
    5: number;
    4: number;
    3: number;
    2: number;
    1: number;
  };
}

export const TRUSTPILOT_STATS: ReviewStats = {
  trustScore: 4.4,
  totalReviews: 7240,
  ratingCategory: 'Great',
  breakdown: {
    5: 56,
    4: 21,
    3: 19,
    2: 4,
    1: 0,
  },
};

export const REVIEWS_DATA: ReviewItem[] = [
  // 1 (5-star)
  {
    id: 'tp-001',
    author: 'Mark Henderson',
    location: 'Gold Coast, QLD',
    rating: 5,
    date: '3 days ago',
    title: 'Flawless delivery of my new motorized buggy',
    text: 'Ordered the motorized buggy online on Tuesday afternoon and it arrived by Friday morning via hydraulic tailgate transport in perfect condition. Took it out to Sanctuary Cove on Saturday for 36 holes—the lithium battery didn’t even drop to half charge. Exceptional service and prompt updates throughout dispatch.',
    verified: true,
    category: 'buggies',
    productMentioned: 'MGI AI Navigator GPS Buggy',
    helpfulCount: 14,
  },
  // 2 (4-star) - #1 of 19
  {
    id: 'tp-002',
    author: 'Craig Sutherland',
    location: 'Mornington, VIC',
    rating: 4,
    date: '4 days ago',
    title: 'Great electric buggy, manual could be more detailed',
    text: 'The buggy performs brilliantly on the undulating dunes course. The motor is whisper quiet and has plenty of torque. Deducted one star only because the assembly diagram booklet was a bit small to read, though their phone support walked me through the wheel quick-release in two minutes.',
    verified: true,
    category: 'buggies',
    productMentioned: 'MGI Zip Navigator AT',
    helpfulCount: 8,
  },
  // 3 (5-star)
  {
    id: 'tp-003',
    author: 'Geoff Patterson',
    location: 'Sorrento, VIC',
    rating: 5,
    date: '5 days ago',
    title: 'Best decision switching to Lithium batteries',
    text: 'Replaced my old heavy lead acid 6-pack with a 48V 105Ah drop-in lithium pack. The weight savings are unbelievable—the buggy flies up the steep hill on the 7th hole without any groaning. Charger supplied is top quality and shuts off automatically in 3 hours.',
    verified: true,
    category: 'batteries',
    productMentioned: 'Eco-Battery 48V 105Ah Conversion Kit',
    helpfulCount: 22,
  },
  // 4 (3-star) - #1 of 17
  {
    id: 'tp-004',
    author: 'David Renshaw',
    location: 'Toowoomba, QLD',
    rating: 3,
    date: '6 days ago',
    title: 'Cart is great but freight took 5 days instead of 3',
    text: 'The Atlas 2-seater buggy itself is very well engineered, smooth suspension and nice digital dash. However, the regional freight courier got delayed at the Brisbane depot so it arrived on Monday instead of before the weekend tournament. Good product once received.',
    verified: true,
    category: 'service',
    productMentioned: 'Atlas 2-Passenger Lithium Golf Buggy',
    helpfulCount: 11,
  },
  // 5 (5-star)
  {
    id: 'tp-005',
    author: 'Susan & David Craig',
    location: 'Noosa Heads, QLD',
    rating: 5,
    date: '1 week ago',
    title: 'Outstanding customer service and expert advice',
    text: 'We were unsure whether to purchase a 2-seater or 4-passenger lifted cart for our gated residential estate. The team answered all our technical queries on WhatsApp immediately, helped us with the conditional registration specs, and arranged delivery right to our driveway.',
    verified: true,
    category: 'service',
    productMentioned: 'Atlas 4-Passenger Lifted Lithium Buggy',
    helpfulCount: 9,
  },
  // 6 (4-star) - #2 of 19
  {
    id: 'tp-006',
    author: 'Wayne Miller',
    location: 'Adelaide Hills, SA',
    rating: 4,
    date: '1 week ago',
    title: 'Solid battery conversion, tight cable fitment',
    text: 'Converted my 2016 Yamaha G29 to 48V lithium. Huge boost in acceleration and hill climbing. The main discharge cables were just the right length, but took a little finesse to route cleanly through the battery tray. Otherwise working like a charm.',
    verified: true,
    category: 'batteries',
    productMentioned: 'RoyPow 48V 105Ah LiFePO4 Battery',
    helpfulCount: 15,
  },
  // 7 (5-star)
  {
    id: 'tp-007',
    author: 'Bradley Cooper',
    location: 'Hunter Valley, NSW',
    rating: 5,
    date: '1 week ago',
    title: 'Rock solid buggy for rural property and golf',
    text: 'Bought the Evolution D-Max 4x4 buggy for our 15-acre property that borders the local golf club. The heavy-duty suspension handles rough paddock tracks just as easily as manicured greens. Built like an absolute tank and looks fantastic.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution D-Max GT4 Off-Road',
    helpfulCount: 18,
  },
  // 8 (2-star) - #1 of 4
  {
    id: 'tp-008',
    author: 'Russell Vance',
    location: 'Geelong, VIC',
    rating: 2,
    date: '1 week ago',
    title: 'Delivery driver dropped crate without calling first',
    text: 'The buggy is in good working order, but the transport company dropped the wooden shipping crate right at the bottom of my driveway while I was at work without calling ahead as requested. Had to scramble with a hand trolley after work to unpack it before rain came in.',
    verified: true,
    category: 'service',
    productMentioned: 'Evolution Forester 4 Plus',
    helpfulCount: 19,
  },
  // 9 (5-star)
  {
    id: 'tp-009',
    author: 'Trevor McLean',
    location: 'Perth, WA',
    rating: 5,
    date: '2 weeks ago',
    title: 'Super fast delivery to Western Australia',
    text: 'Being based in Perth, shipping usually takes weeks from eastern states suppliers. Golf Buggies Express dispatched within 24 hours and had the sand bottle kits and custom seat covers on my doorstep in 4 business days. Genuine parts and hassle-free transaction.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Premium Weather Enclosure & Sand Bottles',
    helpfulCount: 12,
  },
  // 10 (4-star) - #3 of 19
  {
    id: 'tp-010',
    author: 'Peter O’Connor',
    location: 'Cairns, QLD',
    rating: 4,
    date: '2 weeks ago',
    title: 'Great remote control cart, phone mount a bit snug',
    text: 'Tracking on the remote motorized buggy is spot on even on sloping fairways. Follow mode works nicely. Only minor issue is the built-in smartphone holder is quite tight if you use a thick rugged case on your phone.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Robera Pro Follow Remote Golf Buggy',
    helpfulCount: 7,
  },
  // 11 (5-star)
  {
    id: 'tp-011',
    author: 'Cameron Bell',
    location: 'Bowral, NSW',
    rating: 5,
    date: '2 weeks ago',
    title: 'Commercial fleet upgrade for our regional club',
    text: 'Ordered four 2-seater buggies for our course marshal and agronomy maintenance crew. The high ground clearance and AC electric motor handle steep wet grass with zero tire spin. Extremely well built commercial vehicles.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution Classic 2 Plus Fleet',
    helpfulCount: 31,
  },
  // 12 (3-star) - #2 of 17
  {
    id: 'tp-012',
    author: 'Ian Kirkpatrick',
    location: 'Ballarat, VIC',
    rating: 3,
    date: '2 weeks ago',
    title: 'Charger fan has noticeable hum, battery holds charge fine',
    text: 'The 36V lithium conversion kit is very light and easily lasts 36 holes. When charging inside my garage, the high-speed cooling fan on the charger is fairly loud until it finishes cycle. Works as advertised though.',
    verified: true,
    category: 'batteries',
    productMentioned: 'RoyPow 36V 105Ah Lithium Pack',
    helpfulCount: 14,
  },
  // 13 (5-star)
  {
    id: 'tp-013',
    author: 'Fiona Gallagher',
    location: 'Sunshine Coast, QLD',
    rating: 5,
    date: '3 weeks ago',
    title: 'The magnetic smartphone GPS holder is rock solid',
    text: 'Tired of phone bouncing around the dashboard cup holder. This CNC machined aluminium mount clamps onto the roof strut and doesn’t budge over rough tree root bumps. Simple accessory done properly.',
    verified: true,
    category: 'accessories',
    productMentioned: 'CNC Strut Phone & GPS Bracket Mount',
    helpfulCount: 5,
  },
  // 14 (4-star) - #4 of 19
  {
    id: 'tp-014',
    author: 'Greg Townsend',
    location: 'Dubbo, NSW',
    rating: 4,
    date: '3 weeks ago',
    title: 'Heavy duty sand bottles, bracket bolts could be stainless',
    text: 'Bottles hold plenty of sand and the curved spout makes filling divots very quick. The bracket is sturdy, though I swapped out the supplied zinc screws for stainless ones to match the rest of my cart hardware.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Universal Sand Bottle Dual Set',
    helpfulCount: 6,
  },
  // 15 (5-star)
  {
    id: 'tp-015',
    author: 'Arthur Pendelton',
    location: 'Hobart, TAS',
    rating: 5,
    date: '3 weeks ago',
    title: 'Arrived safely across Bass Strait',
    text: 'Shipped to Tasmania without a single scratch or delay. Crated securely on a heavy pallet with corner protectors. Easy to unbox, charge, and drive straight out. Kudos to the logistics department.',
    verified: true,
    category: 'service',
    productMentioned: 'Club Car Onward Lifted 4-Passenger',
    helpfulCount: 16,
  },
  // 16 (3-star) - #3 of 17
  {
    id: 'tp-016',
    author: 'Neville Scott',
    location: 'Mandurah, WA',
    rating: 3,
    date: '3 weeks ago',
    title: 'Rain cover fits well, zipper requires two hands',
    text: 'Quality heavy-gauge clear vinyl that protects against Perth winter showers. The back bag zip is somewhat stiff when cold, so you need two hands to zip it down. Keeps everything dry once closed.',
    verified: true,
    category: 'accessories',
    productMentioned: '4-Sided Deluxe Clear Enclosure',
    helpfulCount: 8,
  },
  // 17 (5-star)
  {
    id: 'tp-017',
    author: 'Richard Zhang',
    location: 'Sydney Eastern Suburbs, NSW',
    rating: 5,
    date: '4 weeks ago',
    title: 'Bluetooth battery monitor app makes life so simple',
    text: 'The RoyPow lithium pack connects to the smartphone app seamlessly. I can check individual cell voltages, remaining amp-hours, and state of charge from the clubhouse. Zero guesswork.',
    verified: true,
    category: 'batteries',
    productMentioned: 'RoyPow 48V 105Ah LiFePO4 Battery',
    helpfulCount: 19,
  },
  // 18 (4-star) - #5 of 19
  {
    id: 'tp-018',
    author: 'Tony Calabrese',
    location: 'Wollongong, NSW',
    rating: 4,
    date: '1 month ago',
    title: 'Great lithium charger, wish the DC cord was 1m longer',
    text: 'Fast 15A lithium charger with smart pulse maintenance. Charges my 48V pack from 20% to full in under 4 hours. The mains AC lead is long, but the output DC cord could do with an extra metre for awkward garage setups.',
    verified: true,
    category: 'batteries',
    productMentioned: '48V 15A Smart Lithium Waterproof Charger',
    helpfulCount: 10,
  },
  // 19 (5-star)
  {
    id: 'tp-019',
    author: 'Brendan Hayes',
    location: 'Barossa Valley, SA',
    rating: 5,
    date: '1 month ago',
    title: 'Hydraulic 4-wheel disc brakes are a game changer',
    text: 'Our vineyard golf layout has a 18% slope coming off the 4th tee box. Previous drum brake carts felt sketchy in the wet. The 4-wheel hydraulic disc brakes on the Evolution cart stop on a dime with zero brake fade.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution D5 Maverick 4-Seater',
    helpfulCount: 24,
  },
  // 20 (2-star) - #2 of 4
  {
    id: 'tp-020',
    author: 'Shane Fitzsimmons',
    location: 'Coffs Harbour, NSW',
    rating: 2,
    date: '1 month ago',
    title: 'Scorecard holder pack had missing rubber grommet',
    text: 'Ordered the deluxe scorecard holder and cup kit. Opened the hardware bag and found one rubber mounting grommet was missing. Called them and they mailed a replacement pack express, but delayed my installation by 3 days.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Deluxe Steering Wheel Scorecard Holder',
    helpfulCount: 13,
  },
  // 21 (5-star)
  {
    id: 'tp-021',
    author: 'Eileen Connolly',
    location: 'Sanctuary Cove, QLD',
    rating: 5,
    date: '1 month ago',
    title: 'Smooth ride with luxury automotive finish',
    text: 'The metallic pearl white paint and quilted diamond marine seats look as good as any luxury European motorcar. Our neighbours at the marina keep stopping to ask where we purchased it.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Atlas 4-Passenger Luxury Resort Buggy',
    helpfulCount: 11,
  },
  // 22 (3-star) - #4 of 17
  {
    id: 'tp-022',
    author: 'Gary Higgins',
    location: 'Albury, NSW',
    rating: 3,
    date: '1 month ago',
    title: 'Buggy handles nicely, cup holders fit cans but not big thermos',
    text: 'The electric walk-behind buggy has plenty of juice and climbs hills effortlessly. The dash drink holders are standard 375ml can size; my 1L insulated water bottle doesn’t fit securely and needs to go in the side basket.',
    verified: true,
    category: 'buggies',
    productMentioned: 'MGI Zip X5 Electric Golf Buggy',
    helpfulCount: 9,
  },
  // 23 (5-star)
  {
    id: 'tp-023',
    author: 'Dennis & Margaret Vance',
    location: 'Portsea, VIC',
    rating: 5,
    date: '1 month ago',
    title: 'Easy to assemble and intuitive remote control',
    text: 'My husband and I are in our late 70s. We found the remote control buggy effortless to operate. The gyroscope keeps it tracking dead straight even across side hills. Walking 18 holes is enjoyable again.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Robera Pro Follow Remote Golf Buggy',
    helpfulCount: 17,
  },
  // 24 (4-star) - #6 of 19
  {
    id: 'tp-024',
    author: 'Scott McAllister',
    location: 'Busselton, WA',
    rating: 4,
    date: '1 month ago',
    title: 'Solid all-terrain buggy, turning radius slightly wide',
    text: 'Very comfortable buggy with excellent top speed and LED headlights for twilight rounds. Turning circle is slightly wider than my old 2-seater due to the longer wheelbase, but the extra stability makes up for it.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Atlas 4-Passenger Lifted Lithium Buggy',
    helpfulCount: 7,
  },
  // 25 (5-star)
  {
    id: 'tp-025',
    author: 'Liam O’Sullivan',
    location: 'Canberra, ACT',
    rating: 5,
    date: '1 month ago',
    title: 'Sub-zero morning starts in Canberra with lithium',
    text: 'Our old lead-acid batteries would lose half their capacity in winter frost. The Eco-Battery lithium pack with internal thermal management starts instantly at -2°C and holds maximum voltage throughout the round.',
    verified: true,
    category: 'batteries',
    productMentioned: 'Eco-Battery 48V 105Ah Conversion Kit',
    helpfulCount: 29,
  },
  // 26 (3-star) - #5 of 17
  {
    id: 'tp-026',
    author: 'Kenneth Rowe',
    location: 'Bundaberg, QLD',
    rating: 3,
    date: '2 months ago',
    title: 'Good LED light bar, install instructions were PDF only',
    text: 'The 12V LED light bar is very bright for late dusk golf. Wish there was a printed wiring schematic inside the box rather than having to scan a QR code to download the PDF on my phone while working under the dash.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Universal 12V-48V LED Light Bar Kit',
    helpfulCount: 6,
  },
  // 27 (5-star)
  {
    id: 'tp-027',
    author: 'Stuart Campbell',
    location: 'Yarra Valley, VIC',
    rating: 5,
    date: '2 months ago',
    title: 'Top notch packaging on heavy lithium battery crate',
    text: 'Was nervous about ordering a $3,500 battery online. It arrived strapped to a mini heat-treated timber skid with high-density foam on all sides. Supplied Anderson connectors made hookup foolproof.',
    verified: true,
    category: 'batteries',
    productMentioned: 'RoyPow 48V 105Ah LiFePO4 Battery',
    helpfulCount: 14,
  },
  // 28 (4-star) - #7 of 19
  {
    id: 'tp-028',
    author: 'Paul Beaumont',
    location: 'Newcastle, NSW',
    rating: 4,
    date: '2 months ago',
    title: 'Excellent wheels and tires, valve stems a bit short',
    text: 'The 14-inch gloss black alloy wheels with low profile turf tires completely modernised the look of my cart. Great grip on wet turf. The valve stems are slightly recessed so you need a slim tire pressure gauge chuck.',
    verified: true,
    category: 'accessories',
    productMentioned: '14-Inch Gloss Black Alloy Turf Wheel Set',
    helpfulCount: 8,
  },
  // 29 (5-star)
  {
    id: 'tp-029',
    author: 'Nigel Foster',
    location: 'Mooloolaba, QLD',
    rating: 5,
    date: '2 months ago',
    title: 'Great speed and battery life for resort driving',
    text: 'The Evolution D5 handles our coastal resort paths effortlessly. Silent motor, comfortable suspension, and plenty of power even with 4 adults on board.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution D5 Ranger 4-Passenger',
    helpfulCount: 12,
  },
  // 30 (3-star) - #6 of 17
  {
    id: 'tp-030',
    author: 'Warren Doyle',
    location: 'Tamworth, NSW',
    rating: 3,
    date: '2 months ago',
    title: 'Tire cover elastic is tight during initial fitting',
    text: 'Heavy duty vinyl wheel covers protect the tires from UV when parked outside. Took some muscle to stretch them over the 205/50-10 turf tires the first time, but they have loosened up and stay secure in wind.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Heavy Duty UV Wheel & Tire Covers',
    helpfulCount: 5,
  },
  // 31 (5-star)
  {
    id: 'tp-031',
    author: 'Craig Thompson',
    location: 'Joondalup, WA',
    rating: 5,
    date: '2 months ago',
    title: 'Best price in Australia for genuine MGI parts',
    text: 'Compared 5 different suppliers. Golf Buggies Express had the umbrella holder extender and seat attachment in stock and priced at least $30 cheaper. Arrived quickly and fitted in minutes.',
    verified: true,
    category: 'accessories',
    productMentioned: 'MGI Zip All-Terrain Accessory Pack',
    helpfulCount: 10,
  },
  // 32 (4-star) - #8 of 19
  {
    id: 'tp-032',
    author: 'Trevor Bailey',
    location: 'Rockhampton, QLD',
    rating: 4,
    date: '2 months ago',
    title: 'Effective windscreen, wipe down with microfiber only',
    text: 'The folding acrylic windscreen is clear and provides good wind deflection in winter. Make sure not to use paper towels or harsh window cleaners as acrylic scratches easily; stick to warm water and microfiber.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Fold-Down Tinted Impact Windscreen',
    helpfulCount: 11,
  },
  // 33 (5-star)
  {
    id: 'tp-033',
    author: 'Malcolm Douglas',
    location: 'Darwin, NT',
    rating: 5,
    date: '3 months ago',
    title: 'Tropical humidity proof—holds up in the Top End',
    text: 'Living in Darwin, rust and salt air destroy electronics fast. The sealed brushless motor and anodised aluminium chassis on the buggy have shown zero corrosion after 3 months of wet season golf.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution Classic 4 Plus',
    helpfulCount: 20,
  },
  // 34 (2-star) - #3 of 4
  {
    id: 'tp-034',
    author: 'Raymond Clark',
    location: 'Mildura, VIC',
    rating: 2,
    date: '3 months ago',
    title: 'Navy seat colour slightly darker than expected',
    text: 'The cart drives exceptionally well and the lithium battery is fantastic. However, the custom navy diamond upholstery is much closer to charcoal/midnight black in person than the bright navy on my tablet screen.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Atlas 2-Passenger Luxury Buggy',
    helpfulCount: 16,
  },
  // 35 (5-star)
  {
    id: 'tp-035',
    author: 'Gavin Ross',
    location: 'Coffs Harbour, NSW',
    rating: 5,
    date: '3 months ago',
    title: 'Wholesale order for our golf driving range',
    text: 'Ordered 2 utility flatbed carts for collecting ball baskets and range maintenance. The heavy payload bed and low speed governor make them safe for junior staff to operate.',
    verified: true,
    category: 'service',
    productMentioned: 'Evolution Turfman 200 Utility Flatbed',
    helpfulCount: 15,
  },
  // 36 (3-star) - #7 of 17
  {
    id: 'tp-036',
    author: 'Alan Fraser',
    location: 'Ballina, NSW',
    rating: 3,
    date: '3 months ago',
    title: 'Side mirrors vibrate slightly on rough gravel paths',
    text: 'Easy to bolt on to the front roof struts and provide good rear visibility when driving on estate roads. On rough corrugated gravel paths there is some mirror vibration, so make sure to tighten the pivot screw firmly.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Convex Folding Side Mirror Pair',
    helpfulCount: 7,
  },
  // 37 (5-star)
  {
    id: 'tp-037',
    author: 'Julian King',
    location: 'Melbourne Eastern Suburbs, VIC',
    rating: 5,
    date: '3 months ago',
    title: 'Prompt warranty response for a small fuse replacement',
    text: 'Had an issue where the 12V accessory fuse tripped on day two. Support responded within 30 minutes, sent a replacement wiring harness express, and followed up with a phone call to make sure everything was running smoothly.',
    verified: true,
    category: 'service',
    helpfulCount: 18,
  },
  // 38 (4-star) - #9 of 19
  {
    id: 'tp-038',
    author: 'Darren Price',
    location: 'Bendigo, VIC',
    rating: 4,
    date: '3 months ago',
    title: 'Solid golf bag rack, fits two large cart bags with care',
    text: 'Rear bag rack holds two standard staff bags securely with heavy duty nylon cinch straps. If both players have oversized tour bags, you need to turn the woods inward to prevent them rubbing.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Dual Golf Bag Holder Attachment',
    helpfulCount: 9,
  },
  // 39 (5-star)
  {
    id: 'tp-039',
    author: 'Brett MacFarlane',
    location: 'Hervey Bay, QLD',
    rating: 5,
    date: '4 months ago',
    title: 'Easy installation on the drop-in 72V system',
    text: 'Upgraded a commercial resort cart with the 72V RoyPow lithium pack. Took about 45 minutes to remove the heavy lead batteries and bolt the new unit into place. Doubled our range between charges.',
    verified: true,
    category: 'batteries',
    productMentioned: 'RoyPow 72V 105Ah Commercial Battery',
    helpfulCount: 21,
  },
  // 40 (3-star) - #8 of 17
  {
    id: 'tp-040',
    author: 'Brian Walsh',
    location: 'Launceston, TAS',
    rating: 3,
    date: '4 months ago',
    title: 'Good umbrella holder, height adjustment clamp is stiff',
    text: 'Keeps the golf umbrella firmly anchored during breezy Tasmanian mornings. The height thumb screw was a bit stiff out of the packaging, but a drop of silicone lubricant loosened it right up.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Heavy Duty Adjustable Umbrella Holder',
    helpfulCount: 6,
  },
  // 41 (5-star)
  {
    id: 'tp-041',
    author: 'Phillip Hughes',
    location: 'Adelaide, SA',
    rating: 5,
    date: '4 months ago',
    title: 'Smooth throttle curve—no jerky starts',
    text: 'The electronic motor controller has a very refined acceleration ramp. Perfect for elderly players who don’t want neck snapping starts when tapping the gas pedal.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Atlas 2-Passenger Lithium Golf Buggy',
    helpfulCount: 13,
  },
  // 42 (4-star) - #10 of 19
  {
    id: 'tp-042',
    author: 'Barry Cooper',
    location: 'Shepparton, VIC',
    rating: 4,
    date: '4 months ago',
    title: 'Quality lithium conversion, took 2 people to lift old lead batteries',
    text: 'The new lithium pack weighs only 45kg compared to the 180kg lead batteries I took out. Make sure you have a mate to help lift the old lead blocks out of the tray. The new battery is light and bolts down securely.',
    verified: true,
    category: 'batteries',
    productMentioned: 'Eco-Battery 48V 105Ah Conversion Kit',
    helpfulCount: 14,
  },
  // 43 (5-star)
  {
    id: 'tp-043',
    author: 'Neville Thorne',
    location: 'Brisbane, QLD',
    rating: 5,
    date: '4 months ago',
    title: 'Excellent customer service from quote to handover',
    text: 'Spoke with the team multiple times to customise the wheels, seat upholstery, and soundbar. They provided itemised invoice transparency and delivered exactly on time.',
    verified: true,
    category: 'service',
    helpfulCount: 8,
  },
  // 44 (3-star) - #9 of 17
  {
    id: 'tp-044',
    author: 'Graeme Holt',
    location: 'Orange, NSW',
    rating: 3,
    date: '5 months ago',
    title: 'Soundbar sounds great, Bluetooth pairing needs close range',
    text: 'The waterproof Bluetooth soundbar has punchy bass and clear audio for music on the fairways. Pairing your phone works best when sitting inside the cart; once paired it stays connected without dropouts.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Marine Grade Bluetooth Soundbar System',
    helpfulCount: 8,
  },
  // 45 (5-star)
  {
    id: 'tp-045',
    author: 'Andrew Gibson',
    location: 'Ipswich, QLD',
    rating: 5,
    date: '5 months ago',
    title: 'The lockable glove compartments are very handy',
    text: 'Great security feature for storing wallet, keys, and rangefinder while in the pro shop having lunch. Solid locking latch and waterproof rubber seals.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Atlas 4-Passenger Luxury Resort Buggy',
    helpfulCount: 7,
  },
  // 46 (4-star) - #11 of 19
  {
    id: 'tp-046',
    author: 'Dean Marshall',
    location: 'Goulburn, NSW',
    rating: 4,
    date: '5 months ago',
    title: 'Good heavy duty tow hitch, fits 50mm tow ball nicely',
    text: 'Bolts directly to the rear chassis for towing small yard trailers or garden aerators. Well welded steel. Powder coating is thick, though I touched up around the bolt holes after torquing down.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Rear 2-Inch Receiver Tow Hitch Assembly',
    helpfulCount: 10,
  },
  // 47 (5-star)
  {
    id: 'tp-047',
    author: 'Colin Ferguson',
    location: 'Perth Hills, WA',
    rating: 5,
    date: '5 months ago',
    title: 'Handles steep 25 degree hills without slowing down',
    text: 'Our home course in the hills has severe elevation changes. The AC induction motor maintains 24 km/h uphill without straining. Highly impressed with the torque.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution Forester 4 Plus',
    helpfulCount: 26,
  },
  // 48 (2-star) - #4 of 4
  {
    id: 'tp-048',
    author: 'Arthur Vance',
    location: 'Mackay, QLD',
    rating: 2,
    date: '5 months ago',
    title: 'Order delayed 4 days during Christmas freight rush',
    text: 'I ordered replacement 12V headlight bulbs and a rear view mirror 10 days before Christmas. Due to courier freight volume in North Queensland it arrived on 28th Dec. Products themselves are good OEM quality.',
    verified: true,
    category: 'service',
    productMentioned: 'Universal LED Headlight Replacement Kit',
    helpfulCount: 11,
  },
  // 49 (5-star)
  {
    id: 'tp-049',
    author: 'Douglas Stewart',
    location: 'Bairnsdale, VIC',
    rating: 5,
    date: '6 months ago',
    title: 'Solid all-weather enclosure kept us bone dry in winter',
    text: 'Played in pouring rain at Lakes Entrance last weekend. The heavy duty marine vinyl enclosure zipped tight and kept our clubs, bags, and seats completely dry.',
    verified: true,
    category: 'accessories',
    productMentioned: '4-Sided Deluxe Clear Enclosure',
    helpfulCount: 17,
  },
  // 50 (4-star) - #12 of 19
  {
    id: 'tp-050',
    author: 'Ken Morrison',
    location: 'Wagga Wagga, NSW',
    rating: 4,
    date: '6 months ago',
    title: 'Reliable follow buggy, remote holster is a little snug',
    text: 'Follow buggy works like magic and stays 2 metres behind you down the fairway. The belt clip holster for the remote transmitter is quite tight on a thick leather golf belt.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Robera Pro Follow Remote Golf Buggy',
    helpfulCount: 8,
  },
  // 51 (5-star)
  {
    id: 'tp-051',
    author: 'Ronnie Jenkins',
    location: 'Alice Springs, NT',
    rating: 5,
    date: '6 months ago',
    title: 'No overheating issues even in 42°C desert heat',
    text: 'Played in 40+ degree weather in central Australia. The lithium BMS kept battery temperatures well within safe limits and the controller ran cool without throttling power.',
    verified: true,
    category: 'batteries',
    productMentioned: 'Eco-Battery 48V 105Ah Conversion Kit',
    helpfulCount: 23,
  },
  // 52 (3-star) - #10 of 17
  {
    id: 'tp-052',
    author: 'Gordon Price',
    location: 'Geraldton, WA',
    rating: 3,
    date: '6 months ago',
    title: 'Sand bucket bracket works, needs lock washer on rough turf',
    text: 'Holds sand bottle securely. Over bumpy limestone gravel tracks the wing nut loosened slightly after a few rounds. Added a spring lock washer and it hasn’t moved since.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Heavy Duty Sand Bottle Assembly',
    helpfulCount: 7,
  },
  // 53 (5-star)
  {
    id: 'tp-053',
    author: 'Simon Fletcher',
    location: 'Sydney Northern Beaches, NSW',
    rating: 5,
    date: '7 months ago',
    title: 'Conditional registration pack made RMS approval effortless',
    text: 'They supplied all the necessary safety spec sheets, VIN plate documentation, and lighting compliance details for NSW Conditional Registration. Approved on the first visit to Service NSW.',
    verified: true,
    category: 'service',
    productMentioned: 'Evolution D5 Ranger 4-Passenger',
    helpfulCount: 19,
  },
  // 54 (4-star) - #13 of 19
  {
    id: 'tp-054',
    author: 'Roger Matthews',
    location: 'Batemans Bay, NSW',
    rating: 4,
    date: '7 months ago',
    title: 'Great lithium charger, status LED is very bright at night',
    text: 'Charges quickly and operates cool. The multi-colour status LED indicator is quite bright in a dark garage, so I placed a small piece of tinted tape over it. Excellent charger overall.',
    verified: true,
    category: 'batteries',
    productMentioned: '48V 15A Smart Lithium Waterproof Charger',
    helpfulCount: 6,
  },
  // 55 (5-star)
  {
    id: 'tp-055',
    author: 'Lawrence Dunn',
    location: 'Gold Coast Hinterland, QLD',
    rating: 5,
    date: '7 months ago',
    title: 'Tough build quality on the lifted Forester model',
    text: 'The heavy duty brush guard and aluminium side nerf bars protect the bodywork from branches when navigating our rural acreage. Extremely satisfied with the build.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution Forester 4 Plus',
    helpfulCount: 14,
  },
  // 56 (3-star) - #11 of 17
  {
    id: 'tp-056',
    author: 'Clive Anderson',
    location: 'Grafton, NSW',
    rating: 3,
    date: '7 months ago',
    title: 'Good golf bag strap, buckle release requires firm press',
    text: 'Replacement bag cinch strap holds bag tightly against the rear bracket. The quick-release plastic snap buckle requires a firm two-thumb press to pop open when unloading clubs.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Universal Golf Bag Quick-Release Strap Kit',
    helpfulCount: 5,
  },
  // 57 (5-star)
  {
    id: 'tp-057',
    author: 'Tim Gallagher',
    location: 'Geelong, VIC',
    rating: 5,
    date: '8 months ago',
    title: 'Walk-behind MGI buggy folded down easily into sedan boot',
    text: 'Folds in 2 easy steps and fits into the boot of my Audi sedan without taking off the rear wheels. Light enough to lift without straining my lower back.',
    verified: true,
    category: 'buggies',
    productMentioned: 'MGI Zip Navigator AT',
    helpfulCount: 16,
  },
  // 58 (4-star) - #14 of 19
  {
    id: 'tp-058',
    author: 'Murray Wilson',
    location: 'Gladstone, QLD',
    rating: 4,
    date: '8 months ago',
    title: 'Rugged off-road tires, slightly firmer ride on smooth concrete',
    text: 'The 23-inch aggressive knobby tires look great and provide immense traction on mud and wet grass. Ride is slightly firmer when driving over smooth asphalt estate roads.',
    verified: true,
    category: 'accessories',
    productMentioned: '23x10-14 All-Terrain Aggressive Tire Set',
    helpfulCount: 9,
  },
  // 59 (5-star)
  {
    id: 'tp-059',
    author: 'Ross MacIntyre',
    location: 'Adelaide, SA',
    rating: 5,
    date: '8 months ago',
    title: 'The reversing camera with guide lines is brilliant',
    text: 'Backing into a tight garage space between the family SUV and workshop bench is stress-free with the wide angle colour reversing camera. Crisp HD display on the 9-inch dash.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Atlas 4-Passenger Luxury Resort Buggy',
    helpfulCount: 15,
  },
  // 60 (3-star) - #12 of 17
  {
    id: 'tp-060',
    author: 'Trevor Collins',
    location: 'Burnie, TAS',
    rating: 3,
    date: '8 months ago',
    title: 'Seat covers fit snug, installation takes patience',
    text: 'The two-tone marine vinyl seat covers look like factory original upholstery once fitted. Stretching them tightly over the original foam cushions took about 40 minutes of pulling.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Custom Diamond-Stitch Seat Cover Set',
    helpfulCount: 8,
  },
  // 61 (5-star)
  {
    id: 'tp-061',
    author: 'Eric Schmidt',
    location: 'Victor Harbor, SA',
    rating: 5,
    date: '9 months ago',
    title: '5 years warranty on Eco-Battery provides peace of mind',
    text: 'Registered the warranty online in 2 minutes. The Australian support office is responsive and knowing it has an 8-year design life made the investment well worth it.',
    verified: true,
    category: 'batteries',
    productMentioned: 'Eco-Battery 48V 105Ah Conversion Kit',
    helpfulCount: 22,
  },
  // 62 (4-star) - #15 of 19
  {
    id: 'tp-062',
    author: 'Greg Hansen',
    location: 'Gympie, QLD',
    rating: 4,
    date: '9 months ago',
    title: 'Solid utility box, tailgate latch is quite firm',
    text: 'The aluminium diamond plate rear cargo box is great for carrying tools, garden mulch, and sports gear. Tailgate slam latch needs a firm push to click into lock position.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Aluminium Diamond Plate Rear Utility Box',
    helpfulCount: 7,
  },
  // 63 (5-star)
  {
    id: 'tp-063',
    author: 'Geoffrey Lewis',
    location: 'Ballarat, VIC',
    rating: 5,
    date: '9 months ago',
    title: 'Self-balancing gyro keeps cart straight on side hills',
    text: 'On severe sloping fairways where older buggies veer toward the rough, this robotic cart tracks dead true. Great engineering on the front axle sensors.',
    verified: true,
    category: 'buggies',
    productMentioned: 'MGI AI Navigator GPS Buggy',
    helpfulCount: 18,
  },
  // 64 (3-star) - #13 of 17
  {
    id: 'tp-064',
    author: 'Peter Sterling',
    location: 'Dubbo, NSW',
    rating: 3,
    date: '9 months ago',
    title: 'GPS screen is crisp, touch sensitivity reduced in heavy rain',
    text: 'The colour GPS mapping screen is clear and distances are accurate to 1 metre. When heavy rain drops hit the screen, touch sensitivity can require wiping off water droplets.',
    verified: true,
    category: 'buggies',
    productMentioned: 'MGI AI Navigator GPS Buggy',
    helpfulCount: 9,
  },
  // 65 (5-star)
  {
    id: 'tp-065',
    author: 'Martin Boyd',
    location: 'Albury-Wodonga, NSW',
    rating: 5,
    date: '10 months ago',
    title: 'Replaced lead acid batteries—cart is 150kg lighter!',
    text: 'Steering feels lighter, tires don’t rut the fairway in winter, and acceleration is instant. Best performance upgrade you can do to an electric cart.',
    verified: true,
    category: 'batteries',
    productMentioned: 'RoyPow 48V 105Ah LiFePO4 Battery',
    helpfulCount: 19,
  },
  // 66 (4-star) - #16 of 19
  {
    id: 'tp-066',
    author: 'Stewart Long',
    location: 'Sunbury, VIC',
    rating: 4,
    date: '10 months ago',
    title: 'Great cart, horn button could be more prominent',
    text: 'Smooth driving buggy with great hill climb power and comfortable seats. The horn button on the steering stalk is slightly small to hit quickly with driving gloves on.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution Classic 2 Plus Fleet',
    helpfulCount: 6,
  },
  // 67 (5-star)
  {
    id: 'tp-067',
    author: 'Kenrick Davies',
    location: 'Cairns, QLD',
    rating: 5,
    date: '10 months ago',
    title: 'Fold-down rear seat transforms cart into a utility truck',
    text: 'When grand kids visit, it’s a 4-seater. When working in the yard, the rear seat flips open to a flat thermoplastic cargo deck. Incredibly versatile design.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution Forester 4 Plus',
    helpfulCount: 14,
  },
  // 68 (3-star) - #14 of 17
  {
    id: 'tp-068',
    author: 'Bruce MacIntyre',
    location: 'Warrnambool, VIC',
    rating: 3,
    date: '10 months ago',
    title: 'Good battery meter, display is bright in twilight',
    text: 'Digital state of charge gauge mounted cleanly into the dashboard cutout. Very accurate percentage readings. At dusk it is slightly bright, though perfectly readable in bright sunlight.',
    verified: true,
    category: 'batteries',
    productMentioned: 'Digital Lithium Battery SOC Gauge Kit',
    helpfulCount: 7,
  },
  // 69 (5-star)
  {
    id: 'tp-069',
    author: 'Terrence Walsh',
    location: 'Rockhampton, QLD',
    rating: 5,
    date: '11 months ago',
    title: 'Arrived fully assembled—just plug in and drive',
    text: 'No complicated assembly required. Unstrapped the transport crate, connected the master battery cutoff switch, checked tire pressures, and drove straight onto the green.',
    verified: true,
    category: 'service',
    productMentioned: 'Atlas 2-Passenger Lithium Golf Buggy',
    helpfulCount: 12,
  },
  // 70 (4-star) - #17 of 19
  {
    id: 'tp-070',
    author: 'David Prentice',
    location: 'Launceston, TAS',
    rating: 4,
    date: '11 months ago',
    title: 'High quality cooler box, bracket mounting was tight',
    text: 'Insulated marine cooler keeps drinks ice cold for 36 holes. The mounting bracket bolts behind the driver seat were a snug fit against the battery box shroud.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Side Mount 12-Can Insulated Cooler Box',
    helpfulCount: 8,
  },
  // 71 (5-star)
  {
    id: 'tp-071',
    author: 'Nigel Fletcher',
    location: 'Toowoomba, QLD',
    rating: 5,
    date: '11 months ago',
    title: 'USB fast charge ports keep rangefinders and phones powered',
    text: 'Dual QC 3.0 USB ports integrated into the glove compartment. Kept my GPS watch and phone at 100% all afternoon while running score apps.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Atlas 4-Passenger Luxury Resort Buggy',
    helpfulCount: 9,
  },
  // 72 (3-star) - #15 of 17
  {
    id: 'tp-072',
    author: 'Graham Bishop',
    location: 'Port Macquarie, NSW',
    rating: 3,
    date: '11 months ago',
    title: 'Good floor mat, needs to sit in sun to flatten after unboxing',
    text: 'Heavy duty custom-moulded rubber floor liner protects the cart floor from mud and golf spikes. Shipped rolled in a box, so you need to lay it flat in the sun for an hour before installing.',
    verified: true,
    category: 'accessories',
    productMentioned: 'All-Weather Custom Rubber Floor Liner',
    helpfulCount: 6,
  },
  // 73 (5-star)
  {
    id: 'tp-073',
    author: 'Clifford Grant',
    location: 'Perth, WA',
    rating: 5,
    date: '11 months ago',
    title: '48V lithium conversion runs 4 rounds of golf on single charge',
    text: 'Tested over 4 rounds at Secret Harbour without charging in between. Battery still had 28% remaining. Incredible efficiency compared to old battery technology.',
    verified: true,
    category: 'batteries',
    productMentioned: 'Eco-Battery 48V 105Ah Conversion Kit',
    helpfulCount: 25,
  },
  // 74 (4-star) - #18 of 19
  {
    id: 'tp-074',
    author: 'Vernon Hayes',
    location: 'Darwin, NT',
    rating: 4,
    date: '1 year ago',
    title: 'Powerful cooling fan kit, slightly tricky wire routing',
    text: 'The dual 12V dashboard air blowers make a huge difference in tropical humidity. Wire routing under the front cowl took some patience to zip tie neatly out of sight.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Dual 12V High-Velocity Dash Fan System',
    helpfulCount: 7,
  },
  // 75 (5-star)
  {
    id: 'tp-075',
    author: 'Warren Brooks',
    location: 'Mornington Peninsula, VIC',
    rating: 5,
    date: '1 year ago',
    title: 'Premium diamond stitch seats are supportive and comfy',
    text: 'High-density foam with lumbar support makes a huge difference over 18 holes. Back pain after golf is completely gone.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Atlas 4-Passenger Luxury Resort Buggy',
    helpfulCount: 16,
  },
  // 76 (3-star) - #16 of 17
  {
    id: 'tp-076',
    author: 'Trevor Nichols',
    location: 'Mildura, VIC',
    rating: 3,
    date: '1 year ago',
    title: 'Ball washer works well, drain plug thread is fine plastic',
    text: 'Clubs and balls come out sparkling clean. The bottom drain thumb screw is plastic; be careful not to cross-thread when replacing water and detergent.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Side Strut Mount Club & Ball Washer',
    helpfulCount: 5,
  },
  // 77 (5-star)
  {
    id: 'tp-077',
    author: 'Raymond Scott',
    location: 'Central Coast, NSW',
    rating: 5,
    date: '1 year ago',
    title: 'Responsive customer support on WhatsApp for setup tips',
    text: 'Sent a quick photo on WhatsApp asking about the charger LED colours. Received a clear video walkthrough within 5 minutes. Brilliant customer service.',
    verified: true,
    category: 'service',
    helpfulCount: 13,
  },
  // 78 (4-star) - #19 of 19
  {
    id: 'tp-078',
    author: 'Lindsay Walker',
    location: 'Canberra, ACT',
    rating: 4,
    date: '1 year ago',
    title: 'Sturdy roof rack, wind noise noticeable at top 35 km/h speed',
    text: 'Heavy aluminium basket roof rack holds bags and camping gear easily. At full top speed of 35 km/h on estate roads you can hear some wind buffeting, but nothing alarming.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Aluminium Heavy Duty Roof Basket Rack',
    helpfulCount: 8,
  },
  // 79 (5-star)
  {
    id: 'tp-079',
    author: 'Darrell Price',
    location: 'Bendigo, VIC',
    rating: 5,
    date: '1 year ago',
    title: 'The electronic park brake auto-engages on slopes',
    text: 'Automatic electromagnetic brake engages the second you lift off the accelerator. You never have to kick a manual brake pedal into locked notch position.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution D5 Maverick 4-Seater',
    helpfulCount: 20,
  },
  // 80 (3-star) - #17 of 17
  {
    id: 'tp-080',
    author: 'Stanley Howard',
    location: 'Goulburn, NSW',
    rating: 3,
    date: '1 year ago',
    title: 'Solid cart cover, storage bag is a tight squeeze to repack',
    text: 'Waterproof cover protects against frost and dust in the car port. Once unpacked, folding it small enough to get back into the zip carry pouch requires origami skills.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Universal 4-Passenger Heavy Dust & Rain Cover',
    helpfulCount: 7,
  },
  // 81 (5-star)
  {
    id: 'tp-081',
    author: 'Neville King',
    location: 'Surfers Paradise, QLD',
    rating: 5,
    date: '1 year ago',
    title: 'Zero battery maintenance—no more distilled water top-ups',
    text: 'Used to spend every second weekend checking battery acid levels and scrubbing terminal corrosion. Lithium is completely sealed and maintenance-free.',
    verified: true,
    category: 'batteries',
    productMentioned: 'RoyPow 48V 105Ah LiFePO4 Battery',
    helpfulCount: 28,
  },
  // 82 (5-star)
  {
    id: 'tp-082',
    author: 'Ian McDonald',
    location: 'Adelaide Hills, SA',
    rating: 5,
    date: '1 year ago',
    title: 'Smooth acceleration and whisper quiet motor operation',
    text: 'Cruising through the quiet morning fairways without any engine noise or motor whine. Birds don’t even fly away as you roll past.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Atlas 2-Passenger Lithium Golf Buggy',
    helpfulCount: 11,
  },
  // 83 (5-star)
  {
    id: 'tp-083',
    author: 'Barry Bennett',
    location: 'Young, NSW',
    rating: 5,
    date: '1 year ago',
    title: 'Robotic follow buggy saves energy for the back nine',
    text: 'I used to get exhausted walking the last 4 holes. With the motorized remote cart carrying the bag, I feel fresh and my handicap has dropped 2 shots.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Robera Pro Follow Remote Golf Buggy',
    helpfulCount: 22,
  },
  // 84 (5-star)
  {
    id: 'tp-084',
    author: 'Peter Mitchell',
    location: 'Wonthaggi, VIC',
    rating: 5,
    date: '1 year ago',
    title: 'Eco-Battery 48V kit transformed our 2018 Club Car',
    text: 'Feels like a brand new $20,000 cart. Climbs hills effortlessly and charges in 2.5 hours.',
    verified: true,
    category: 'batteries',
    productMentioned: 'Eco-Battery 48V 105Ah Conversion Kit',
    helpfulCount: 20,
  },
  // 85 (5-star)
  {
    id: 'tp-085',
    author: 'Graham Ward',
    location: 'Atherton, QLD',
    rating: 5,
    date: '1 year ago',
    title: 'Sand divot bottles with metal bracket mounts don’t rattle',
    text: 'High quality UV stabilized plastic with curved pour spout. Essential for maintaining fairway etiquette.',
    verified: true,
    category: 'accessories',
    productMentioned: 'Heavy Duty Sand Bottle Assembly',
    helpfulCount: 7,
  },
  // 86 (5-star)
  {
    id: 'tp-086',
    author: 'Keith Sullivan',
    location: 'Wollongong, NSW',
    rating: 5,
    date: '1 year ago',
    title: '5 stars for service, communication, and prompt delivery',
    text: 'Every step from quote negotiation, battery selection, to door delivery was handled with consummate professionalism. Highly recommended.',
    verified: true,
    category: 'general',
    helpfulCount: 14,
  },
  // 87 (5-star)
  {
    id: 'tp-087',
    author: 'Anthony Rossi',
    location: 'Sydney, NSW',
    rating: 5,
    date: '1 year ago',
    title: 'Unbeatable value and premium build standard',
    text: 'Searched for months across all dealers. Golf Buggies Express provided the highest specification chassis and lithium pack at the most competitive price.',
    verified: true,
    category: 'buggies',
    productMentioned: 'Evolution Classic 4 Plus',
    helpfulCount: 19,
  },
  // 88 (5-star)
  {
    id: 'tp-088',
    author: 'Brian Campbell',
    location: 'Newcastle, NSW',
    rating: 5,
    date: '1 year ago',
    title: 'Great remote range—works up to 50 metres away',
    text: 'I can send the buggy ahead to the next tee while finishing putting on the green. Saves time and walks straight as an arrow.',
    verified: true,
    category: 'buggies',
    productMentioned: 'MGI Zip Navigator AT',
    helpfulCount: 15,
  },
  // 89 (5-star)
  {
    id: 'tp-089',
    author: 'Dennis O’Keefe',
    location: 'Geelong, VIC',
    rating: 5,
    date: '1 year ago',
    title: 'Best investment for our golf resort accommodation',
    text: 'Guests love having dedicated electric carts to commute between their luxury villas, tennis courts, and clubhouse.',
    verified: true,
    category: 'service',
    productMentioned: 'Atlas 4-Passenger Luxury Resort Buggy',
    helpfulCount: 18,
  },
  // 90 (5-star)
  {
    id: 'tp-090',
    author: 'Trevor Hughes',
    location: 'Adelaide, SA',
    rating: 5,
    date: '1 year ago',
    title: 'Aussie company that actually answers the phone',
    text: 'Called on a Saturday morning with a question about charging cycles and got connected to a knowledgeable technician right away. Rare to see this level of support nowadays.',
    verified: true,
    category: 'service',
    helpfulCount: 26,
  },
];
