// src/config/site.ts - The Single Source of Truth for WebForge v9.1

export interface ProductItem {
  id: string;
  slug: string;
  name: string;
  category: string;
  fuel_type: string;
  price_aud: number;
  price_display: string;
  search_intent: string;
  target_audience: string;
  key_specs: string;
  shortDescription: string;
  // fullDescription, faqs, primaryKeyword and supportingKeywords live in
  // src/config/product-details.ts (server-only) - see ProductDetails there.
  badge?: string;
  featured?: boolean;
  images: string[];
  inStock?: boolean;

}

export const SITE = {
  name: 'The Buggies Express',
  legalEntity: 'Golf Buggies Express PTY LTD',
  tagline: "Australia's Most Complete Golf Buggy & Cart Specialists",
  domain: 'www.golfbuggiesexpress.com.au',
  locale: 'en-AU',
  currency: 'AUD',
  currencySymbol: '$',
  target: 'vercel',
  // Palette: Australian coastal & outback luxury. Warm bone canvas, white
  // card surfaces, architectural charcoal ink, sun-baked terracotta accent.
  primaryColor: '#C86D51',   // sun-baked terracotta - primary accent
  accentPressed: '#A85640',  // terracotta, hover/pressed
  accentFill: '#B45A40',     // solid CTA fill (clears 4.5:1 with white label)
  accentTint: '#F7EFEA',     // terracotta wash surface
  accentOnDark: '#E2A17A',   // ochre sand - highlights on charcoal
  charcoal: '#121417',       // architectural charcoal - ink and dark sections
  graphite: '#2B2F34',       // brushed graphite - borders on dark surfaces
  stoneMuted: '#78716C',     // secondary copy
  boneCanvas: '#F7F6F2',     // warm bone page canvas
  hairline: '#E7E5E4',       // 1px architectural border
  gscVerification: 'c84GqyF8sZHI_WHs_IfgbUi3R4vSlC2sR_zklWfWSI8',
  indexNowKey: 'golfbuggiesexpress-idx-2025',
  cartKey: 'buggies-express-cart',
};

// Sitemap <lastmod> dates. Google ignores lastmod once it sees it lie, and the
// old sitemap stamped every URL with the build time, so 118 pages claimed to
// change on every deploy. These are bumped by hand when the content they
// cover actually changes; blog posts use their own `date`.
export const CONTENT_UPDATED = {
  /** PRODUCTS, CATEGORIES or BRAND_PAGES changed (prices, specs, copy, new models). */
  catalog: '2026-09-11',
  /** Static pages: home, about, faq, delivery, contact, crypto-payment, wholesale. */
  pages: '2026-09-11',
};

export function isAccessoryItem(category?: string, id?: string, name?: string): boolean {
  if (id && id.startsWith('PART-')) return true;
  const cat = (category || '').toLowerCase();
  if (cat.includes('batteries') || cat.includes('chargers') || cat.includes('parts')) return true;
  const n = (name || '').toLowerCase();
  if (n.includes('charger') || n.includes('battery') || n.includes('cover') || n.includes('enclosure') || n.includes('windshield') || n.includes('solar') || n.includes('cable') || n.includes('mirror') || n.includes('caddy') || n.includes('cup holder') || n.includes('conversion kit')) return true;
  return false;
}

export function isBuggyItem(category?: string, id?: string, name?: string): boolean {
  return !isAccessoryItem(category, id, name);
}

export const ABN_INFO = {
  companyName: 'GOLF BUGGIES EXPRESS PTY LTD',
  acn: '668 598 758',
  abn: '28 668 598 758',
  abnFormatted: '28 668 598 758',
  status: 'Registered',
  registeredDate: '7/06/2023',
  registrationDate: '7/06/2023',
  reviewDate: '7/06/2027',
  regulator: 'Australian Securities & Investments Commission (ASIC)',
  locality: 'YATALA QLD 4207',
  country: 'Australia',
  officialLookupUrl: 'https://abr.business.gov.au/ABN/View?id=28668598758',
  abrLookupUrl: 'https://abr.business.gov.au/ABN/View?id=28668598758',
  officialAbrLink: 'https://abr.business.gov.au/ABN/View?id=28668598758',
  heroQuote: "Australia's most complete golf buggy business — sales, service, warranty, parts, and custom builds, backed by support that doesn't end at delivery.",
};

export const CONTACT = {
  email: 'sales&#64;golfbuggiesexpress.com.au',
  emailRaw: 'sales@golfbuggiesexpress.com.au',
  phone: '+61 480 804 189',
  phoneDisplay: '0480 804 189',
  whatsappNumber: '+61480804189',
  whatsappUrl: 'https://wa.me/61480804189',
  address: 'Yatala Industrial Hub, Yatala QLD 4207',
  hq: 'Yatala, Queensland, Australia',
  country: 'Australia',
  serviceFootprint: 'Australia-wide direct freight & enclosed delivery (Gold Coast, Brisbane, Sydney, Melbourne, Perth, Adelaide, Cairns)',
};

// Order rules. This block is the ONLY source of truth for them - CLAUDE.md
// deliberately no longer restates the numbers, so they cannot drift again.
//
// Confirmed by the owner 2026-09-10: there is NO minimum order, and NO
// free-freight threshold. Freight is always quoted against the delivery
// postcode at checkout. The earlier $1,000 / $25,000 / $500 figures were
// stale and are gone - do not reintroduce any of them.
export const SHOP = {
  minOrder: 0,                     // confirmed: no minimum order
  freeShippingThreshold: null,     // confirmed: no free-freight offer; always quoted
  shippingNote: 'Calculated according to location/distance & pallet freight requirements',
  cryptoDiscount: 10, // 10% on BTC / USDT
  accessoryBundleDiscount: 5, // 5% discount on all accessories when purchased alongside any buggy
  financeIn4: {
    enabled: true,
    installments: 4,
    interestRate: '0%',
    frequency: 'Fortnightly or Monthly',
    description: 'Split your purchase into 4 equal interest-free installments with 0% interest and instant approval.',
  },
  paymentMethods: [
    'PayID / Osko',
    'Direct Bank Transfer (EFT)',
    'Finance in 4 (4 Equal Interest-Free Payments)',
    'Crypto (BTC / USDT - 10% Off)',
  ],
};

// Crypto settlement. Buyers paying in BTC or USDT take SHOP.cryptoDiscount off
// the vehicle price; freight and accessories are charged at full rate on top.
//
// The seller addresses below are intentionally empty. They must be pasted in by
// the business owner and checked character by character - a mistyped address
// sends funds somewhere unrecoverable, and there is no reversal on a settled
// chain transaction. While an address is blank the portal hides the
// "pay the seller directly" route rather than showing a placeholder.
export const CRYPTO = {
  discountPercent: SHOP.cryptoDiscount,
  wallets: [
    {
      key: 'btc',
      asset: 'BTC',
      assetName: 'Bitcoin',
      network: 'Bitcoin mainnet',
      addressHint: 'starts with bc1, 1 or 3',
      address: 'bc1qe3mfevg3ud3jukp9ad37wszcfrwev7zxxex5u5',
    },
    {
      key: 'usdt-trc20',
      asset: 'USDT',
      assetName: 'Tether',
      network: 'Tron (TRC-20)',
      addressHint: 'starts with T',
      address: 'TVQGzSJKcHXTwX6Fn8CPb6A5PmAkoCFZRh',
    },
    {
      key: 'usdt-erc20',
      asset: 'USDT',
      assetName: 'Tether',
      network: 'Ethereum (ERC-20)',
      addressHint: 'starts with 0x',
      address: '0x2629c24d3720E5A24adBe7Bde4677334B559C36D',
    },
  ],
  // Payment is taken on-site (CryptoCheckout): the three addresses above,
  // a QR code and a WhatsApp receipt step. No exchange is linked or recommended.
};

export const FORMS = {
  provider: 'web3forms',
  web3formsKey: 'PENDING',
  zohoEmail: 'sales@golfbuggiesexpress.com.au',
  resendFrom: '',
  turnstileSiteKey: '',
};

export const CHAT = {
  whatsappNumber: '+61480804189',
  tawkPropertyId: 'pending',
};

export const BRAND = {
  foundingYear: '2023',
  foundingLocation: 'Queensland, Australia',
  description: "Australia's most complete golf buggy business — sales, service, warranty, parts, and custom builds, backed by support that doesn't end at delivery.",
  milestones: [
    { year: '2023', event: 'Registered GOLF BUGGIES EXPRESS PTY LTD (ACN 668 598 758) in Yatala QLD to bridge the gap in genuine warranty-backed golf cart sales across Australia.' },
    { year: '2024', event: 'Expanded Yatala central depot to house over 60+ in-stock models spanning lithium 4-seaters, farm utilities, and remote walk-behind buggies.' },
    { year: '2025', event: 'Expanded dedicated national delivery and freight network delivering crated and ready-to-drive golf buggies directly across regional QLD, NSW, VIC, and nationwide.' },
  ],
  differentiation: [
    'Service & warranty that does not stop at delivery — backed by dedicated technicians and field support.',
    'A true one-stop Australian shop: new, certified pre-owned, batteries, chargers, and custom builds all under one roof.',
    'Built for every customer: golf club fleet operators, luxury gated estate residents, and heavy acreage farm owners.',
    'Quality & customisation without the usual trade-offs: factory lithium upgrades, high-torque lift packages, and prompt freight delivery.',
  ],
  sameAs: [],
  awards: [],
};

// Factory finishes offered across the fleet. The swatch applies a CSS filter
// to the product photograph so the buyer can preview a finish; the render is
// indicative only, which the UI states plainly next to the swatches.
// Brands carried, with the model count each. Counts are derived from PRODUCTS
// at build time in the nav, so this list only names the brand and its query.
export const BRANDS = [
  { name: 'Club Car', q: 'Club Car' },
  { name: 'E-Z-GO', q: 'E-Z-GO' },
  { name: 'Yamaha', q: 'Yamaha' },
  { name: 'Evolution', q: 'Evolution' },
  { name: 'LVTONG', q: 'LVTONG' },
  { name: 'Tara', q: 'Tara' },
  { name: 'MGI', q: 'MGI' },
  { name: 'Atlas', q: 'Atlas' },
] as const;

/**
 * Shop-by-brand pages. `match` is tested case-insensitively against a
 * product name to build each brand's range, so adding a product to PRODUCTS
 * automatically lands it on the right brand page.
 *
 * Only brands we actually stock appear here. Rival brands are discussed in
 * blog comparisons and never given a shop page, because a shop page implies
 * stock we do not hold.
 */
export interface BrandPage {
  slug: string;
  name: string;
  match: string;
  origin: string;
  primaryKeyword: string;
  supportingKeywords: string[];
  intro: string;
  body: string;
}

export const BRAND_PAGES: BrandPage[] = [
  {
    slug: 'club-car',
    name: 'Club Car',
    match: 'club car',
    origin: 'United States',
    primaryKeyword: 'club car golf carts',
    supportingKeywords: ['club car golf buggy australia', 'clubcar golf carts for sale', 'club car golf cart parts', 'club car onward australia', 'club car tempo australia', 'club car utility vehicle'],
    intro: 'Club Car golf buggies for sale in Australia, stocked and serviced from our Yatala QLD depot with genuine parts held locally.',
    body: 'Club Car is the brand buyers choose when resale value matters as much as the drive. The aircraft-grade aluminium frame is the reason: aluminium does not rust, so coastal salt air and irrigated fairways cannot eat the chassis out from under the bodywork the way they do with steel-framed imports. That single material decision is why a well-kept Club Car holds its price years after a cheaper buggy has become a liability. We carry the Onward, Tempo, Carryall and Transporter lines, spanning private golf, estate driving, grounds work and passenger shuttling, in both lithium and EFI petrol. Parts are held in Australia rather than ordered in when something fails.',
  },
  {
    slug: 'mgi',
    name: 'MGI',
    match: 'mgi',
    origin: 'Australia',
    primaryKeyword: 'mgi golf buggy',
    supportingKeywords: ['mgi golf cart', 'mgi golf buggies', 'mgi golf buggy australia', 'mgi buggy', 'mgi golf carts', 'mgi zip navigator'],
    intro: 'MGI motorised and remote control golf buggies, the Australian-designed walk-behind range, in stock at Yatala QLD.',
    body: 'MGI is an Australian company and it shows in how the buggies are set up for local courses. The Zip and Ai Navigator ranges cover the whole walk-behind spectrum, from a simple speed dial for a first motorised buggy through to full directional remote control with gyroscope straight-tracking that holds a line across cambered fairways. Australian conditions were the design brief rather than an afterthought, which matters on kikuyu and couch turf and through a wet season. Genuine MGI batteries, remotes and accessories are held in Australian stock, so a worn consumable does not mean replacing an otherwise healthy buggy.',
  },
  {
    slug: 'e-z-go',
    name: 'E-Z-GO',
    match: 'e-z-go',
    origin: 'United States',
    primaryKeyword: 'ezgo golf buggy',
    supportingKeywords: ['ezgo golf cart parts australia', 'ez go golf carts', 'ezgo golf carts for sale', 'ezgo golf buggy parts', 'e-z-go golf cart', 'ezgo rxv australia'],
    intro: 'E-Z-GO golf buggies and utility vehicles for sale in Australia, with ELiTE lithium models and EFI petrol, supported from Yatala QLD.',
    body: 'E-Z-GO builds around safety and serviceability rather than headline specifications. The RXV ELiTE is the clearest example: its automatic electromagnetic brake holds the buggy the instant you lift off the throttle, so it will not creep on a steep fairway or a sloped village driveway. For retirement village residents and anyone parking on an incline, that behaviour is worth more than any number on a spec sheet. The range runs from two-seat golf models through the six-seat Express L6 to the Cushman Hauler commercial line. ELiTE lithium uses Samsung SDI cells, and parts are stocked in Australia.',
  },
  {
    slug: 'yamaha',
    name: 'Yamaha',
    match: 'yamaha',
    origin: 'Japan',
    primaryKeyword: 'yamaha golf carts',
    supportingKeywords: ['yamaha golf cart parts', 'yamaha golf buggy parts', 'yamaha golf carts australia', 'yamaha golf cart for sale', 'yamaha golf car parts', 'yamaha drive2 australia'],
    intro: 'Yamaha golf buggies and UMAX utility vehicles for sale in Australia, including the QuietTech EFI petrol range, from our Yatala QLD depot.',
    body: 'Yamaha brings its engine and chassis engineering to a category where most competitors buy both in. Two things stand out. Independent front and rear suspension on the Drive2 is rare at this level and it is why the buggy absorbs rough turf and unsealed tracks as a muted movement rather than a jolt through the seat frame. And QuietTech petrol answers the one real objection to combustion: it brings a petrol buggy close enough to electric in sound that conversation at speed stays comfortable, while keeping unlimited range and one-minute refuelling. The UMAX line covers livestock properties and large regional venues.',
  },
  {
    slug: 'evolution',
    name: 'Evolution',
    match: 'evolution',
    origin: 'United States',
    primaryKeyword: 'evolution golf carts australia',
    supportingKeywords: ['evolution d5 golf cart', 'evolution golf cart price', 'evolution electric golf cart', 'evolution d5 ranger', 'evolution golf buggy', 'evolution classic golf cart'],
    intro: 'Evolution electric golf buggies for sale in Australia, from the six-passenger D5 Ranger to the Classic 2 Plus, in stock at Yatala QLD.',
    body: 'Evolution builds the most screen-forward buggies we stock, and for buyers coming across from a modern car that familiarity matters. The D5 Ranger 4+2 carries six passengers with forward-facing seating in both rows, a nine-inch touchscreen and a 110Ah lithium pack, which makes it the largest-capacity model in our luxury range. The Classic 2 Plus brings automotive-level instrumentation to a two-seat buggy: a 6.3-inch LCD, side mirrors with integrated turn signals and reverse camera compatibility, which is what buyers on shared estate roads actually ask for. The 700 heavy commercial utility covers facility and patrol work.',
  },
  {
    slug: 'lvtong',
    name: 'LVTONG',
    match: 'lvtong',
    origin: 'China',
    primaryKeyword: 'lvtong golf cart australia',
    supportingKeywords: ['lvtong golf buggy', 'lvtong electric golf cart', 'lvtong resort cruiser', 'commercial golf buggy australia', 'holiday park golf buggy', 'caravan park golf cart'],
    intro: 'LVTONG electric golf buggies for Australian resorts, caravan parks and commercial operators, supplied and supported from Yatala QLD.',
    body: 'LVTONG is specified by operators who count running cost per year rather than features per brochure, and it has become a proven workhorse across Australian caravan parks and holiday resorts. The Resort Cruiser pairs a 4kW AC motor with a maintenance-free lithium pack and an on-board charger, so any standard outlet becomes a charging point without new infrastructure. Heavy-duty bumpers take the knocks that shared-use vehicles collect from bollards and gateposts. The commercial flatbed adds a low steel mesh deck that drains, turning awkward lifts into slides for nursery and grounds work.',
  },
  {
    slug: 'tara',
    name: 'Tara',
    match: 'tara',
    origin: 'Australia',
    primaryKeyword: 'tara golf buggy australia',
    supportingKeywords: ['tara roadster golf cart', 'affordable golf buggy australia', 'value golf cart australia', 'lifted golf buggy value', 'budget 4 seater golf cart', 'tara spirit golf buggy'],
    intro: 'Tara golf buggies for sale in Australia, the value end of the lifted and two-seat lithium range, from our Yatala QLD depot.',
    body: 'Tara is where the range earns its value position with hardware rather than trim. The Roadster 2+2 Lifted is the clearest case: hydraulic disc brakes on a lifted chassis give genuine stopping control on sloped semi-rural driveways where drum brakes fade and feel vague under load, and the rear flip seat converts from passenger bench to flat cargo deck in seconds. The Roadster 4 Off-Road uses a high-torque gear reduction chosen specifically for sustained climbing rather than flat-ground speed. The Spirit Pro is a straightforward lithium two-seater for golfers stepping away from an ageing lead-acid buggy.',
  },
  {
    slug: 'atlas',
    name: 'Atlas',
    match: 'atlas',
    origin: 'United States',
    primaryKeyword: 'atlas golf carts',
    supportingKeywords: ['atlas golf carts australia', 'atlas golf carts for sale', 'atlas golf cart accessories', 'atlas golf cars', 'atlas lifted golf cart', 'atlas 4 passenger buggy'],
    intro: 'Atlas lifted lithium golf buggies for Australian estates and acreage, including the 350A heavy-duty model, in stock at Yatala QLD.',
    body: 'Atlas is the range we point acreage owners at when a standard-height buggy has already disappointed them. Both models are built around ground clearance and hill capability rather than fairway manners. The 4-Passenger Lifted pairs a three-inch factory lift and 14-inch alloys with custom leather seating, so it clears rutted estate driveways without giving up cabin comfort. The Heavy-Duty Lifted 350A goes further, with a 350-amp controller and four-wheel hydraulic disc brakes: controller amperage is what decides whether a laden four-seater walks up a steep farm track or bogs down halfway, and the brakes are what get it back down.',
  },
  {
    slug: 'cushman',
    name: 'Cushman',
    match: 'cushman',
    origin: 'United States',
    primaryKeyword: 'cushman utility vehicle australia',
    supportingKeywords: ['cushman hauler australia', 'cushman golf cart parts', 'cushman hauler 1200', 'commercial utility buggy australia', 'turf utility vehicle australia', 'grounds maintenance buggy'],
    intro: 'Cushman Hauler utility vehicles for Australian turf, grounds and agricultural work, supplied from our Yatala QLD depot.',
    body: 'Cushman is a work brand, and the specification reflects it. The Hauler PRO runs a 72V AC drive rather than the 48V systems common elsewhere in the range, and higher system voltage lets it move heavy loads at lower current, running cooler and holding performance through a full shift. Its optional electric dump bed turns tipping a load of sand or mulch into a button rather than a shovel. The petrol Hauler 1200 takes the opposite approach: a 13.5HP Kawasaki engine and a manual dump bed, with fewer systems to fail a long way from the shed. Both carry substantial rated loads.',
  },
  {
    slug: 'powakaddy',
    name: 'PowaKaddy',
    match: 'powakaddy',
    origin: 'United Kingdom',
    primaryKeyword: 'powakaddy golf buggy',
    supportingKeywords: ['powakaddy australia', 'powakaddy electric golf buggies', 'powakaddy golf trolleys', 'powakaddy buggy', 'powakaddy fx7 australia', 'uk electric golf trolley australia'],
    intro: 'PowaKaddy electric golf trolleys in Australia, including the FX7 GPS lithium, stocked and warranty-supported from Yatala QLD.',
    body: 'PowaKaddy brings UK engineering and the most readable screen in the walk-behind category. The FX7 carries a 3.5-inch OCA full-colour touchscreen preloaded with over 40,000 courses worldwide, so it works on your home course and on holiday without hunting for a download before every round. OCA bonding is the reason it stays legible in Australian sunlight where cheaper laminated screens wash out. The 30V Plug and Play lithium system fits and removes without tools, which matters when the buggy lives in a car boot between rounds and the battery comes inside to charge.',
  },
  {
    slug: 'robera',
    name: 'Robera',
    match: 'robera',
    origin: 'International',
    primaryKeyword: 'robera golf buggy australia',
    supportingKeywords: ['follow me golf buggy australia', 'hands free golf trolley', 'smart follow golf caddy', 'robera pro golf buggy', 'ai golf buggy australia', 'self following golf buggy'],
    intro: 'Robera hands-free follow golf buggies in Australia, the smart-tracking walk-behind option, stocked at our Yatala QLD depot.',
    body: 'Robera is the only buggy in our range that needs no input at all once you start walking. A smart tracking tag clips to your belt and the buggy follows your footsteps at a safe distance, so there is no remote to hold, no dial to adjust and nothing to think about between shots. Dual-mode remote control is still there when you want to send it ahead. All-terrain dual motors supply the independent drive that follow-mode needs to hold a line across slopes and around obstacles rather than cutting corners. For buyers who decided the point of walking is to walk unencumbered, this is the step up.',
  },
];

export const VEHICLE_COLORS = [
  { id: 'factory', name: 'Factory Finish', swatch: '#E7E5E4', filter: 'none' },
  { id: 'coastal-teal', name: 'Coastal Teal', swatch: '#2E8B87', filter: 'hue-rotate(150deg) saturate(1.25)' },
  { id: 'outback-ochre', name: 'Outback Ochre', swatch: '#C86D51', filter: 'hue-rotate(330deg) saturate(1.3)' },
  { id: 'graphite', name: 'Graphite Black', swatch: '#2B2F34', filter: 'saturate(0.25) brightness(0.82) contrast(1.1)' },
] as const;

// metaTitle / metaDescription carry each category's own keyword cluster
// (see docs/keyword-map.md). Without them every category inherits one
// templated description, which reads as near-duplicate content and wastes
// seven chances to place cluster terms. Titles <=60 chars, descriptions ~150.
export const CATEGORIES = [
  { slug: 'all', name: 'All Vehicles & Parts', count: 62 },
  {
    slug: 'luxury-4-seater',
    name: 'Luxury 4-Seater',
    rawCategory: 'Luxury & High-Demand 4-Seaters',
    count: 6,
    metaTitle: '4 Seater Golf Buggies for Sale Australia | Buggies Express',
    metaDescription:
      'Six luxury 4-seater golf buggies for sale in Australia, including 4+2 six-passenger cruisers. Lithium models tested at our Yatala QLD depot.',
  },
  {
    slug: 'traditional-2-seater',
    name: 'Traditional 2-Seater',
    rawCategory: 'Traditional 2-Seater Electric Golf Buggies',
    count: 6,
    metaTitle: '2 Seater Electric Golf Buggies for Sale | Buggies Express',
    metaDescription:
      'Traditional 2-person golf carts and electric buggies for sale in Australia. Club Car, E-Z-GO and Yamaha lithium models, priced with GST included.',
  },
  {
    slug: 'off-road-4x4',
    name: 'Off-Road 4x4',
    rawCategory: 'Off-Road, Lifted & 4x4 Buggies',
    count: 6,
    metaTitle: 'Lifted 4x4 Off-Road Golf Buggies Australia | Buggies Express',
    metaDescription:
      'Lifted 4x4 golf buggies built for Australian acreage and rough terrain. High ground clearance, heavy-duty brakes and all-terrain tyres from Yatala QLD.',
  },
  {
    slug: 'commercial-utility',
    name: 'Commercial Utility',
    rawCategory: 'Commercial & Farm Utility Buggies',
    count: 6,
    metaTitle: 'Commercial Utility Buggies Australia | Buggies Express',
    metaDescription:
      'Electric utility buggies for farms, resorts and industrial parks across Australia. Flatbed, cargo and 6-passenger transporters with enclosed freight.',
  },
  {
    slug: 'mechanical-petrol',
    name: 'Mechanical Petrol',
    rawCategory: 'Mechanical & Petrol Buggies',
    count: 6,
    metaTitle: 'Petrol Golf Buggies & EFI Carts for Sale | Buggies Express',
    metaDescription:
      'Petrol and EFI golf buggies for sale in Australia. Club Car, Yamaha and E-Z-GO mechanical models for properties without charging infrastructure.',
  },
  {
    slug: 'walk-behind-buggies',
    name: 'Walk-Behind Buggies',
    rawCategory: 'Motorised Walk-Behind Golf Buggies',
    count: 6,
    // Without this the template produces "Walk-Behind Buggies Buggies".
    h1: 'Motorised Walk-Behind Golf Buggies for Sale in Australia',
    metaTitle: 'Golf Trolleys & Motorised Golf Buggies | Buggies Express',
    metaDescription:
      'Motorised, remote control and foldable golf buggies for sale in Australia. MGI, PowaKaddy and Robera electric golf trolleys shipped from Yatala QLD.',
    // Body copy for the largest winnable keyword cluster in docs/keyword-map.md
    // (~3,050/mo, mostly KD < 20). Every claim below is checked against the six
    // products actually in this category. Note: the range is entirely MOTORISED
    // - there are no manual push trolleys in stock, so push buggies are only
    // ever discussed editorially and linked to the guides, never implied to be
    // for sale. Do not add "junior golf buggy" copy either: that cluster lives
    // on the coming-soon /shop/junior-golf-buggies/ page, and nothing here is
    // a junior model.
    intro:
      'Electric golf trolleys and motorised walk-behind buggies for Australian golfers who prefer to walk the course. Six lithium models from $1,299 to $2,849 AUD, including full remote control and hands-free follow, tested and dispatched from our Yatala QLD depot.',
    sections: [
      {
        heading: 'Electric Golf Trolleys vs Push Buggies',
        body: 'A golf push buggy is moved by hand; a motorised golf buggy drives itself under lithium power while you walk beside it. Everything in this category is motorised — we do not stock manual push trolleys. If you are still weighing a push golf buggy against an electric golf trolley, or comparing three-wheel and four-wheel frames, the guides below cover both decisions before you commit to a model.',
      },
      {
        heading: 'Remote Control Golf Buggies',
        body: 'Two models in the range ship with a golf buggy remote. The MGI Ai Navigator adds full directional remote control with an integrated touchscreen GPS and a gyroscope straight tracker, and the Robera Pro offers dual-mode remote plus smart follow — a tracking tag clips to your belt so the buggy follows your footsteps hands-free. Both remote control golf buggies are stocked in Australia with local warranty support rather than parallel imported.',
      },
      {
        heading: 'Foldable and Compact Models',
        body: 'Boot space decides more purchases than any spec sheet. The MGI Zip X1 is the entry point at $1,299 AUD with a compact fold mechanism and a simple variable speed dial, and folding is standard across the range. Check the folded dimensions against your boot before ordering — the foldable buyers guide below walks through measuring it properly.',
      },
      {
        heading: 'Lithium Battery Range and Course Conditions',
        body: 'Every buggy here runs lithium rather than lead-acid. The Zip X5 carries a 36-hole extended lithium battery with downhill speed control and an electronic park brake, while the Zip Navigator pairs twin 230W motors with a rear fold-out fifth wheel for steeper fairway contours. The PowaKaddy FX7 runs a 30V plug-and-play lithium system behind a 3.5-inch colour touchscreen preloaded with over 40,000 courses worldwide.',
      },
    ],
    guides: [
      { slug: 'best-golf-trolley-australia-push-motorized-remote-comparison', label: 'Best golf trolley in Australia: push vs motorised vs remote' },
      { slug: 'best-push-golf-buggy-australia-3-wheel-vs-4-wheel-review', label: 'Push golf buggies compared: three-wheel vs four-wheel' },
      { slug: 'remote-control-golf-buggy-australia-buyers-guide', label: 'Remote control golf buggy buyers guide' },
      { slug: 'foldable-golf-buggy-buyers-guide-boot-space-weight', label: 'Foldable golf buggy guide: boot space and weight' },
      { slug: 'motorised-vs-push-golf-buggy-health-stamina-benefits', label: 'Motorised vs push: what it changes for your round' },
    ],
  },
  {
    slug: 'batteries-chargers',
    name: 'Batteries & Chargers',
    rawCategory: 'Golf Buggy Batteries & Chargers',
    count: 10,
    h1: 'Golf Buggy Batteries & Chargers in Australia',
    metaTitle: 'Golf Buggy Batteries & Chargers Australia | Buggies Express',
    metaDescription:
      'Golf buggy batteries and chargers in Australia. Lithium conversion kits, drop-in modules, deep cycle lead acid and smart chargers from our Yatala QLD depot.',
    // Split out of the old combined parts category so the battery cluster
    // (~700/mo, KD 5-14) has a canonical target of its own. Every figure below
    // is read off the ten products actually in this category - do not add
    // chemistry or runtime claims that no product on the site supports.
    intro:
      'Golf buggy batteries and chargers for Australian owners, from an $85 voltage reducer to a $4,700 72V commercial lithium pack. Ten power-system items covering lithium conversion kits, drop-in modules, deep cycle lead acid and smart on-board chargers, dispatched from our Yatala QLD depot.',
    sections: [
      {
        heading: 'Lithium vs Lead Acid',
        body: 'We stock both, because the right answer depends on how often the buggy runs. Lead acid is still the cheapest way back on the course - a Trojan T-875 8V deep cycle cell is $340 AUD - but it needs watering and it sags as it discharges. Lithium costs more up front, starting at $1,850 AUD for an Invicta 48V 50Ah drop-in module, and gives you a sealed, maintenance-free pack instead. The comparison guide below sets the two side by side before you commit.',
      },
      {
        heading: '48V Lithium Conversion Kits',
        body: 'Converting an existing lead-acid buggy is the most common upgrade we ship. The Eco Battery 48V 105Ah conversion kit at $3,850 AUD and the RoyPow 48V 105Ah pack at $3,600 AUD both replace a full bank of lead-acid cells, and the Invicta 48V 50Ah module is the lighter drop-in option at $1,850 AUD. Check your existing charger and battery tray dimensions before ordering - the conversion guide below covers what a realistic total cost looks like.',
      },
      {
        heading: 'Chargers and Charging',
        body: 'A lithium pack needs a charger that matches it. The Delta-Q QuiQ 48V smart on-board charger is $680 AUD and the Club Car ERIC 48V high-frequency charger is $590 AUD. For properties without a convenient power point, the 175W solar charging panel expansion kit at $520 AUD supplements mains charging rather than replacing it - the solar guide below is honest about what it will and will not do in Australian conditions.',
      },
      {
        heading: '72V, 24V and Support Components',
        body: 'At the heavy end, the RoyPow 72V 105Ah commercial pack is $4,700 AUD for utility and resort fleets that run all day. At the other, the MGI 24V lithium battery at $450 AUD is the replacement pack for walk-behind trolleys, and the universal 48V/36V to 12V 30A voltage reducer at $85 AUD is what lets accessories such as lights and a soundbar run off the main pack safely.',
      },
    ],
    guides: [
      { slug: 'lithium-vs-lead-acid-golf-buggy-batteries-australia', label: 'Lithium vs lead acid golf buggy batteries' },
      { slug: 'lithium-battery-conversion-guide-cost-australia', label: 'Lithium conversion guide: what it really costs' },
      { slug: 'electric-golf-buggy-range-test-one-charge-australia', label: 'How far a buggy goes on one charge' },
      { slug: 'golf-buggy-winter-storage-battery-care-australia', label: 'Winter storage and battery care' },
      { slug: 'solar-panels-on-golf-buggies-australia-feasibility-guide', label: 'Solar panels on golf buggies: does it stack up?' },
    ],
  },
  {
    slug: 'accessories-spare-parts',
    name: 'Accessories & Spare Parts',
    rawCategory: 'Golf Buggy Accessories & Spare Parts',
    count: 16,
    h1: 'Golf Buggy Accessories & Spare Parts in Australia',
    metaTitle: 'Golf Buggy Accessories & Spare Parts | Buggies Express',
    metaDescription:
      'Golf buggy accessories and spare parts in Australia. Controllers, brake kits, wheels, windshields, lighting, seats and covers shipped from Yatala QLD.',
    // The other half of the old combined category. This cluster is the
    // lowest-KD block on the site (~550/mo, mostly KD 4-10) and most of it is
    // brand-qualified ("ezgo golf cart parts", "yamaha golf buggy parts"), so
    // the copy names the fitments we actually carry and nothing else.
    intro:
      'Golf buggy accessories and spare parts for Australian owners, from a $75 sand bottle set to a $1,450 AC controller upgrade. Sixteen items covering controllers and solenoids, brakes, wheels and tyres, lighting, mirrors, seating, weather protection and storage, dispatched from our Yatala QLD depot.',
    sections: [
      {
        heading: 'Controllers and Electrical Spares',
        body: 'The controller decides how a buggy actually feels to drive. The Curtis 1268 400A programmable motor controller is $890 AUD, and the Navitas 600A AC controller upgrade kit at $1,450 AUD is the bigger step for owners chasing more torque on hills. The Albright 48VDC 200A heavy duty solenoid at $120 AUD is the part most often replaced when a buggy clicks but will not move.',
      },
      {
        heading: 'Lighting, Mirrors and Restraints',
        body: 'The MadJax Alpha Lux LED light kit is $320 AUD, side mirrors with integrated LED indicators are $95 AUD, and a retractable front and rear seatbelt set is $145 AUD. These are the components commonly fitted when owners want a buggy equipped for estate roads - but registration and road-use rules differ in every state and territory, so check your own requirements with the relevant authority before you rely on any of it.',
      },
      {
        heading: 'Wheels, Brakes and Terrain Hardware',
        body: 'For acreage and rough ground, the all-terrain 23x10.5-12 wheel and tyre combo is $850 AUD for a set of four, and the heavy duty 4-wheel hydraulic disc brake kit at $750 AUD is the matching upgrade - more tyre and more speed is worth very little without more brake. A heavy duty tow hitch and ball assembly is $110 AUD for owners towing a trailer or a greens roller.',
      },
      {
        heading: 'Seating, Weather Protection and Storage',
        body: 'The rear flip seat kit at $650 AUD converts a 2-seater into a 4-seater without a new vehicle. For weather, the all-weather heavy-duty PVC enclosure is $290 AUD and the foldable tinted acrylic windshield is $160 AUD. Storage and comfort round it out: a lockable dash glove box at $185 AUD, a 26-inch waterproof marine grade Bluetooth soundbar at $420 AUD, and a dual sand bottle assembly at $75 AUD. Walk-behind owners will also find the replacement MGI Ai and Zip remote controller here at $190 AUD.',
      },
    ],
    guides: [
      { slug: 'must-have-golf-buggy-accessories-and-spares-australia', label: 'Must-have golf buggy accessories and spares' },
      { slug: 'golf-buggy-parts-and-spares-australia-guide', label: 'Golf buggy parts and spares: a buyers guide' },
      { slug: 'electric-golf-buggy-troubleshooting-and-replacement-parts', label: 'Troubleshooting and replacement parts' },
      { slug: 'mgi-golf-buggy-accessories-guide-australia', label: 'MGI accessories and spares guide' },
      { slug: 'golf-buggy-seat-covers-and-upholstery-australia', label: 'Seat covers and upholstery' },
    ],
  },
  {
    slug: 'junior-golf-buggies',
    name: 'Junior Golf Buggies',
    rawCategory: 'Junior Golf Buggies',
    count: 0,
    // No products yet. The page exists so the junior cluster has a home
    // that starts earning before stock lands, and so interest can be
    // registered. CategoryClient swaps the catalogue for a register-interest
    // block; CatalogInterface hides the filter chip (a chip with zero
    // results is a dead end). Remove the flag - and add real products - when
    // the owner confirms the range. NOTHING here may state a date, price,
    // model or specification: none is final, and inventing one breaks the
    // no-fabricated-facts rule.
    comingSoon: true,
    metaTitle: 'Junior & Kids Golf Buggies — Coming Soon | Buggies Express',
    metaDescription:
      'Junior and kids golf buggies are coming to The Buggies Express. Register your interest and we will email you the day the range, photos and pricing go live.',
    h1: 'Junior Golf Buggies in Australia — Coming Soon',
    primaryKeyword: 'junior golf buggy',
    supportingKeywords: [
      'kids golf buggy',
      'kids golf cart',
      'childrens golf buggy',
      'junior golf buggy australia',
      'junior golf carts for sale',
      'junior golf buggies',
    ],
    intro:
      'A junior golf buggy range sized for younger golfers is on its way. We are finalising the models now, and until the buggies, photos and pricing are confirmed nothing on this page is for sale. Register your interest below and you will hear from us the day it lands, dispatched as always from our Yatala QLD depot.',
    sections: [
      {
        heading: 'What Makes a Golf Buggy Junior-Sized',
        body: 'A kids golf buggy is not simply a smaller adult one. The details that matter are a handle or seat height a younger golfer can use without reaching, a frame light enough for them to load themselves, and controls that are simple and predictable. Those are the criteria we are holding the range to, and we will publish the exact specification for every model rather than describe it loosely.',
      },
      {
        heading: 'What We Will and Will Not Say Yet',
        body: 'We have not announced a launch date, a price or a model list, because none of them is final. Every product on this site carries specifications we have checked at our Yatala QLD depot, and the junior range will be no different. When the buggies arrive you will see photographs of the actual units, GST-inclusive pricing and a full specification for each - not a rendering and a promise.',
      },
      {
        heading: 'In the Meantime: Our Current Range',
        body: 'Our walk-behind electric trolleys are built for adult golfers, so we will not claim any of them is a junior model. Whether one suits a taller teenager comes down to handle height and bag weight, and that is a conversation worth having with us rather than a guess. The junior buying guide below covers what to measure before you decide.',
      },
      {
        heading: 'Register Your Interest',
        body: 'Leave your name, email and postcode and we will let you know as soon as the range is live. Like everything we sell, junior golf buggies will ship Australia-wide in enclosed freight, with the cost quoted against your delivery postcode rather than added later.',
      },
    ],
    guides: [
      { slug: 'junior-golf-buggy-australia-guide', label: 'Junior golf buggy guide: sizing, safety and what to look for' },
      { slug: 'foldable-golf-buggy-buyers-guide-boot-space-weight', label: 'Foldable buggies: boot space and weight' },
      { slug: 'motorised-vs-push-golf-buggy-health-stamina-benefits', label: 'Motorised vs push: what it changes for a round' },
      { slug: 'best-push-golf-buggy-australia-3-wheel-vs-4-wheel-review', label: 'Three-wheel vs four-wheel push buggies' },
    ],
    faqs: [
      {
        q: 'When will the junior golf buggies be available?',
        a: 'We have not set a date, and we will not guess at one. The range is being finalised now. Register your interest on this page and we will email you as soon as the junior golf buggies, their photos and their pricing are live.',
      },
      {
        q: 'What is a junior golf buggy?',
        a: 'A golf buggy sized for a younger golfer: a lower handle or seat height they can use comfortably, a lighter frame they can load into a car themselves, and simple controls. A kids golf buggy that is just a shrunken adult model usually gets the handle height wrong, and that is the dimension that matters most.',
      },
      {
        q: 'Will you publish prices and specifications before launch?',
        a: 'No - only once they are final. Every product on this site carries specifications checked at our Yatala QLD depot and a GST-inclusive price, and the junior range will be listed the same way rather than with estimates.',
      },
      {
        q: 'Can a junior use one of your current electric golf trolleys?',
        a: 'Our walk-behind range is built for adult golfers, so we will not describe any of it as a junior model. Whether one suits a taller teenager depends on handle height and bag weight. Call or message us with their height and the bag they use and we will give you a straight answer.',
      },
      {
        q: 'Will junior golf buggies be delivered Australia-wide?',
        a: 'Yes. Junior golf buggies will ship the same way as everything else we sell: enclosed freight to every state and territory from Yatala QLD, with the freight cost quoted against your delivery postcode rather than added as a surprise later.',
      },
      {
        q: 'How do I register my interest in the junior range?',
        a: 'Use the form on this page with your name, email and postcode. You can also email or WhatsApp us using the contact details in the footer. We will contact you once the junior golf buggies are available to order.',
      },
    ],
  },
];

export const PRODUCTS: ProductItem[] = [
  {
    id: 'BUG-001',
    slug: 'atlas-4-passenger-lifted-lithium-buggy',
    name: 'Atlas 4-Passenger Lifted Lithium Buggy',
    category: 'Luxury & High-Demand 4-Seaters',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 20900,
    price_display: '$20,900 AUD',
    search_intent: 'Transactional / Commercial',
    target_audience: 'Gated estates, luxury property owners, resort operators',
    key_specs: '48V Lithium, 3-inch Factory Lift, Custom Leather Seats, Touchscreen Display, 14-inch Alloy Wheels',
    shortDescription: 'The pinnacle of luxury acreage mobility with 3-inch factory lift, high-density 48V lithium battery, and premium 4-passenger leather seating.',
    badge: 'Flagship Model',
    featured: true,
    images: ['/images/atlas-4-passenger-lifted-lithium-buggy.webp'],
    inStock: true,
  },
  {
    id: 'BUG-002',
    slug: 'evolution-d5-ranger-4-plus-2',
    name: 'Evolution D5 Ranger 4+2 Plus',
    category: 'Luxury & High-Demand 4-Seaters',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 22500,
    price_display: '$22,500 AUD',
    search_intent: 'Transactional',
    target_audience: 'High net-worth families, lifestyle acreage owners',
    key_specs: '110Ah Lithium, Soundbar with Bluetooth, 9-inch Touchscreen, Foldable Windshield, Forward Facing Seats',
    shortDescription: 'Modern luxury 6-passenger cruiser equipped with a 110Ah lithium battery, marine Bluetooth soundbar, and multi-functional 9-inch touch screen.',
    badge: 'Popular Family',
    featured: true,
    images: ['/images/evolution-d5-ranger-4-plus-2.webp'],
    inStock: true,
  },
  {
    id: 'BUG-003',
    slug: 'club-car-onward-4-passenger-lithium',
    name: 'Club Car Onward 4-Passenger Lithium',
    category: 'Luxury & High-Demand 4-Seaters',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 24500,
    price_display: '$24,500 AUD',
    search_intent: 'Brand Direct / High-Intent',
    target_audience: 'Club Car brand loyalists, premium golf village residents',
    key_specs: 'AC Drive Motor, Custom Metallic Paint, Premium Canopy Top, Ergonomic Seating, Aircraft-Grade Aluminum Frame',
    shortDescription: 'Industry gold standard featuring rust-proof aircraft-grade aluminum chassis, high-efficiency AC drive motor, and custom metallic coachwork.',
    badge: 'Heritage Elite',
    featured: true,
    images: ['/images/club-car-onward-4-passenger-lithium.webp'],
    inStock: true,
  },
  {
    id: 'BUG-004',
    slug: 'tara-roadster-2-plus-2-lifted',
    name: 'Tara Roadster 2+2 Lifted',
    category: 'Luxury & High-Demand 4-Seaters',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 18990,
    price_display: '$18,990 AUD',
    search_intent: 'Commercial',
    target_audience: 'Budget-luxury buyers, semi-rural properties',
    key_specs: 'Lithium Battery, Lifted Chassis, Hydraulic Disc Brakes, LED Light Package, Rear Flip Seat',
    shortDescription: 'High-value lifted lithium buggy with automotive hydraulic disc brakes, full LED package, and convertible flatbed rear seat.',
    badge: 'Value Pick',
    featured: false,
    images: ['/images/tara-roadster-2-plus-2-lifted.webp'],
    inStock: true,
  },
  {
    id: 'BUG-005',
    slug: 'ezgo-express-l6-lithium',
    name: 'E-Z-GO Express L6 Lithium',
    category: 'Luxury & High-Demand 4-Seaters',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 27900,
    price_display: '$27,900 AUD',
    search_intent: 'High-Ticket Transactional',
    target_audience: 'Resort transport, large family estates, commercial venues',
    key_specs: 'ELiTE Lithium Technology, 6-Passenger Seating, High Ground Clearance, Heavy Duty Suspension',
    shortDescription: '6-passenger luxury transporter powered by Samsung SDI ELiTE Lithium batteries and heavy-duty reinforced off-road suspension.',
    badge: '6-Seater Transporter',
    featured: true,
    images: ['/images/ezgo-express-l6-lithium.webp'],
    inStock: true,
  },
  {
    id: 'BUG-006',
    slug: 'lvtong-4-seater-resort-cruiser',
    name: 'LVTONG 4-Seater Resort Cruiser',
    category: 'Luxury & High-Demand 4-Seaters',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 16800,
    price_display: '$16,800 AUD',
    search_intent: 'Commercial',
    target_audience: 'Hotels, holiday parks, community centers',
    key_specs: '4kW AC Motor, Maintenance-Free Lithium, On-Board Charger, Heavy Duty Bumper',
    shortDescription: 'Dependable commercial 4-seater buggy with high-torque 4kW AC motor, integrated smart charger, and rugged bumper protection.',
    badge: 'Resort Fleet',
    featured: false,
    images: ['/images/lvtong-4-seater-resort-cruiser.webp'],
    inStock: true,
  },
  {
    id: 'BUG-007',
    slug: 'club-car-tempo-lithium-2025',
    name: 'Club Car Tempo Lithium (2025 Model)',
    category: 'Traditional 2-Seater Electric Golf Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 16990,
    price_display: '$16,990 AUD',
    search_intent: 'Brand Direct / Transactional',
    target_audience: 'Avid golfers, private course members',
    key_specs: 'Monaco Drive System, Rust-Proof Aluminum Frame, Automotive-Style Dashboard',
    shortDescription: 'The latest 2025 Club Car Tempo 2-seater with maintenance-free lithium battery and iconic rustproof aluminum frame.',
    badge: '2025 Model',
    featured: true,
    images: ['/images/club-car-tempo-lithium-2025.webp'],
    inStock: true,
  },
  {
    id: 'BUG-008',
    slug: 'ezgo-rxv-elite-lithium',
    name: 'E-Z-GO RXV ELiTE Lithium',
    category: 'Traditional 2-Seater Electric Golf Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 15800,
    price_display: '$15,800 AUD',
    search_intent: 'High Traffic / Commercial',
    target_audience: 'Golfers, fleet buyers, retirement village residents',
    key_specs: 'Samsung SDI Lithium Batteries, Automatic Electromagnetic Brake, High-Efficiency AC Drive',
    shortDescription: 'Famous automatic auto-park electromagnetic braking system paired with Samsung SDI maintenance-free lithium battery power.',
    badge: 'Auto-Park Brake',
    featured: true,
    images: ['/images/ezgo-rxv-elite-lithium.webp', '/images/ezgo-rxv-elite-lithium-2.webp'],
    inStock: true,
  },
  {
    id: 'BUG-009',
    slug: 'yamaha-drive2-ac-lithium',
    name: 'Yamaha Drive2 AC Lithium',
    category: 'Traditional 2-Seater Electric Golf Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 16500,
    price_display: '$16,500 AUD',
    search_intent: 'Commercial',
    target_audience: 'Golfers wanting smooth ride comfort, course fleets',
    key_specs: 'Independent Front & Rear Suspension, Ultra-Comfort Seats, Wide Dash Storage',
    shortDescription: 'Unrivaled ride comfort with Yamaha four-wheel independent suspension and wide contoured comfort seating.',
    badge: 'Ultra-Comfort',
    featured: false,
    images: ['/images/yamaha-drive2-ac-lithium.webp'],
    inStock: true,
  },
  {
    id: 'BUG-010',
    slug: 'tara-spirit-pro-2-seater',
    name: 'Tara Spirit Pro 2-Seater',
    category: 'Traditional 2-Seater Electric Golf Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 13500,
    price_display: '$13,500 AUD',
    search_intent: 'Transactional / Value',
    target_audience: 'Cost-conscious private golfers',
    key_specs: 'Lightweight Frame, Rapid Charger, Digital Speedometer, Sweater Basket',
    shortDescription: 'Modern, cost-effective 2-passenger electric buggy with rapid charging capability and clear digital dashboard instrumentation.',
    badge: 'Great Value',
    featured: false,
    images: ['/images/tara-spirit-pro-2-seater.webp', '/images/tara-spirit-pro-2-seater-2.webp'],
    inStock: true,
  },
  {
    id: 'BUG-011',
    slug: 'lvtong-2-passenger-golf-buggy',
    name: 'LVTONG 2-Passenger Golf Buggy',
    category: 'Traditional 2-Seater Electric Golf Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 11990,
    price_display: '$11,990 AUD',
    search_intent: 'Value / Commercial',
    target_audience: 'Budget private buyers, local golf clubs',
    key_specs: '48V System, Split Foldable Windshield, Dual Sand Bottles, Caddy Bag Holder',
    shortDescription: 'Fully loaded course-ready 2-seater with split windshield, dual divot repair sand bottles, and rear bag brackets.',
    badge: 'Course Ready',
    featured: false,
    images: ['/images/lvtong-2-passenger-golf-buggy.webp'],
    inStock: true,
  },
  {
    id: 'BUG-012',
    slug: 'evolution-classic-2-plus',
    name: 'Evolution Classic 2 Plus',
    category: 'Traditional 2-Seater Electric Golf Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 14200,
    price_display: '$14,200 AUD',
    search_intent: 'Transactional',
    target_audience: 'Modern tech-focused golfers',
    key_specs: '6.3-inch LCD Screen, Lithium-Ion Battery, Two-Tone Seats, Side Mirrors with Turn Signals',
    shortDescription: 'Feature-packed 2-seater buggy with automotive LCD instrument cluster, integrated mirrors, and two-tone luxury upholstery.',
    badge: 'Tech Spec',
    featured: false,
    images: ['/images/evolution-classic-2-plus.webp'],
    inStock: true,
  },
  {
    id: 'BUG-013',
    slug: 'atlas-4-seater-heavy-duty-lifted-350a',
    name: 'Atlas 4-Seater Heavy Duty Lifted (350A)',
    category: 'Off-Road, Lifted & 4x4 Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 21990,
    price_display: '$21,990 AUD',
    search_intent: 'Commercial / High-Torque',
    target_audience: 'Acreage owners, hilly farm tracks, rural properties',
    key_specs: '350A Controller, 4-wheel Hydraulic Brakes, Rugged All-Terrain Tires, Brush Guard',
    shortDescription: 'High-torque 350-amp power controller with 4-wheel hydraulic disc brakes and steel brush guard for steep Australian hills.',
    badge: 'High-Torque 350A',
    featured: true,
    images: ['/images/atlas-4-seater-heavy-duty-lifted-350a.webp'],
    inStock: true,
  },
  {
    id: 'BUG-014',
    slug: 'evolution-d-max-gt4-off-road',
    name: 'Evolution D-MAX GT4 Off-Road',
    category: 'Off-Road, Lifted & 4x4 Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 23800,
    price_display: '$23,800 AUD',
    search_intent: 'High-Ticket Off-Road',
    target_audience: 'Hunters, large property managers, trail enthusiasts',
    key_specs: 'Heavy Duty Roll Cage, Independent Off-Road Suspension, Integrated Winch, High-Power AC Engine',
    shortDescription: 'Aggressive trail buggy with full roll cage, heavy-duty recovery winch, and long-travel independent suspension.',
    badge: 'Trail Edition',
    featured: true,
    images: ['/images/evolution-d-max-gt4-off-road.webp'],
    inStock: true,
  },
  {
    id: 'BUG-015',
    slug: 'ezgo-express-s4-lifted-high-torque',
    name: 'E-Z-GO Express S4 Lifted High-Torque',
    category: 'Off-Road, Lifted & 4x4 Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 20500,
    price_display: '$20,500 AUD',
    search_intent: 'Transactional',
    target_audience: 'Rural families, farm transport',
    key_specs: '4-inch Lift Kit, Desert Eagle All-Terrain Tires, Convertible Rear Seat to Cargo Bed',
    shortDescription: '4-inch factory lifted chassis riding on Desert Eagle all-terrain tyres with flip-over flatbed utility platform.',
    badge: 'Dual Purpose',
    featured: false,
    images: ['/images/ezgo-express-s4-lifted-high-torque.webp'],
    inStock: true,
  },
  {
    id: 'BUG-016',
    slug: 'lvtong-rough-terrain-lifted-buggy',
    name: 'LVTONG Rough-Terrain Lifted Buggy',
    category: 'Off-Road, Lifted & 4x4 Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 17500,
    price_display: '$17,500 AUD',
    search_intent: 'Value Commercial',
    target_audience: 'Farmers, orchard owners, bush properties',
    key_specs: 'High Ground Clearance, Reinforced Steel Subframe, Front LED Light Bar',
    shortDescription: 'Rugged high ground clearance buggy reinforced with steel front bash guard and high-intensity night LED light bar.',
    badge: 'Farm Ready',
    featured: false,
    images: ['/images/lvtong-rough-terrain-lifted-buggy.webp'],
    inStock: true,
  },
  {
    id: 'BUG-017',
    slug: 'club-car-onward-lifted-efi-petrol',
    name: 'Club Car Onward Lifted EFI Petrol',
    category: 'Off-Road, Lifted & 4x4 Buggies',
    fuel_type: 'Mechanical (Petrol EFI)',
    price_aud: 19800,
    price_display: '$19,800 AUD',
    search_intent: 'Rural Long Range',
    target_audience: 'Buyers without grid power access, long-distance farm users',
    key_specs: 'Kohler 14HP EFI Petrol Engine, Lifted Suspension, All-Terrain Tread',
    shortDescription: 'Electronic Fuel Injection (EFI) petrol engine delivering infinite remote range without battery charging reliance.',
    badge: 'Petrol Range',
    featured: false,
    images: ['/images/club-car-onward-lifted-efi-petrol.webp'],
    inStock: true,
  },
  {
    id: 'BUG-018',
    slug: 'tara-roadster-4-off-road',
    name: 'Tara Roadster 4 Off-Road',
    category: 'Off-Road, Lifted & 4x4 Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 19500,
    price_display: '$19,500 AUD',
    search_intent: 'Transactional',
    target_audience: 'Property owners needing steep incline power',
    key_specs: 'High-Torque Gear Ratio, 12-inch Off-Road Rims, Rear Cargo Tray Option',
    shortDescription: 'High-torque gear reduction transmission designed specifically for heavy incline climbing and rugged acreage trails.',
    badge: 'Hill Climber',
    featured: false,
    images: ['/images/tara-roadster-4-off-road.webp'],
    inStock: true,
  },
  {
    id: 'BUG-019',
    slug: 'club-car-carryall-700-electric-utility',
    name: 'Club Car Carryall 700 Electric Utility',
    category: 'Commercial & Farm Utility Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 22900,
    price_display: '$22,900 AUD',
    search_intent: 'Commercial / B2B',
    target_audience: 'Councils, maintenance teams, commercial farms',
    key_specs: '6-Foot Aluminum Cargo Box, 680kg Payload Capacity, Heavy-Duty Tow Hitch',
    shortDescription: 'Heavy-duty 6-foot aluminum cargo bed boasting an immense 680kg payload and integrated industrial tow hitch.',
    badge: '680kg Payload',
    featured: true,
    images: ['/images/club-car-carryall-700-electric-utility.webp'],
    inStock: true,
  },
  {
    id: 'BUG-020',
    slug: 'ezgo-cushman-hauler-pro-lithium',
    name: 'E-Z-GO Cushman Hauler PRO Lithium',
    category: 'Commercial & Farm Utility Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 21500,
    price_display: '$21,500 AUD',
    search_intent: 'Commercial / Industrial',
    target_audience: 'Turf managers, schools, university campuses',
    key_specs: '72V AC Drive, Electric Cargo Bed Dump Option, 544kg Towing Capacity',
    shortDescription: 'High-voltage 72V commercial AC drive system with optional electric hydraulic tilt bed dump and 544kg tow capacity.',
    badge: '72V Commercial',
    featured: true,
    images: ['/images/ezgo-cushman-hauler-pro-lithium.webp'],
    inStock: true,
  },
  {
    id: 'BUG-021',
    slug: 'yamaha-umax-rally-efi-petrol',
    name: 'Yamaha UMAX Rally EFI Petrol',
    category: 'Commercial & Farm Utility Buggies',
    fuel_type: 'Mechanical (Petrol EFI)',
    price_aud: 18900,
    price_display: '$18,900 AUD',
    search_intent: 'Commercial / Farm',
    target_audience: 'Livestock properties, large regional venues',
    key_specs: '402cc Yamaha EFI Engine, Side-Filling Fuel Tank, Bucket Seats, Under-Hood Storage',
    shortDescription: 'Heavy-duty 402cc Yamaha EFI commercial workhorse with huge under-hood dry storage and side fuel filler.',
    badge: 'Heavy Farm Spec',
    featured: false,
    images: ['/images/yamaha-umax-rally-efi-petrol.webp'],
    inStock: true,
  },
  {
    id: 'BUG-022',
    slug: 'evolution-700-heavy-commercial-utility',
    name: 'Evolution 700 Heavy Commercial Utility',
    category: 'Commercial & Farm Utility Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 19200,
    price_display: '$19,200 AUD',
    search_intent: 'Commercial',
    target_audience: 'Facility management, security patrols',
    key_specs: 'Drop-Side Flatbed Tray, Lithium-Ion, High-Output Headlights, Tow Bar',
    shortDescription: 'Industrial drop-side flatbed carrying tray with lithium-ion power and automotive front headlights.',
    badge: 'Drop-Side Tray',
    featured: false,
    images: ['/images/evolution-700-heavy-commercial-utility.webp', '/images/evolution-700-heavy-commercial-utility-2.webp'],
    inStock: true,
  },
  {
    id: 'BUG-023',
    slug: 'lvtong-commercial-flatbed-cargo-buggy',
    name: 'LVTONG Commercial Flatbed / Cargo Buggy',
    category: 'Commercial & Farm Utility Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 15900,
    price_display: '$15,900 AUD',
    search_intent: 'Value B2B',
    target_audience: 'Warehouses, nurseries, eco-resort groundskeepers',
    key_specs: 'Steel Mesh Flatbed, Low Loader Height, Regenerative Braking',
    shortDescription: 'Low-loading steel deck cargo carrier with intelligent regenerative braking for safe warehouse and estate transit.',
    badge: 'Low Loader Deck',
    featured: false,
    images: ['/images/lvtong-commercial-flatbed-cargo-buggy.webp'],
    inStock: true,
  },
  {
    id: 'BUG-024',
    slug: 'club-car-transporter-6-commercial',
    name: 'Club Car Transporter 6 Commercial',
    category: 'Commercial & Farm Utility Buggies',
    fuel_type: 'Electric (Lithium-Ion)',
    price_aud: 26400,
    price_display: '$26,400 AUD',
    search_intent: 'High-Ticket B2B',
    target_audience: 'Airports, mines, large resort guest shuttles',
    key_specs: '6-Passenger Forward-Facing Seating, Armor-Flex Body, Heavy-Duty Axles',
    shortDescription: 'Premium 6-passenger forward-facing shuttle featuring dent-resistant ArmorFlex bodywork and reinforced commercial axles.',
    badge: '6-Passenger VIP',
    featured: true,
    images: ['/images/club-car-transporter-6-commercial.webp'],
    inStock: true,
  },
  {
    id: 'BUG-025',
    slug: 'yamaha-drive2-quiettech-efi-petrol',
    name: 'Yamaha Drive2 QuietTech EFI Petrol',
    category: 'Mechanical & Petrol Buggies',
    fuel_type: 'Mechanical (Petrol EFI)',
    price_aud: 14800,
    price_display: '$14,800 AUD',
    search_intent: 'Commercial / Quiet Petrol',
    target_audience: 'Golfers and property owners wanting petrol range without noise',
    key_specs: 'Quietest Petrol Engine on the Market, Fully Independent Rear Suspension, High MPG',
    shortDescription: 'Patented QuietTech engineering creates the quietest petrol golf cart on earth—sounds like electric with unlimited petrol range.',
    badge: 'Quietest Petrol',
    featured: true,
    images: ['/images/yamaha-drive2-quiettech-efi-petrol.webp'],
    inStock: true,
  },
  {
    id: 'BUG-026',
    slug: 'club-car-tempo-efi-petrol',
    name: 'Club Car Tempo EFI Petrol',
    category: 'Mechanical & Petrol Buggies',
    fuel_type: 'Mechanical (Petrol EFI)',
    price_aud: 14250,
    price_display: '$14,250 AUD',
    search_intent: 'Brand Direct / Petrol',
    target_audience: 'Traditional rural users, remote property caretakers',
    key_specs: '14HP Single Cylinder Engine, Overhead Cam, Tank Capacity 25.4L',
    shortDescription: '14HP overhead-cam petrol engine backed by a generous 25.4-litre fuel tank for long weeks between refills.',
    badge: '25.4L Fuel Tank',
    featured: false,
    images: ['/images/club-car-tempo-efi-petrol.webp'],
    inStock: true,
  },
  {
    id: 'BUG-027',
    slug: 'ezgo-freedom-rxv-gas',
    name: 'E-Z-GO Freedom RXV Gas',
    category: 'Mechanical & Petrol Buggies',
    fuel_type: 'Mechanical (Petrol)',
    price_aud: 13900,
    price_display: '$13,900 AUD',
    search_intent: 'Transactional',
    target_audience: 'Farmers, acreage owners',
    key_specs: 'EX1 Closed-Loop EFI Petrol Engine, Low Maintenance, Energy Efficient',
    shortDescription: 'Purpose-built EX1 closed-loop petrol engine engineered specifically to reduce oil changes and maintenance intervals.',
    badge: 'Low Maintenance Gas',
    featured: false,
    images: ['/images/ezgo-freedom-rxv-gas.webp'],
    inStock: true,
  },
  {
    id: 'BUG-028',
    slug: 'cushman-hauler-1200-gas-utility',
    name: 'Cushman Hauler 1200 Gas Utility',
    category: 'Mechanical & Petrol Buggies',
    fuel_type: 'Mechanical (Petrol)',
    price_aud: 16800,
    price_display: '$16,800 AUD',
    search_intent: 'Commercial Utility',
    target_audience: 'Heavy agricultural property work',
    key_specs: '13.5HP Kawasaki Engine, Manual Dump Bed, 544kg Total Load Capacity',
    shortDescription: 'Bulletproof 13.5HP Kawasaki petrol engine with heavy-duty manual dump bed and 544kg carrying capacity.',
    badge: 'Kawasaki Powered',
    featured: false,
    images: ['/images/cushman-hauler-1200-gas-utility.webp'],
    inStock: true,
  },
  {
    id: 'BUG-029',
    slug: 'yamaha-umax-one-efi-utility',
    name: 'Yamaha UMAX One EFI Utility',
    category: 'Mechanical & Petrol Buggies',
    fuel_type: 'Mechanical (Petrol EFI)',
    price_aud: 15500,
    price_display: '$15,500 AUD',
    search_intent: 'Commercial / Farm',
    target_audience: 'Small farms, lifestyle blocks, sport venues',
    key_specs: 'Compact Utility Bed, One-Hand Latch System, High Comfort Bucket Seats',
    shortDescription: 'Compact yet capable EFI utility buggy with single-handed tailgate latch and wide contoured bucket seats.',
    badge: 'Compact Utility',
    featured: false,
    images: ['/images/yamaha-umax-one-efi-utility.webp'],
    inStock: true,
  },
  {
    id: 'BUG-030',
    slug: 'club-car-carryall-300-petrol',
    name: 'Club Car Carryall 300 Petrol',
    category: 'Mechanical & Petrol Buggies',
    fuel_type: 'Mechanical (Petrol EFI)',
    price_aud: 16200,
    price_display: '$16,200 AUD',
    search_intent: 'Commercial',
    target_audience: 'Light commercial, school groundskeeping',
    key_specs: 'Rustproof Aircraft Grade Aluminum Frame, 14HP Engine, Compact Turning Radius',
    shortDescription: 'Agile utility buggy featuring tight turning circle and rustproof aluminum bed for schools and grounds teams.',
    badge: 'Tight Radius Work',
    featured: false,
    images: ['/images/club-car-carryall-300-petrol.webp'],
    inStock: true,
  },
  {
    id: 'BUG-031',
    slug: 'mgi-ai-navigator-gps-remote-buggy',
    name: 'MGI Ai Navigator GPS Remote Buggy',
    category: 'Motorised Walk-Behind Golf Buggies',
    fuel_type: 'Electric (Walk-Behind Lithium)',
    price_aud: 2849,
    price_display: '$2,849 AUD',
    search_intent: 'High Volume Consumer (#1 Seller)',
    target_audience: 'Private golfers walking the course',
    key_specs: 'Full Directional Remote, Integrated Touchscreen GPS, Gyroscope Straight Tracker',
    shortDescription: "Australia's #1 motorized remote buggy with integrated high-resolution touchscreen GPS and Patented Gyroscope Straight Tracker.",
    badge: 'Australia #1 Seller',
    featured: true,
    images: ['/images/mgi-ai-navigator-gps-remote-buggy.webp'],
    inStock: true,
  },
  {
    id: 'BUG-032',
    slug: 'mgi-zip-navigator-all-terrain',
    name: 'MGI Zip Navigator All-Terrain',
    category: 'Motorised Walk-Behind Golf Buggies',
    fuel_type: 'Electric (Walk-Behind Lithium)',
    price_aud: 2209,
    price_display: '$2,209 AUD',
    search_intent: 'High Volume Consumer',
    target_audience: 'Walk-behind golfers wanting all-terrain stability',
    key_specs: 'Twin 230W Motors, 24V 380Wh Lithium Battery, Rear Anti-Tip 5th Wheel',
    shortDescription: 'Dual calibrated 230W motors with rear fold-out 5th wheel for zero tipping on steep fairway contours.',
    badge: 'Twin 230W Motors',
    featured: true,
    images: ['/images/mgi-zip-navigator-all-terrain.webp'],
    inStock: true,
  },
  {
    id: 'BUG-033',
    slug: 'mgi-2024-zip-x5-36-hole-lithium',
    name: 'MGI 2024 Zip X5 36-Hole Lithium',
    category: 'Motorised Walk-Behind Golf Buggies',
    fuel_type: 'Electric (Walk-Behind Lithium)',
    price_aud: 1875,
    price_display: '$1,875 AUD',
    search_intent: 'Transactional',
    target_audience: 'Golfers playing long 36-hole days',
    key_specs: 'Downhill Speed Control, Electronic Park Brake, Distance Control Function',
    shortDescription: 'Downhill speed control keeps a steady walking pace downhill automatically, with 36-hole extended lithium battery.',
    badge: 'Downhill Speed Control',
    featured: false,
    images: ['/images/mgi-2024-zip-x5-36-hole-lithium.webp'],
    inStock: true,
  },
  {
    id: 'BUG-034',
    slug: 'powakaddy-fx7-gps-lithium',
    name: 'PowaKaddy FX7 GPS Lithium',
    category: 'Motorised Walk-Behind Golf Buggies',
    fuel_type: 'Electric (Walk-Behind Lithium)',
    price_aud: 2099,
    price_display: '$2,099 AUD',
    search_intent: 'Brand Direct / High-End',
    target_audience: 'Tech-savvy golfers seeking UK engineering',
    key_specs: '3.5-inch OCA Full Color Touch Screen, High-Power 30V Plug n Play Lithium',
    shortDescription: 'Brilliant 3.5-inch full colour touchscreen pre-loaded with over 40,000 worldwide golf courses and 30V lithium system.',
    badge: '3.5" GPS Screen',
    featured: false,
    images: ['/images/powakaddy-fx7-gps-lithium.webp'],
    inStock: true,
  },
  {
    id: 'BUG-035',
    slug: 'robera-pro-follow-remote-golf-buggy',
    name: 'Robera Pro Follow Remote Golf Buggy',
    category: 'Motorised Walk-Behind Golf Buggies',
    fuel_type: 'Electric (Walk-Behind Lithium)',
    price_aud: 2799,
    price_display: '$2,799 AUD',
    search_intent: 'High-End Niche',
    target_audience: 'Premium walk-behind buyers seeking hands-free tech',
    key_specs: 'Smart Follow Tracking Tag, Remote Control Dual-Mode, All-Terrain Dual Motors',
    shortDescription: 'Hands-free automatic smart follow technology—clips to your belt and tracks your footsteps at a safe distance.',
    badge: 'Smart Follow Mode',
    featured: true,
    images: ['/images/robera-pro-follow-remote-golf-buggy.webp'],
    inStock: true,
  },
  {
    id: 'BUG-036',
    slug: 'mgi-zip-x1-lithium-buggy',
    name: 'MGI Zip X1 Lithium Buggy',
    category: 'Motorised Walk-Behind Golf Buggies',
    fuel_type: 'Electric (Walk-Behind Lithium)',
    price_aud: 1299,
    price_display: '$1,299 AUD',
    search_intent: 'Entry Level High Volume',
    target_audience: 'First-time motorised buggy buyers',
    key_specs: 'Simple Speed Dial, Click & Go Lithium System, Compact Fold Mechanism',
    shortDescription: 'The most popular entry-level motorized walking buggy in Australia with smooth variable speed dial and fast fold chassis.',
    badge: 'Best Entry Electric',
    featured: false,
    images: ['/images/mgi-zip-x1-lithium-buggy.webp'],
    inStock: true,
  },
  // 26 parts & accessories: 10 batteries/chargers, 16 accessories/spares
  {
    id: 'PART-001',
    slug: 'eco-battery-48v-105ah-lithium-conversion-kit',
    name: 'Eco Battery 48V 105Ah Lithium Conversion Kit',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Battery Part',
    price_aud: 3850,
    price_display: '$3,850 AUD',
    search_intent: 'High-Margin Replacement',
    target_audience: 'Golf cart owners upgrading from lead-acid to lithium',
    key_specs: 'Includes CAN-bus Charger, Digital Gauge, Mounting Bracket, Universal Harness',
    shortDescription: 'Complete drop-in lithium upgrade kit that eliminates 140kg of toxic lead-acid weight with an 8-year warranty.',
    badge: 'Complete Kit',
    featured: true,
    images: ['/images/eco-battery-48v-105ah-lithium-conversion-kit.webp'],
    inStock: true,
  },
  {
    id: 'PART-002',
    slug: 'roypow-48v-105ah-lithium-battery-pack',
    name: 'RoyPow 48V 105Ah Golf Cart Lithium Battery Pack',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Battery Part',
    price_aud: 3600,
    price_display: '$3,600 AUD',
    search_intent: 'High Search Volume',
    target_audience: 'Club Car Precedent / EZGO RXV owners',
    key_specs: 'Drop-In Replacement, Built-in BMS, 5-Year Warranty, Thermal Protection',
    shortDescription: 'Automotive-grade LiFePO4 cells with smart Bluetooth BMS and integrated thermal freeze-prevention circuitry.',
    badge: 'LiFePO4 Grade',
    featured: false,
    images: ['/images/roypow-48v-105ah-lithium-battery-pack.webp'],
    inStock: true,
  },
  {
    id: 'PART-026',
    slug: 'roypow-72v-105ah-commercial-lithium-battery',
    name: 'RoyPow 72V 105Ah Commercial Lithium Battery Pack',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Battery Part',
    price_aud: 4700,
    price_display: '$4,700 AUD',
    search_intent: 'Commercial',
    target_audience: 'Resort fleets, security patrols and grounds teams running 72V vehicles',
    key_specs: '72V 105Ah, Drop-In Replacement, Built-in BMS, 5-Year Warranty, Thermal Protection',
    shortDescription: 'Commercial-duty 72V LiFePO4 pack with smart BMS and thermal protection, sized for full-shift resort and grounds work.',
    badge: '72V Commercial',
    featured: false,
    images: ['/images/roypow-72v-105ah-commercial-lithium-battery.webp'],
    inStock: true,
  },
  {
    id: 'PART-003',
    slug: 'invicta-48v-50ah-lithium-drop-in-module',
    name: 'Invicta 48V 50Ah Lithium Drop-in Module',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Battery Part',
    price_aud: 1850,
    price_display: '$1,850 AUD',
    search_intent: 'Transactional',
    target_audience: 'Compact or light-duty cart owners',
    key_specs: 'Parallel Expansion Capable, Integrated Bluetooth Monitoring',
    shortDescription: 'Compact modular lithium module allowing parallel linking for custom capacity expansions on light vehicles.',
    badge: 'Bluetooth BMS',
    featured: false,
    images: ['/images/invicta-48v-50ah-lithium-drop-in-module.webp'],
    inStock: true,
  },
  {
    id: 'PART-004',
    slug: 'trojan-t-875-8v-deep-cycle-lead-acid-battery',
    name: 'Trojan T-875 8V Deep Cycle Lead Acid Battery',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Battery Part',
    price_aud: 340,
    price_display: '$340 AUD',
    search_intent: 'High Volume Replacements',
    target_audience: 'Fleet operators, standard golf carts',
    key_specs: '8V Deep Cycle, T2 Technology, High Capacity Grid Design',
    shortDescription: 'Genuine Trojan T-875 8-volt deep cycle battery engineered with Alpha Plus paste formulation for maximum fleet cycles.',
    badge: 'Genuine Trojan',
    featured: false,
    images: ['/images/trojan-t-875-8v-deep-cycle-lead-acid-battery.webp'],
    inStock: true,
  },
  {
    id: 'PART-005',
    slug: 'delta-q-quiq-48v-smart-on-board-charger',
    name: 'Delta-Q QuiQ 48V Smart On-Board Charger',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Charger Part',
    price_aud: 680,
    price_display: '$680 AUD',
    search_intent: 'High Intent Repair',
    target_audience: 'E-Z-GO RXV / TXT owners needing charger replacement',
    key_specs: 'Multi-Profile Charging Algorithms, Weatherproof Sealed Enclosure',
    shortDescription: 'IP66 sealed weatherproof on-board charger featuring pre-loaded multi-profile charging algorithms for all battery chemistries.',
    badge: 'IP66 Sealed',
    featured: false,
    images: ['/images/delta-q-quiq-48v-smart-on-board-charger.webp'],
    inStock: true,
  },
  {
    id: 'PART-006',
    slug: 'club-car-eric-48v-high-frequency-charger',
    name: 'Club Car ERIC 48V High-Frequency Charger',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Charger Part',
    price_aud: 590,
    price_display: '$590 AUD',
    search_intent: 'Brand Replacement',
    target_audience: 'Club Car Precedent & Tempo owners',
    key_specs: 'Automatic Voltage Compensation, Global AC Input Compatibility',
    shortDescription: 'OEM high-frequency intelligent battery charger with automatic voltage compensation and lightweight footprint.',
    badge: 'OEM Club Car',
    featured: false,
    images: ['/images/club-car-eric-48v-high-frequency-charger.webp'],
    inStock: true,
  },
  {
    id: 'PART-007',
    slug: 'mgi-24v-lithium-battery-36-hole',
    name: 'MGI 24V Lithium Battery (24-Spindle / 36 Hole)',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Walk-Behind Battery',
    price_aud: 450,
    price_display: '$450 AUD',
    search_intent: 'High Volume Consumer Replacement',
    target_audience: 'Owners of MGI Zip & Ai Series buggies',
    key_specs: '24V 380Wh Capacity, Advanced BMS, Click & Go Design',
    shortDescription: 'Genuine replacement 36-hole lithium battery for all MGI Zip Navigator and Ai Series motorized buggies.',
    badge: 'Genuine MGI Part',
    featured: false,
    images: ['/images/mgi-24v-lithium-battery-36-hole.webp'],
    inStock: true,
  },
  {
    id: 'PART-008',
    slug: 'curtis-1268-400a-programmable-motor-controller',
    name: 'Curtis 1268 400A Programmable Motor Controller',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Electrical Component',
    price_aud: 890,
    price_display: '$890 AUD',
    search_intent: 'Performance Upgrade',
    target_audience: 'Lifted cart builders, performance tuners',
    key_specs: '400 Amp Peak Output, Regenerative Braking Control, Programmable Curves',
    shortDescription: 'Heavy-duty 400-amp programmable motor speed controller for lifted and high-torque cart conversions.',
    badge: '400A Peak',
    featured: false,
    images: ['/images/curtis-1268-400a-programmable-motor-controller.webp'],
    inStock: true,
  },
  {
    id: 'PART-009',
    slug: 'navitas-600a-ac-controller-upgrade-kit',
    name: 'Navitas 600A AC Controller Upgrade Kit',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Electrical Component',
    price_aud: 1450,
    price_display: '$1,450 AUD',
    search_intent: 'High Intent Performance',
    target_audience: 'Golfers needing speed (40+ km/h) & hill climbing torque',
    key_specs: 'Bluetooth On-the-Fly Lockout Control, Up to 600 Amps Output',
    shortDescription: 'Unleashes blistering 40+ km/h speeds and massive hill torque with on-the-fly dashboard adjustment dial.',
    badge: '600A High Power',
    featured: true,
    images: ['/images/navitas-600a-ac-controller-upgrade-kit.webp'],
    inStock: true,
  },
  {
    id: 'PART-010',
    slug: 'universal-48v-to-12v-30a-voltage-reducer',
    name: 'Universal 48V/36V to 12V 30A Voltage Reducer',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Electrical Component',
    price_aud: 85,
    price_display: '$85 AUD',
    search_intent: 'Accessory Install',
    target_audience: 'DIY cart builders adding lights, audio, or horns',
    key_specs: 'Key-Switch Triggered, Waterproof Cast Aluminum Housing',
    shortDescription: 'Step-down converter allowing safe 12V supply for LED lights, audio soundbars, and USB phone chargers.',
    badge: 'Essential Upgrade',
    featured: false,
    images: ['/images/universal-48v-to-12v-30a-voltage-reducer.webp'],
    inStock: true,
  },
  {
    id: 'PART-011',
    slug: 'madjax-alpha-lux-street-legal-led-light-kit',
    name: 'MadJax Alpha Lux Street Legal LED Light Kit',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Accessories & Lighting',
    price_aud: 320,
    price_display: '$320 AUD',
    search_intent: 'Street-Legal Conversion',
    target_audience: 'Gated estate drivers driving at night',
    key_specs: 'Automotive Turn Signals, Hazard Lights, Horn, Brake Switch Included',
    shortDescription: 'High-intensity automotive LED projector headlights, sequential turn signals, brake switch, and mechanical horn.',
    badge: 'Street Legal Spec',
    featured: false,
    images: ['/images/madjax-alpha-lux-street-legal-led-light-kit.webp'],
    inStock: true,
  },
  {
    id: 'PART-012',
    slug: 'heavy-duty-4-wheel-hydraulic-disc-brake-kit',
    name: 'Heavy Duty 4-Wheel Hydraulic Disc Brake Kit',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Mechanical Part',
    price_aud: 750,
    price_display: '$750 AUD',
    search_intent: 'Safety / Performance',
    target_audience: 'Heavy utility and fast lifted cart owners',
    key_specs: 'Dual-Piston Calipers, Stainless Steel Lines, Direct Bolt-On',
    shortDescription: 'Replaces weak factory rear drum brakes with automotive dual-piston hydraulic disc brakes on all four wheels.',
    badge: '4-Wheel Hydraulic',
    featured: false,
    images: ['/images/heavy-duty-4-wheel-hydraulic-disc-brake-kit.webp'],
    inStock: true,
  },
  {
    id: 'PART-013',
    slug: 'all-weather-heavy-duty-pvc-enclosure',
    name: 'All-Weather Heavy-Duty PVC Enclosure',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Accessories',
    price_aud: 290,
    price_display: '$290 AUD',
    search_intent: 'High Volume Accessory',
    target_audience: 'Golfers playing in rain, winter drivers',
    key_specs: 'Roll-Up Clear Vinyl Windows, Heavy Duty Zippers, Universal Fit Options',
    shortDescription: 'Heavy-duty 4-sided weather enclosure with crystal clear marine vinyl roll-up windows and reinforced brass eyelets.',
    badge: 'All-Weather',
    featured: false,
    images: ['/images/all-weather-heavy-duty-pvc-enclosure.webp'],
    inStock: true,
  },
  {
    id: 'PART-014',
    slug: 'all-terrain-23x10-5-12-wheel-tyre-combo',
    name: 'All-Terrain 23x10.5-12 Wheel & Tyre Combo (Set of 4)',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Wheels & Tires',
    price_aud: 850,
    price_display: '$850 AUD',
    search_intent: 'Visual & Off-Road Upgrade',
    target_audience: 'Lifted cart owners, property buyers',
    key_specs: '12-inch Machined Alloy Rims, 6-ply Off-Road Tread, Includes Lug Nuts',
    shortDescription: 'Aggressive 23-inch 6-ply puncture-resistant tyres mounted on diamond-cut 12-inch aluminum alloy wheels.',
    badge: 'Set of 4 Rims & Tyres',
    featured: true,
    images: ['/images/all-terrain-23x10-5-12-wheel-tyre-combo.webp'],
    inStock: true,
  },
  {
    id: 'PART-015',
    slug: 'foldable-tinted-acrylic-windshield-system',
    name: 'Foldable Tinted Acrylic Windshield System',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Body Accessory',
    price_aud: 160,
    price_display: '$160 AUD',
    search_intent: 'Replacement / Upgrade',
    target_audience: 'Club Car, EZGO, and Yamaha owners',
    key_specs: 'High-Impact Acrylic, Snug Noise-Reduction Clips, UV Protection',
    shortDescription: 'Smoke tinted UV-blocking split windshield that folds down for refreshing summer breeze.',
    badge: 'UV Tinted',
    featured: false,
    images: ['/images/foldable-tinted-acrylic-windshield-system.webp'],
    inStock: true,
  },
  {
    id: 'PART-016',
    slug: 'heavy-duty-solenoid-albright-48vdc-200a',
    name: 'Heavy Duty Solenoid Albright 48VDC 200A',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Electrical Maintenance',
    price_aud: 120,
    price_display: '$120 AUD',
    search_intent: 'Repair / Maintenance',
    target_audience: 'Carts experiencing ignition or starting issues',
    key_specs: 'Continuous Duty Rating, Silver Alloy Contacts',
    shortDescription: 'Industrial continuous duty Albright 48V solenoid with silver alloy contacts to handle high current spikes.',
    badge: 'Continuous Duty',
    featured: false,
    images: ['/images/heavy-duty-solenoid-albright-48vdc-200a.webp'],
    inStock: true,
  },
  {
    id: 'PART-017',
    slug: 'replacement-mgi-ai-zip-remote-controller',
    name: 'Replacement MGI Ai & Zip Remote Controller Unit',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Walk-Behind Part',
    price_aud: 190,
    price_display: '$190 AUD',
    search_intent: 'High Intent Replacement',
    target_audience: 'MGI buggy owners who lost or damaged their remote',
    key_specs: 'Pre-programmed Pairing Capability, USB-C Rechargeable',
    shortDescription: 'Official replacement handheld directional remote control unit for MGI Zip Navigator and Ai Series buggies.',
    badge: 'Official MGI Remote',
    featured: false,
    images: ['/images/replacement-mgi-ai-zip-remote-controller.webp'],
    inStock: true,
  },
  {
    id: 'PART-018',
    slug: 'golf-cart-side-mirrors-integrated-led-indicators',
    name: 'Golf Cart Side Mirrors with Integrated LED Indicators',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Safety Accessory',
    price_aud: 95,
    price_display: '$95 AUD',
    search_intent: 'Safety Upgrade',
    target_audience: 'Road-registered or estate golf buggy users',
    key_specs: 'Convex Glass for Wide Angle View, Integrated LED Amber Indicators',
    shortDescription: 'Wide-angle convex mirrors with built-in amber LED turn signal indicators on mirror face.',
    badge: 'LED Turn Mirror',
    featured: false,
    images: ['/images/golf-cart-side-mirrors-integrated-led-indicators.webp'],
    inStock: true,
  },
  {
    id: 'PART-019',
    slug: 'heavy-duty-rear-flip-seat-kit-2-to-4',
    name: 'Heavy Duty Rear Flip Seat Kit (Converts 2 to 4 Seater)',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Body Upgrade',
    price_aud: 650,
    price_display: '$650 AUD',
    search_intent: 'High Search Volume Conversion',
    target_audience: 'Owners wanting to expand 2-seater capacity to 4',
    key_specs: 'Folds Flat into Flatbed Cargo Tray, Powder-Coated Steel Frame',
    shortDescription: 'Transforms any standard 2-seater cart into a 4-passenger cruiser or a heavy flatbed cargo hauler.',
    badge: '2-in-1 Conversion',
    featured: true,
    images: ['/images/heavy-duty-rear-flip-seat-kit-2-to-4.webp'],
    inStock: true,
  },
  {
    id: 'PART-020',
    slug: 'heavy-duty-tow-hitch-ball-assembly',
    name: 'Heavy Duty Tow Hitch & Ball Assembly',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Utility Accessory',
    price_aud: 110,
    price_display: '$110 AUD',
    search_intent: 'Utility / Farm Work',
    target_audience: 'Farm cart owners pulling trailers or mowers',
    key_specs: '2-inch Receiver, Powder Coated Steel, Mounting Hardware Included',
    shortDescription: 'Standard 2-inch hitch receiver with 50mm chrome tow ball for towing garden trailers and sprayers.',
    badge: '50mm Tow Ball',
    featured: false,
    images: ['/images/heavy-duty-tow-hitch-ball-assembly.webp'],
    inStock: true,
  },
  {
    id: 'PART-021',
    slug: 'golf-cart-solar-charging-panel-expansion-kit',
    name: 'Golf Cart Solar Charging Panel Expansion Kit (175W)',
    category: 'Golf Buggy Batteries & Chargers',
    fuel_type: 'Solar Accessory',
    price_aud: 520,
    price_display: '$520 AUD',
    search_intent: 'High Intent Eco / Rural',
    target_audience: 'Acreage cart owners parked away from power',
    key_specs: 'Flexible Rooftop Panel, MPPT Charge Controller (36V/48V), Extends Daily Range by 20%',
    shortDescription: 'Aerodynamic flexible solar panel that mounts to cart roof to trickle charge your battery pack throughout sunny days.',
    badge: 'Solar Range Extender',
    featured: true,
    images: ['/images/golf-cart-solar-charging-panel-expansion-kit.webp'],
    inStock: true,
  },
  {
    id: 'PART-022',
    slug: 'waterproof-marine-grade-bluetooth-soundbar',
    name: 'Waterproof Marine Grade Bluetooth Soundbar (26-inch)',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Audio Accessory',
    price_aud: 420,
    price_display: '$420 AUD',
    search_intent: 'High Margin Leisure',
    target_audience: 'Resort and lifestyle cart drivers',
    key_specs: 'IP67 Waterproof, Integrated RGB Lights, Direct Clamp to Roll Cage',
    shortDescription: 'High-output marine Bluetooth audio soundbar with deep bass radiators and integrated customizable accent lighting.',
    badge: 'IP67 Marine Audio',
    featured: false,
    images: ['/images/waterproof-marine-grade-bluetooth-soundbar.webp'],
    inStock: true,
  },
  {
    id: 'PART-023',
    slug: 'retractable-seatbelt-system-set',
    name: 'Retractable Seatbelt System Set (Front & Rear)',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Safety Accessory',
    price_aud: 145,
    price_display: '$145 AUD',
    search_intent: 'Safety Compliance',
    target_audience: 'Families with kids, estate road compliance',
    key_specs: '3-Point Lap & Shoulder Harness, Bracket Kit Included, E-Mark Certified',
    shortDescription: 'E-Mark certified automatic retractable 3-point seatbelt system with heavy-duty steel mounting brackets.',
    badge: 'Safety Certified',
    featured: false,
    images: ['/images/retractable-seatbelt-system-set.webp'],
    inStock: true,
  },
  {
    id: 'PART-024',
    slug: 'lockable-dash-glove-box-storage-system',
    name: 'Lockable Dash Glove Box Storage System',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Body Accessory',
    price_aud: 185,
    price_display: '$185 AUD',
    search_intent: 'Security Upgrade',
    target_audience: 'Golfers leaving valuables at the club or resort',
    key_specs: 'Carbon Fiber Finish, Dual Keys, Custom Fitted Molding for Popular Models',
    shortDescription: 'Secure locking dual glove box compartments with carbon fiber textured lids to safeguard smartphones and keys.',
    badge: 'Lockable Security',
    featured: false,
    images: ['/images/lockable-dash-glove-box-storage-system.webp'],
    inStock: true,
  },
  {
    id: 'PART-025',
    slug: 'heavy-duty-sand-bottle-assembly-dual-set',
    name: 'Heavy Duty Sand Bottle Assembly (Dual Set)',
    category: 'Golf Buggy Accessories & Spare Parts',
    fuel_type: 'Golf Accessory',
    price_aud: 75,
    price_display: '$75 AUD',
    search_intent: 'High Volume Replacement',
    target_audience: 'Private golf cart owners, course operators',
    key_specs: 'Rattle-Free Bracket Mounts, Easy-Pour Curved Neck Design',
    shortDescription: 'Curved neck easy-pour sand divot bottles with heavy-duty rattle-free side frame mounting brackets.',
    badge: 'Course Essential',
    featured: false,
    images: ['/images/heavy-duty-sand-bottle-assembly-dual-set.webp'],
    inStock: true,
  },
];

export const FAQ = [
  {
    question: 'How do you deliver golf buggies and carts across regional Australia?',
    answer: 'We dispatch fully assembled and tested buggies from our Yatala QLD depot via specialized enclosed freight and tilt-tray carriers with direct delivery to residential estates, regional properties, and golf courses across QLD, NSW, VIC, SA, WA, and TAS.',
  },
  {
    question: 'How do lifted lithium buggies perform on steep slopes and wet paddocks?',
    answer: 'Our lifted lithium models (such as the Atlas HD and Evolution D-MAX) feature high-torque 350A/400A AC motors, 4-wheel hydraulic disc brakes, and wide all-terrain tyres that maintain superior traction on 25+ degree muddy inclines without slipping or losing power.',
  },
  {
    question: 'What is the real-world driving range of lithium golf buggies per charge?',
    answer: 'Equipped with 48V 105Ah to 110Ah lithium-ion battery packs, our 4-seater and utility buggies deliver between 65km to 90km of real-world driving range per full charge, requiring zero water maintenance and charging in just 2.5 to 4 hours.',
  },
  {
    question: 'How does ordering and enclosed freight delivery work across Australia?',
    answer: 'You can order online, over the phone, or via WhatsApp with our team. We issue an official Australian Tax Invoice and coordinate enclosed direct delivery across Australia with comprehensive pre-delivery inspection (we deliver directly to your property, business, or club).',
  },
  {
    question: 'What warranty is provided by Golf Buggies Express PTY LTD?',
    answer: 'Every new buggy includes our comprehensive Australian warranty covering chassis, motor, and controller, plus up to 5-8 years manufacturer warranty on lithium battery cells, fully backed by our Yatala QLD service center and mobile technicians.',
  },
  {
    question: 'Do you offer crypto discounts and flexible payment methods?',
    answer: 'Yes. We provide a 10% discount on orders settled via Bitcoin (BTC) or Tether (USDT). We also accept PayID / Osko for instant bank clearance, standard EFT, credit cards, and Finance in 4 interest-free installments.',
  },
  {
    question: 'How does the 5% accessory bundle discount work when purchasing with a buggy?',
    answer: 'When you purchase any accessories, battery upgrades, chargers, or weatherproof covers alongside a golf buggy, you receive an automatic 5% discount on all accessory items. This bundle discount applies across all payment methods including Finance in 4, PayID, credit cards, and bank transfer.',
  },
  {
    question: 'How does Finance in 4 work for buggies and accessories?',
    answer: 'Finance in 4 allows Australian buyers to split their order into 4 equal interest-free installments with 0% interest and instant pre-qualification. It is available on all models, parts, and accessories with flexible fortnightly or monthly schedules.',
  },
];

export const KEYWORDS = {
  primary: 'golf buggies for sale',
  primaryHubs: [
    'golf buggies for sale',
    'golf buggy for sale',
    'electric golf buggy for sale',
    'golf buggy australia',
    'golf push buggy',
  ],
  secondary: [
    'electric golf buggies for sale',
    'golf buggy electric',
    'motorised golf buggy for sale',
    'motorized golf buggy',
    'push golf buggy for sale',
    'remote control golf buggies',
    'remote control golf buggy for sale',
    'remote control golf buggy australia',
    'three wheel golf buggy',
    'foldable golf buggy',
    'folding golf buggy australia',
    'golf buggy sales',
    'electric golf buggy australia',
    'golf buggy accessories australia',
    'mgi golf buggy accessories',
    'golf buggy spares',
    'electric golf buggy parts',
    'second hand golf carts for sale',
    'best push golf buggy australia review',
    'golf trolley',
    '4 seater lifted golf cart australia',
    'electric utility buggy price',
    'lithium golf cart for acreage',
    'heavy duty off road golf buggy',
  ],
};
